// apps/nuxt/app/features/playground/matrix-orb/MatrixOrbPage.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

import DemoColorSwatches from '../DemoColorSwatches.vue'
import DemoControl from '../DemoControl.vue'
import DemoSection from '../DemoSection.vue'
import DemoSegmented from '../DemoSegmented.vue'
import DemoSlider from '../DemoSlider.vue'
import DemoStage from '../DemoStage.vue'
import DemoSwitch from '../DemoSwitch.vue'
import PlaygroundPage from '../PlaygroundPage.vue'
import { DEMO_ACCENTS } from '../demo-palette'

import MatrixOrb from './MatrixOrb.vue'
import type { MatrixOrbState } from './matrix-orb-types'
import { matrixOrbMeta } from './meta'

const ORB_STATES: MatrixOrbState[] = ['idle', 'listening', 'thinking']

/**
 * 演示场 › Ai Kit › Matrix Orb（Canvas 2D 点阵光球，零依赖）。
 * idle / listening / thinking 三态平滑混合；listening 振幅可自动包络或手动驱动（对应真实语音电平）。
 */
const { t } = useI18n()
const state = ref<MatrixOrbState>('idle')
const autoLevel = ref(true)
const level = ref(0.6)
const dots = ref(11)
const color = ref<string>(DEMO_ACCENTS[1])

const labels = computed<Record<MatrixOrbState, string>>(() => ({
  idle: t('features.playground.matrixOrb.state.idle'),
  listening: t('features.playground.matrixOrb.state.listening'),
  thinking: t('features.playground.matrixOrb.state.thinking')
}))
const stateOptions = computed(() =>
  ORB_STATES.map(id => ({ id, label: labels.value[id] }))
)
</script>

<template>
  <PlaygroundPage :meta="matrixOrbMeta">
    <DemoSection
      :description="t('features.playground.matrixOrb.stageDescription')"
      :title="t('features.playground.matrixOrb.stageTitle')"
    >
      <template #controls>
        <DemoControl :label="t('features.playground.matrixOrb.stateLabel')">
          <DemoSegmented
            v-model="state"
            :label="t('features.playground.matrixOrb.stateLabel')"
            :options="stateOptions"
          />
        </DemoControl>
        <DemoSwitch
          v-model="autoLevel"
          :label="t('features.playground.matrixOrb.autoLevel')"
        />
        <DemoControl
          v-if="!autoLevel"
          :label="t('features.playground.matrixOrb.level')"
        >
          <DemoSlider
            v-model="level"
            :format-options="{ style: 'percent' }"
            :label="t('features.playground.matrixOrb.level')"
            :max="1"
            :min="0"
            :step="0.05"
          />
        </DemoControl>
        <DemoControl :label="t('features.playground.matrixOrb.dots')">
          <DemoSlider
            v-model="dots"
            :label="t('features.playground.matrixOrb.dots')"
            :max="17"
            :min="5"
            :step="2"
            class="w-36"
          />
        </DemoControl>
        <DemoControl :label="t('features.playground.common.color')">
          <DemoColorSwatches
            v-model="color"
            :colors="DEMO_ACCENTS"
            :label="t('features.playground.common.color')"
          />
        </DemoControl>
      </template>
      <DemoStage class="min-h-80">
        <ClientOnly>
          <MatrixOrb
            :color="color"
            :dots="dots"
            :labels="labels"
            :level="autoLevel ? undefined : level"
            :size="240"
            :state="state"
          />
        </ClientOnly>
      </DemoStage>
    </DemoSection>

    <DemoSection
      :description="t('features.playground.matrixOrb.trioDescription')"
      :title="t('features.playground.matrixOrb.trioTitle')"
    >
      <DemoStage class="gap-10">
        <ClientOnly>
          <MatrixOrb
            v-for="orbState in ORB_STATES"
            :key="orbState"
            :color="color"
            :labels="labels"
            :size="140"
            :state="orbState"
          />
        </ClientOnly>
      </DemoStage>
    </DemoSection>
  </PlaygroundPage>
</template>

// apps/react/src/features/playground/matrix-orb/matrix-orb-page.tsx
import type { MatrixOrbState } from "./matrix-orb";

import { useState } from "react";

import {
  DemoControl,
  DemoSection,
  DemoStage,
  PlaygroundPage,
} from "../demo-section";
import {
  ColorSwatches,
  DemoSegmented,
  DemoSlider,
  DemoSwitch,
} from "../demo-controls";
import { DEMO_ACCENTS } from "../demo-palette";

import MatrixOrb from "./matrix-orb";
import { matrixOrbMeta } from "./meta";

import { useTranslation } from "@/i18n";

const ORB_STATES: MatrixOrbState[] = ["idle", "listening", "thinking"];

/**
 * 演示场 › Ai Kit › Matrix Orb：rare-ui `matrix-orb`（Canvas 2D 点阵光球，零依赖）。
 * idle / listening / thinking 三态平滑混合；listening 振幅可自动包络或手动驱动（对应真实语音电平）。
 * RAF 循环在 effect 内、cleanup 取消：keepAlive 切走即暂停。
 */
export function MatrixOrbPage() {
  const { t } = useTranslation();
  const [state, setState] = useState<MatrixOrbState>("idle");
  const [autoLevel, setAutoLevel] = useState(true);
  const [level, setLevel] = useState(0.6);
  const [dots, setDots] = useState(11);
  const [color, setColor] = useState<string>(DEMO_ACCENTS[1]);

  const labels: Record<MatrixOrbState, string> = {
    idle: t("features.playground.matrixOrb.state.idle"),
    listening: t("features.playground.matrixOrb.state.listening"),
    thinking: t("features.playground.matrixOrb.state.thinking"),
  };

  return (
    <PlaygroundPage meta={matrixOrbMeta}>
      <DemoSection
        controls={
          <>
            <DemoControl label={t("features.playground.matrixOrb.stateLabel")}>
              <DemoSegmented<MatrixOrbState>
                label={t("features.playground.matrixOrb.stateLabel")}
                options={ORB_STATES.map((id) => ({ id, label: labels[id] }))}
                value={state}
                onChange={setState}
              />
            </DemoControl>
            <DemoSwitch
              isSelected={autoLevel}
              label={t("features.playground.matrixOrb.autoLevel")}
              onChange={setAutoLevel}
            />
            {!autoLevel ? (
              <DemoControl label={t("features.playground.matrixOrb.level")}>
                <DemoSlider
                  formatOptions={{ style: "percent" }}
                  label={t("features.playground.matrixOrb.level")}
                  maxValue={1}
                  minValue={0}
                  step={0.05}
                  value={level}
                  onChange={setLevel}
                />
              </DemoControl>
            ) : null}
            <DemoControl label={t("features.playground.matrixOrb.dots")}>
              <DemoSlider
                className="w-36"
                label={t("features.playground.matrixOrb.dots")}
                maxValue={17}
                minValue={5}
                step={2}
                value={dots}
                onChange={setDots}
              />
            </DemoControl>
            <DemoControl label={t("features.playground.common.color")}>
              <ColorSwatches
                colors={DEMO_ACCENTS}
                label={t("features.playground.common.color")}
                value={color}
                onChange={setColor}
              />
            </DemoControl>
          </>
        }
        description={t("features.playground.matrixOrb.stageDescription")}
        title={t("features.playground.matrixOrb.stageTitle")}
      >
        <DemoStage className="min-h-80">
          <MatrixOrb
            color={color}
            dots={dots}
            labels={labels}
            level={autoLevel ? undefined : level}
            size={240}
            state={state}
          />
        </DemoStage>
      </DemoSection>

      <DemoSection
        description={t("features.playground.matrixOrb.trioDescription")}
        title={t("features.playground.matrixOrb.trioTitle")}
      >
        <DemoStage className="gap-10">
          {ORB_STATES.map((orbState) => (
            <MatrixOrb
              key={orbState}
              color={color}
              labels={labels}
              size={140}
              state={orbState}
            />
          ))}
        </DemoStage>
      </DemoSection>
    </PlaygroundPage>
  );
}
