// apps/nuxt/app/features/roles/RolesPage.vue
<script setup lang="ts">
import type { Role } from '@/lib/api-types'
import type { AppColumnDef, AppTable } from '@/components/data-table/table-types'

import { computed, h, ref, resolveComponent } from 'vue'
import { useQueryClient } from '@tanstack/vue-query'
import { useVueTable, getCoreRowModel, getSortedRowModel } from '@tanstack/vue-table'

import {
  deleteRole,
  getRoleErrorMessage,
  ROLES_QUERY_KEY,
  updateRole
} from './role-api'
import RoleFormDialog from './RoleFormDialog.vue'
import RoleGrantDrawer from './RoleGrantDrawer.vue'
import RoleMembersDrawer from './RoleMembersDrawer.vue'
import RolesRowActions from './RolesRowActions.vue'

import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import DataTable from '@/components/data-table/DataTable.vue'
import DataTableSearchReset from '@/components/data-table/DataTableSearchReset.vue'
import DataTableToolbar from '@/components/data-table/DataTableToolbar.vue'
import { useColumnSettingKey } from '@/composables/use-column-setting-key'
import Spinner from '@/components/ui/spinner/index.vue'
import { MENUS_QUERY_KEY } from '@/composables/use-menus'
import { useMenuPermissions } from '@/composables/use-permissions'
import { useListQuery } from '@/composables/use-list-query'
import { createListStore } from '@/lib/list-store'
import { formatDateTime } from '@/lib/format-date'
import { SUPER_ADMIN_ROLE_CODE } from '@/lib/constants'

/**
 * 角色管理页（对齐 React 端 roles-page）：服务端分页列表
 * （page/pageSize/search/enabled）+ CRUD + 菜单授权。
 *
 * - 状态切换走 PUT /roles/:id 的 enabled 字段（EDIT 位）；
 * - 删除为强确认（输入角色 code），已关联用户由后端 409 ROLE_IN_USE 拦截；
 * - 菜单授权为右侧 Drawer（GRANT 位控制入口），保存后失效导航菜单缓存：
 *   若改的是当前用户自己的角色，侧边栏与按钮权限立即生效；
 * - super_admin 行：授权/删除/状态切换不可用（全量权限载体，后端 403 兜底）；
 *   编辑保留——name/description 无权限语义。
 */

/** 列表 store（模块级单例：导航返回复用同一份分页/筛选状态） */
const rolesListStore = createListStore<{ enabled: string | null }>({
  enabled: null
})

const { t, locale } = useI18n()
const toast = useToast()
const queryClient = useQueryClient()
const store = rolesListStore

const { canAdd, canEdit, canDelete, canGrant } = useMenuPermissions()

const {
  data,
  pagination,
  isLoading,
  isFetching,
  isError,
  refetch,
  submitSearch
} = useListQuery<Role, { enabled: string | null }>({
  store,
  queryKeyPrefix: ROLES_QUERY_KEY,
  path: '/roles',
  buildFilters: f => (f.enabled ? { enabled: f.enabled } : {})
})

// 搜索（提交式后端过滤）；
// 条件未变化时 submitSearch 走 refetch，搜索按钮即「刷新列表」入口
const searchInput = ref(store.search)

function applySearch() {
  submitSearch(searchInput.value.trim())
}

const searchDirty = computed(() => searchInput.value.trim() !== store.search)

function resetFilters() {
  searchInput.value = ''
  store.reset()
}

const filterOptions = computed(() => [
  { label: t('features.roles.filter.enabled'), value: 'true' },
  { label: t('features.roles.filter.disabled'), value: 'false' }
])

// ---------------- 弹窗状态 ----------------
const formOpen = ref(false)
const formMode = ref<'create' | 'edit'>('create')
const formRole = ref<Role | null>(null)

const grantOpen = ref(false)
const grantRole = ref<Role | null>(null)

const deleteOpen = ref(false)
const deleteTarget = ref<Role | null>(null)
const deleteSubmitting = ref(false)

const membersOpen = ref(false)
const membersRole = ref<Role | null>(null)

/** 关联用户穿透：点击列表「关联用户」列 +N 打开（契约 v1.13.0） */
function openMembers(role: Role) {
  membersRole.value = role
  membersOpen.value = true
}

function openForm(mode: 'create' | 'edit', role: Role | null) {
  formMode.value = mode
  formRole.value = role
  formOpen.value = true
}

function invalidateList() {
  void queryClient.invalidateQueries({ queryKey: ROLES_QUERY_KEY })
}

/** 授权保存后：失效导航菜单缓存（当前用户自己的角色授权立即生效） */
function handleGrantSaved() {
  void queryClient.invalidateQueries({ queryKey: MENUS_QUERY_KEY })
}

/** 状态切换（PUT enabled 字段；toast.promise 三段反馈：启用中/停用中 → 成功/失败） */
async function toggleStatus(role: Role) {
  const enabling = !role.enabled

  const loadingToast = toast.add({
    title: t(
      enabling
        ? 'features.roles.message.enabling'
        : 'features.roles.message.disabling'
    ),
    icon: h(Spinner, { size: 'sm', class: 'mt-0.5' }),
    color: 'info',
    duration: 0
  })

  try {
    await updateRole(role.id, { name: role.name, enabled: enabling })
    invalidateList()
    toast.update(loadingToast.id, {
      title: t('features.roles.message.statusSuccess'),
      icon: 'i-lucide-check',
      color: 'success'
    })
  } catch (error) {
    toast.update(loadingToast.id, {
      title: getRoleErrorMessage(error),
      icon: 'i-lucide-x',
      color: 'error'
    })
  }
}

async function confirmDelete() {
  if (!deleteTarget.value) return

  deleteSubmitting.value = true

  try {
    await deleteRole(deleteTarget.value.id)
  } catch (error) {
    toast.add({
      color: 'error',
      title: getRoleErrorMessage(error)
    })

    return // 失败保持弹窗打开
  } finally {
    deleteSubmitting.value = false
  }

  invalidateList()
  deleteOpen.value = false
  toast.add({
    color: 'success',
    title: t('features.roles.message.deleteSuccess')
  })
}

// ---------------- 表格 ----------------
const columns = computed<AppColumnDef<Role>[]>(() => [
  {
    id: 'name',
    enableSorting: false,
    header: () => t('features.roles.column.name'),
    cell: ({ row }) =>
      h(
        'div',
        { class: 'flex items-center gap-2' },
        h('span', { class: 'text-sm font-medium' }, row.original.name)
      )
  },
  {
    id: 'code',
    enableSorting: false,
    header: () => t('features.roles.column.code'),
    cell: ({ row }) =>
      h('span', { class: 'font-mono text-sm' }, row.original.code)
  },
  {
    id: 'description',
    enableSorting: false,
    header: () => t('features.roles.column.description'),
    cell: ({ row }) =>
      h(
        'span',
        { class: 'text-muted max-w-64 truncate text-sm' },
        row.original.description || '—'
      )
  },
  {
    id: 'readers',
    enableSorting: false,
    header: () => t('features.roles.column.readers'),
    cell: ({ row }) => {
      const readers = row.original.readers ?? []

      // 无关联用户占位；有则 UAvatarGroup 堆叠（最多 3 个），超出部分 +N
      // （N = userCount - 3），点击 +N 打开关联用户名单抽屉（契约 v1.13.0）。
      // +N 须自绘（组内置计数基于 children 数，服务端只回 3 个不会触发）；
      // 组件内部先对 children reverse 再以 flex-row-reverse 渲染，双重反转
      // 后视觉顺序 == children 传入顺序，故按 [头像正序..., +N] 传即得
      // React 端形态（+N 在尾部）；UAvatar 透传点击与键盘可达性
      if (readers.length === 0) {
        return h('span', { class: 'text-muted text-sm' }, '—')
      }
      const shown = readers.slice(0, 3)
      const extra = Math.max(
        (row.original.userCount ?? shown.length) - shown.length,
        0
      )
      const open = () => openMembers(row.original)

      return h(UAvatarGroup, { size: 'sm' }, () => [
        ...shown.map(reader =>
          h(UAvatar, {
            key: reader.id,
            alt: reader.name,
            src: reader.avatar ?? undefined,
            text: reader.name.slice(0, 1)
          })
        ),
        ...(extra > 0
          ? [
              h(UAvatar, {
                'text': `+${extra}`,
                'class': 'cursor-pointer transition-opacity hover:opacity-80',
                'role': 'button',
                'tabindex': 0,
                'aria-label': t('features.roles.members.title', {
                  name: row.original.name
                }),
                'onClick': open,
                'onKeydown': (event: KeyboardEvent) => {
                  if (event.key === 'Enter' || event.key === ' ') {
                    event.preventDefault()
                    open()
                  }
                }
              })
            ]
          : [])
      ])
    }
  },
  {
    id: 'sort',
    enableSorting: false,
    header: () => t('common.column.sort'),
    cell: ({ row }) =>
      h(UBadge, {
        color: 'neutral',
        label: String(row.original.sort),
        variant: 'soft'
      })
  },
  {
    id: 'enabled',
    enableSorting: false,
    header: () => t('features.roles.column.enabled'),
    cell: ({ row }) =>
      h(UBadge, {
        color: row.original.enabled ? 'success' : 'error',
        label: t(
          row.original.enabled
            ? 'features.roles.filter.enabled'
            : 'features.roles.filter.disabled'
        ),
        variant: 'soft'
      })
  },
  {
    id: 'createdAt',
    enableSorting: false,
    header: () => t('common.column.createdAt'),
    cell: ({ row }) =>
      h(
        'span',
        { class: 'text-muted text-sm' },
        formatDateTime(row.original.createdAt, locale.value)
      )
  },
  {
    id: 'actions',
    enableSorting: false,
    enableHiding: false,
    header: () => t('common.actions'),
    cell: ({ row }) => {
      // 系统内置角色保护：super_admin 的授权/删除/状态切换均不可用
      const isSuperAdmin = row.original.code === SUPER_ADMIN_ROLE_CODE
      const canGrantRow = canGrant.value && !isSuperAdmin
      const canToggle = canEdit.value && !isSuperAdmin
      const canDeleteRow = canDelete.value && !isSuperAdmin

      if (!canGrantRow && !canEdit.value && !canDeleteRow) return null

      return h(RolesRowActions, {
        role: row.original,
        canEdit: canEdit.value,
        canGrantRow,
        canToggle,
        canDeleteRow,
        onAction: (key) => {
          if (key === 'grant') {
            grantRole.value = row.original
            grantOpen.value = true
          }
          if (key === 'edit') openForm('edit', row.original)
          if (key === 'toggle' && canToggle) void toggleStatus(row.original)
          if (key === 'delete') {
            deleteTarget.value = row.original
            deleteOpen.value = true
          }
        }
      })
    }
  }
])

const columnSettingKey = useColumnSettingKey('/settings/roles')

const table: AppTable<Role> = useVueTable({
  get data() {
    return data.value
  },
  get columns() {
    return columns.value
  },
  getCoreRowModel: getCoreRowModel(),
  getSortedRowModel: getSortedRowModel(),
  getRowId: (row: Role) => row.id,
  // 服务端分页：分页状态由列表 store 驱动（受控），仅取数
  manualPagination: true,
  // pageCount 必须用 getter 实时求值：setup 时 total 为 0 会写死为 1，
  // setPageIndex 被 clamp 导致永远翻不了页（对齐 React 每次渲染重建 options）
  get pageCount() {
    return Math.max(1, Math.ceil(pagination.value.total / store.pageSize))
  },
  state: {
    get pagination() {
      return { pageIndex: store.page - 1, pageSize: store.pageSize }
    }
  },
  onPaginationChange: (updater) => {
    const next
      = typeof updater === 'function'
        ? updater({ pageIndex: store.page - 1, pageSize: store.pageSize })
        : updater

    if (next.pageSize !== store.pageSize) {
      store.setPageSize(next.pageSize)
    } else {
      store.setPage(next.pageIndex + 1)
    }
  }
})

// 组件引用（供 h() 使用）
const UBadge = resolveComponent('UBadge')
const UAvatar = resolveComponent('UAvatar')
const UAvatarGroup = resolveComponent('UAvatarGroup')
</script>

<template>
  <div class="flex w-full flex-col gap-4">
    <DataTableToolbar
      :column-setting-key="columnSettingKey"
      :table="table"
    >
      <UInput
        v-model="searchInput"
        :aria-label="t('features.roles.searchPlaceholder')"
        :placeholder="t('features.roles.searchPlaceholder')"
        class="w-64"
        icon="i-lucide-search"
        @keyup.enter="applySearch"
      />
      <USelectMenu
        :aria-label="t('features.roles.column.enabled')"
        :items="filterOptions"
        :model-value="store.filters.enabled ?? undefined"
        :placeholder="t('features.roles.column.enabled')"
        class="w-36"
        value-key="value"
        clear
        :search-input="false"
        @update:model-value="
          (value: unknown) => store.setFilters({ enabled: value as string })
        "
      />
      <DataTableSearchReset
        :can-reset="
          searchDirty || store.search !== '' || store.filters.enabled !== null
        "
        :fetching="isFetching"
        @reset="resetFilters"
        @search="applySearch"
      />
      <UButton
        v-if="canAdd"
        :label="t('features.roles.action.add')"
        icon="i-lucide-plus"
        variant="outline"
        @click="openForm('create', null)"
      />
    </DataTableToolbar>

    <DataTable
      :is-error="isError"
      :loading="isLoading"
      :refreshing="isFetching && !isLoading"
      :table="table"
      :total="pagination.total"
      @retry="refetch()"
    />

    <RoleFormDialog
      v-model:open="formOpen"
      :mode="formMode"
      :role="formRole"
      @saved="invalidateList"
    />

    <RoleGrantDrawer
      v-model:open="grantOpen"
      :role="
        grantOpen && grantRole
          ? { id: grantRole.id, name: grantRole.name, code: grantRole.code }
          : null
      "
      @saved="handleGrantSaved"
    />

    <RoleMembersDrawer
      v-model:open="membersOpen"
      :role="membersRole"
    />

    <ConfirmDialog
      v-model:open="deleteOpen"
      :confirm-keyword="deleteTarget?.code"
      :confirm-text="t('common.delete')"
      :description="
        t('features.roles.message.deleteDesc', {
          name: deleteTarget?.name ?? ''
        })
      "
      :keyword-label="t('features.roles.message.deleteKeyword')"
      :loading="deleteSubmitting"
      :title="t('features.roles.message.deleteTitle')"
      destructive
      @confirm="confirmDelete"
    />
  </div>
</template>

// apps/react/src/features/roles/roles-page.tsx
import type { Role } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/common/data-table/table-types";

import { useQueryClient } from "@tanstack/react-query";
import { useTable } from "@tanstack/react-table";
import {
  Avatar,
  AvatarGroup,
  Button,
  Chip,
  Dropdown,
  Label,
  SearchField,
  Typography,
  toast,
  useOverlayState,
} from "@heroui/react";
import {
  KeyRound,
  MoreHorizontal,
  Pencil,
  Plus,
  Power,
  ShieldCheck,
  Trash2,
} from "lucide-react";
import { useCallback, useMemo, useState } from "react";

import {
  ROLES_QUERY_KEY,
  deleteRole,
  getRoleErrorMessage,
  updateRole,
} from "./role-api";
import { RoleFormDialog, type RoleFormMode } from "./role-form-dialog";
import { RoleGrantDrawer } from "./role-grant-drawer";
import { RoleMembersDrawer } from "./role-members-drawer";

import { DataTable } from "@/components/common/data-table";
import {
  DataTableFilterSelect,
  DataTableSearchReset,
  DataTableToolbar,
  buildColumnSettingKey,
} from "@/components/common/data-table";
import { ConfirmDialog } from "@/components/common/confirm-dialog/confirm-dialog";
import { appTableFeatures } from "@/components/common/data-table/table-types";
import { MENUS_QUERY_KEY } from "@/hooks/use-menus";
import { useMenuPermissions } from "@/hooks/use-permissions";
import { createListStore } from "@/hooks/create-list-store";
import { useListQuery } from "@/hooks/use-list-query";
import { useTranslation } from "@/i18n";
import { formatDateTime } from "@/lib/format-date";
import { SUPER_ADMIN_ROLE_CODE } from "@/lib/constants";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 角色管理页：服务端分页列表（page/pageSize/search/enabled）+ CRUD + 菜单授权。
 *
 * - 列表状态（分页/搜索/筛选）入 feature store（keepAlive 友好），由
 *   useListQuery 装配请求与 queryKey；
 * - 状态切换走 PUT /roles/:id 的 enabled 字段（EDIT 位），下拉里快捷开关；
 * - 删除为强确认（输入角色 code），已关联用户由后端 409 ROLE_IN_USE 拦截；
 * - 菜单授权为右侧 Drawer（父子联动语义见 role-grant-drawer.tsx），
 *   入口由独立 GRANT 位控制（契约 v1.4.4，后端 PUT /roles/:id/menus 同步守卫）；
 *   保存后失效导航菜单缓存：后端 /menus 实时计算 userPermissions，
 *   若改的是当前用户自己的角色，侧边栏与按钮权限立即生效。
 */

/** 列表 store（模块级单例：保活实例复用同一份分页/筛选状态） */
const useRolesListStore = createListStore<{ enabled: string | null }>({
  enabled: null,
});

export function RolesPage() {
  const { t, i18n } = useTranslation();
  const queryClient = useQueryClient();
  const userId = useAuthStore((state) => state.user?.id);
  const { canAdd, canEdit, canDelete, canGrant } = useMenuPermissions();
  // ---------------- 列表（服务端分页 + 筛选） ----------------
  const page = useRolesListStore((s) => s.page);
  const pageSize = useRolesListStore((s) => s.pageSize);
  const search = useRolesListStore((s) => s.search);
  const filters = useRolesListStore((s) => s.filters);
  // actions 为稳定引用（zustand 模式），经 selector 取出不触发多余重渲染
  const setPage = useRolesListStore((s) => s.setPage);
  const setPageSize = useRolesListStore((s) => s.setPageSize);
  const setFilters = useRolesListStore((s) => s.setFilters);
  const resetStore = useRolesListStore((s) => s.reset);

  const {
    data,
    pagination,
    isLoading,
    isFetching,
    isError,
    refetch,
    submitSearch,
  } = useListQuery<Role, { enabled: string | null }>({
    store: useRolesListStore,
    queryKeyPrefix: ROLES_QUERY_KEY,
    path: "/roles",
    buildFilters: (f) => (f.enabled ? { enabled: f.enabled } : {}),
  });

  // 搜索（提交式后端过滤）：本地输入 → 应用到 store；
  // 条件未变化时 submitSearch 走 refetch，搜索按钮即「刷新列表」入口
  const [searchInput, setSearchInput] = useState(search);
  const applySearch = useCallback(
    () => submitSearch(searchInput.trim()),
    [submitSearch, searchInput],
  );
  const searchDirty = searchInput.trim() !== search;

  const resetFilters = useCallback(() => {
    setSearchInput("");
    resetStore();
  }, [resetStore]);

  const filterOptions = useMemo(
    () => [
      { value: "true", label: t("features.roles.filter.enabled") },
      { value: "false", label: t("features.roles.filter.disabled") },
    ],
    [t],
  );

  // ---------------- 弹窗状态（useOverlayState，§7.2 受控浮层语义） ----------------
  const roleDialog = useOverlayState();
  const grantDrawer = useOverlayState();
  const deleteDialog = useOverlayState();
  const membersDrawer = useOverlayState();
  const [formContext, setFormContext] = useState<{
    mode: RoleFormMode;
    role: Role | null;
  }>({ mode: "create", role: null });
  const [deleteTarget, setDeleteTarget] = useState<Role | null>(null);
  const [grantRole, setGrantRole] = useState<Role | null>(null);
  const [membersRole, setMembersRole] = useState<Role | null>(null);

  /** 关联用户穿透：点击列表「关联用户」列 +N 打开（契约 v1.13.0） */
  const openMembers = useCallback(
    (role: Role) => {
      setMembersRole(role);
      membersDrawer.open();
    },
    [membersDrawer.open],
  );

  const openForm = useCallback(
    (mode: RoleFormMode, role: Role | null) => {
      setFormContext({ mode, role });
      roleDialog.open();
    },
    // 依赖收敛到 useOverlayState 的稳定方法引用（对象字面量每次渲染都是新的，
    // 会使本回调与 columns useMemo 每次渲染失效重建）
    [roleDialog.open],
  );

  // ---------------- 变更操作 ----------------
  /** 列表失效：ROLES_QUERY_KEY 前缀覆盖全部分页/筛选组合 */
  const invalidateList = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: ROLES_QUERY_KEY });
  }, [queryClient]);

  const handleSaved = useCallback(() => {
    invalidateList();
  }, [invalidateList]);

  /** 授权保存后：失效导航菜单缓存（当前用户自己的角色授权立即生效） */
  const handleGrantSaved = useCallback(() => {
    void queryClient.invalidateQueries({
      queryKey: MENUS_QUERY_KEY,
      exact: true,
    });
  }, [queryClient]);

  /**
   * 状态切换（toast.promise 三段反馈：启用中/停用中 → 成功/失败）。
   * 请求成功后失效列表缓存。
   */
  const toggleStatus = useCallback(
    (role: Role) => {
      const enabling = !role.enabled;

      void toast.promise(
        updateRole(role.id, { name: role.name, enabled: enabling }).then(() =>
          invalidateList(),
        ),
        {
          loading: t(
            enabling
              ? "features.roles.message.enabling"
              : "features.roles.message.disabling",
          ),
          success: t("features.roles.message.statusSuccess"),
          error: (e) => getRoleErrorMessage(e),
        },
      );
    },
    [invalidateList, t],
  );

  const confirmDelete = useCallback(async () => {
    if (!deleteTarget) return;
    try {
      await deleteRole(deleteTarget.id);
    } catch (error) {
      toast.danger(getRoleErrorMessage(error));

      return;
    }
    invalidateList();
    toast.success(t("features.roles.message.deleteSuccess"));
  }, [deleteTarget, invalidateList, t]);

  // ---------------- 表格 ----------------
  const columns = useMemo<AppColumnDef<Role>[]>(
    () => [
      {
        id: "name",
        enableSorting: false,
        header: t("features.roles.column.name"),
        cell: ({ row }) => (
          <div className="flex items-center gap-2">
            <ShieldCheck aria-hidden className="size-4 shrink-0 text-muted" />
            <Typography className="font-medium" type="body-sm">
              {row.original.name}
            </Typography>
          </div>
        ),
      },
      {
        id: "code",
        enableSorting: false,
        header: t("features.roles.column.code"),
        cell: ({ row }) => (
          <Typography className="font-mono" type="body-sm">
            {row.original.code}
          </Typography>
        ),
      },
      {
        id: "description",
        enableSorting: false,
        header: t("features.roles.column.description"),
        cell: ({ row }) => (
          <Typography
            className="max-w-64 truncate"
            color="muted"
            type="body-sm"
          >
            {row.original.description || "—"}
          </Typography>
        ),
      },
      {
        id: "readers",
        enableSorting: false,
        header: t("features.roles.column.readers"),
        cell: ({ row }) => {
          const readers = row.original.readers ?? [];

          // 无关联用户占位；有则 AvatarGroup 堆叠（最多 3 个），超出部分 +N
          // （N = userCount - 3）点击打开关联用户名单抽屉（契约 v1.13.0）。
          // 总数服务端已知，溢出计数用显式 AvatarGroup.Count（v3.2.6）
          if (readers.length === 0) {
            return (
              <Typography color="muted" type="body-sm">
                —
              </Typography>
            );
          }
          const shown = readers.slice(0, 3);
          const extra = Math.max(
            (row.original.userCount ?? shown.length) - shown.length,
            0,
          );

          return (
            <AvatarGroup max={3} size="sm">
              {shown.map((reader) => (
                <Avatar key={reader.id}>
                  {reader.avatar ? (
                    <Avatar.Image alt={reader.name} src={reader.avatar} />
                  ) : null}
                  <Avatar.Fallback>{reader.name.slice(0, 1)}</Avatar.Fallback>
                </Avatar>
              ))}
              {extra > 0 && (
                <AvatarGroup.Count
                  aria-label={t("features.roles.members.title", {
                    name: row.original.name,
                  })}
                  className="cursor-pointer transition-opacity hover:opacity-80"
                  role="button"
                  tabIndex={0}
                  onClick={() => openMembers(row.original)}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault();
                      openMembers(row.original);
                    }
                  }}
                >
                  +{extra}
                </AvatarGroup.Count>
              )}
            </AvatarGroup>
          );
        },
      },
      {
        id: "sort",
        enableSorting: false,
        meta: { align: "center" },
        header: t("common.column.sort"),
        cell: ({ row }) => <Chip size="sm">{row.original.sort}</Chip>,
      },
      {
        id: "enabled",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.roles.column.enabled"),
        cell: ({ row }) => (
          <Chip
            color={row.original.enabled ? "success" : "danger"}
            size="sm"
            variant="soft"
          >
            {t(
              row.original.enabled
                ? "features.roles.filter.enabled"
                : "features.roles.filter.disabled",
            )}
          </Chip>
        ),
      },
      {
        id: "createdAt",
        enableSorting: false,
        meta: { align: "center" },
        header: t("common.column.createdAt"),
        cell: ({ row }) => (
          <Typography color="muted" type="body-sm">
            {formatDateTime(row.original.createdAt, i18n.language)}
          </Typography>
        ),
      },
      {
        id: "actions",
        enableSorting: false,
        enableHiding: false,
        meta: { align: "center" },
        header: t("common.actions"),
        cell: ({ row }) => {
          // 系统内置角色保护：super_admin 的授权是全量权限载体，
          // 授权/删除/状态切换均不可用（后端亦有 403 SUPER_ADMIN_ROLE_PROTECTED 兜底）；
          // 编辑保留——name/description 无权限语义
          const isSuperAdmin = row.original.code === SUPER_ADMIN_ROLE_CODE;
          const canGrantRow = canGrant && !isSuperAdmin;
          const canToggle = canEdit && !isSuperAdmin;
          const canDeleteRow = canDelete && !isSuperAdmin;

          if (!canGrantRow && !canEdit && !canDeleteRow) return null;

          return (
            <Dropdown>
              <Button
                isIconOnly
                aria-label={t("common.actions")}
                size="sm"
                variant="ghost"
              >
                <MoreHorizontal className="size-4" />
              </Button>
              <Dropdown.Popover className="min-w-36">
                <Dropdown.Menu
                  onAction={(key) => {
                    if (key === "grant") {
                      setGrantRole(row.original);
                      grantDrawer.open();
                    }
                    if (key === "edit") openForm("edit", row.original);
                    if (key === "toggle" && canToggle)
                      toggleStatus(row.original);
                    if (key === "delete") {
                      setDeleteTarget(row.original);
                      deleteDialog.open();
                    }
                  }}
                >
                  {canGrantRow && (
                    <Dropdown.Item
                      id="grant"
                      textValue={t("features.roles.action.grant")}
                    >
                      <KeyRound className="size-4 shrink-0 text-muted" />
                      <Label>{t("features.roles.action.grant")}</Label>
                    </Dropdown.Item>
                  )}
                  {canEdit && (
                    <Dropdown.Item id="edit" textValue={t("common.edit")}>
                      <Pencil className="size-4 shrink-0 text-muted" />
                      <Label>{t("common.edit")}</Label>
                    </Dropdown.Item>
                  )}
                  {canToggle && (
                    <Dropdown.Item
                      id="toggle"
                      textValue={t(
                        row.original.enabled
                          ? "features.roles.action.disable"
                          : "features.roles.action.enable",
                      )}
                    >
                      <Power
                        className={
                          row.original.enabled
                            ? "size-4 shrink-0 text-danger"
                            : "size-4 shrink-0 text-muted"
                        }
                      />
                      <Label>
                        {t(
                          row.original.enabled
                            ? "features.roles.action.disable"
                            : "features.roles.action.enable",
                        )}
                      </Label>
                    </Dropdown.Item>
                  )}
                  {canDeleteRow && (
                    <Dropdown.Item
                      id="delete"
                      textValue={t("common.delete")}
                      variant="danger"
                    >
                      <Trash2 className="size-4 shrink-0 text-danger" />
                      <Label>{t("common.delete")}</Label>
                    </Dropdown.Item>
                  )}
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown>
          );
        },
      },
    ],
    // 依赖收敛到 useOverlayState 的稳定方法引用（对象字面量每次渲染都是新的，
    // 会使 columns useMemo 每次渲染失效重建、整表重渲染）
    [
      t,
      canEdit,
      canDelete,
      canGrant,
      openForm,
      openMembers,
      grantDrawer.open,
      deleteDialog.open,
      toggleStatus,
    ],
  );

  const total = pagination.total;
  const table = useTable({
    columns,
    data,
    features: appTableFeatures,
    getRowId: (row) => row.id,
    // 服务端分页：分页状态由列表 store 驱动（受控），仅取数
    manualPagination: true,
    pageCount: Math.max(1, Math.ceil(total / pageSize)),
    state: { pagination: { pageIndex: page - 1, pageSize } },
    onPaginationChange: (updater) => {
      const next =
        typeof updater === "function"
          ? updater({ pageIndex: page - 1, pageSize })
          : updater;

      if (next.pageSize !== pageSize) {
        setPageSize(next.pageSize);
      } else {
        setPage(next.pageIndex + 1);
      }
    },
  });

  return (
    <div className="flex w-full flex-col pb-8">
      <DataTableToolbar
        columnSettingKey={
          userId ? buildColumnSettingKey(userId, "/settings/roles") : undefined
        }
        table={table}
      >
        <SearchField
          aria-label={t("features.roles.searchPlaceholder")}
          className="w-64"
          value={searchInput}
          variant="secondary"
          onChange={setSearchInput}
          onSubmit={applySearch}
        >
          <SearchField.Group>
            <SearchField.SearchIcon />
            <SearchField.Input
              placeholder={t("features.roles.searchPlaceholder")}
            />
            <SearchField.ClearButton />
          </SearchField.Group>
        </SearchField>
        {/* 状态筛选在搜索按钮前（与输入条件一起提交）；不选默认全部 */}
        <DataTableFilterSelect
          aria-label={t("features.roles.column.enabled")}
          options={filterOptions}
          placeholder={t("features.roles.column.enabled")}
          value={filters.enabled}
          onChange={(value) => setFilters({ enabled: value })}
        />
        <DataTableSearchReset
          canReset={searchDirty || search !== "" || filters.enabled !== null}
          isFetching={isFetching}
          onReset={resetFilters}
          onSearch={applySearch}
        />
        {canAdd && (
          <Button
            size="sm"
            variant="outline"
            onPress={() => openForm("create", null)}
          >
            <Plus className="size-4" />
            {t("features.roles.action.add")}
          </Button>
        )}
      </DataTableToolbar>

      <DataTable
        aria-label={t("menu.pageTitle.roles")}
        className="w-full"
        contentClassName="min-w-[760px]"
        isError={isError}
        isLoading={isLoading || isFetching}
        table={table}
        total={total}
        onRetry={() => void refetch()}
      />

      <RoleFormDialog
        isOpen={roleDialog.isOpen}
        mode={formContext.mode}
        role={formContext.role}
        onOpenChange={roleDialog.setOpen}
        onSaved={handleSaved}
      />

      <RoleGrantDrawer
        isOpen={grantDrawer.isOpen}
        role={
          grantDrawer.isOpen && grantRole
            ? {
                id: grantRole.id,
                name: grantRole.name,
                code: grantRole.code,
              }
            : null
        }
        onOpenChange={grantDrawer.setOpen}
        onSaved={handleGrantSaved}
      />

      <RoleMembersDrawer role={membersRole} state={membersDrawer} />

      <ConfirmDialog
        destructive
        confirmKeyword={deleteTarget?.code}
        confirmText={t("common.delete")}
        description={t("features.roles.message.deleteDesc", {
          name: deleteTarget?.name ?? "",
        })}
        keywordLabel={t("features.roles.message.deleteKeyword")}
        state={{
          isOpen: deleteDialog.isOpen,
          setOpen: deleteDialog.setOpen,
          close: deleteDialog.close,
        }}
        title={t("features.roles.message.deleteTitle")}
        onConfirm={confirmDelete}
      />
    </div>
  );
}
