// apps/next/src/features/playground/loaders/loaders-page.tsx
"use client";

import { useState } from "react";
import { Button } from "@heroui/react";

import {
  DemoControl,
  DemoSection,
  DemoStage,
  PlaygroundPage,
} from "../demo-section";
import { DemoSlider } from "../demo-controls";

import { loadersMeta } from "./meta";
import { Loader, type LoaderVariant } from "./loader";

import { useTranslation } from "@/i18n";

/** 全部 17 种变体（与 LoaderVariant 联合类型一一对应，编译期防漂移）。 */
const LOADER_VARIANTS = [
  "spinner",
  "dots",
  "bars",
  "dot-matrix",
  "dither",
  "morph",
  "comet",
  "scramble",
  "metaballs",
  "newton",
  "helix",
  "percent",
  "ascii",
  "ascii-line",
  "ascii-braille",
  "ascii-blocks",
  "ascii-bounce",
] as const satisfies readonly LoaderVariant[];

const SIZE_RANGE = { min: 16, max: 96, step: 4 };
const SPEED_RANGE = { min: 0.25, max: 3, step: 0.25 };

/** 变体名是技术专名，保留英文不译（与主题切换动画页的处理一致）。 */
function VariantCard({
  size,
  speed,
  variant,
}: {
  size: number;
  speed: number;
  variant: LoaderVariant;
}) {
  return (
    // 高度不写死：随 size 撑开（size=96 时 ASCII 字形 / percent 进度条均需大于
    // 固定行高的空间），grid 行内各卡等高对齐，矮内容垂直居中。
    <div className="flex min-h-24 flex-col items-center justify-center gap-3 rounded-2xl border border-border bg-default/40 p-6">
      {/* motion 对循环中的动画不应用新的 transition，speed 变化须重挂载重启 */}
      <Loader key={speed} size={size} speed={speed} variant={variant} />
      <span className="font-mono text-xs">{variant}</span>
    </div>
  );
}

/** 区块一：17 种变体全员展示墙，滑块统一调节尺寸与周期时长。 */
function VariantGridSection({
  size,
  speed,
  onSizeChange,
  onSpeedChange,
}: {
  size: number;
  speed: number;
  onSizeChange: (value: number) => void;
  onSpeedChange: (value: number) => void;
}) {
  const { t } = useTranslation();

  return (
    <DemoSection
      controls={
        <>
          <DemoControl label={t("features.playground.common.size")}>
            <DemoSlider
              label={t("features.playground.common.size")}
              maxValue={SIZE_RANGE.max}
              minValue={SIZE_RANGE.min}
              step={SIZE_RANGE.step}
              value={size}
              onChange={onSizeChange}
            />
          </DemoControl>
          <DemoControl label={t("features.playground.common.duration")}>
            <DemoSlider
              formatOptions={{ style: "unit", unit: "second" }}
              label={t("features.playground.common.duration")}
              maxValue={SPEED_RANGE.max}
              minValue={SPEED_RANGE.min}
              step={SPEED_RANGE.step}
              value={speed}
              onChange={onSpeedChange}
            />
          </DemoControl>
        </>
      }
      description={t("features.playground.loaders.variantsDescription")}
      title={t("features.playground.loaders.variantsTitle")}
    >
      {/* 5 列给 percent（宽度 size*1.4）留足余量，6 列在 size=96 时会横向溢出 */}
      <div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
        {LOADER_VARIANTS.map((variant) => (
          <VariantCard
            key={variant}
            size={size}
            speed={speed}
            variant={variant}
          />
        ))}
      </div>
    </DemoSection>
  );
}

/** 区块二：选中一种变体并调节尺寸 / 周期时长，中央大号实时预览。 */
function ParamsSection({
  size,
  speed,
  variant,
  onSizeChange,
  onSpeedChange,
  onVariantChange,
}: {
  size: number;
  speed: number;
  variant: LoaderVariant;
  onSizeChange: (value: number) => void;
  onSpeedChange: (value: number) => void;
  onVariantChange: (value: LoaderVariant) => void;
}) {
  const { t } = useTranslation();

  return (
    <DemoSection
      controls={
        <>
          <DemoControl label={t("features.playground.common.size")}>
            <DemoSlider
              label={t("features.playground.common.size")}
              maxValue={SIZE_RANGE.max}
              minValue={SIZE_RANGE.min}
              step={SIZE_RANGE.step}
              value={size}
              onChange={onSizeChange}
            />
          </DemoControl>
          <DemoControl label={t("features.playground.common.duration")}>
            <DemoSlider
              formatOptions={{ style: "unit", unit: "second" }}
              label={t("features.playground.common.duration")}
              maxValue={SPEED_RANGE.max}
              minValue={SPEED_RANGE.min}
              step={SPEED_RANGE.step}
              value={speed}
              onChange={onSpeedChange}
            />
          </DemoControl>
        </>
      }
      description={t("features.playground.loaders.paramsDescription")}
      title={t("features.playground.loaders.paramsTitle")}
    >
      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-1.5">
          <span className="text-xs text-muted">
            {t("features.playground.loaders.variant")}
          </span>
          <div className="flex flex-wrap gap-2">
            {LOADER_VARIANTS.map((item) => (
              <Button
                key={item}
                aria-label={item}
                className="font-mono text-xs"
                size="sm"
                variant={item === variant ? "primary" : "outline"}
                onPress={() => onVariantChange(item)}
              >
                {item}
              </Button>
            ))}
          </div>
        </div>
        <DemoStage className="min-h-52">
          <Loader key={speed} size={size} speed={speed} variant={variant} />
        </DemoStage>
      </div>
    </DemoSection>
  );
}

/**
 * 演示场 › 加载动画：beUI `loader`（motion 关键帧动画，单组件 17 种变体）。
 * 组件 vendor 自 beUI registry（MIT），两区块共享尺寸 / 时长参数，实时联动。
 */
export function LoadersPage() {
  const [size, setSize] = useState(36);
  const [speed, setSpeed] = useState(1);
  const [variant, setVariant] = useState<LoaderVariant>("spinner");

  return (
    <PlaygroundPage meta={loadersMeta}>
      <VariantGridSection
        size={size}
        speed={speed}
        onSizeChange={setSize}
        onSpeedChange={setSpeed}
      />
      <ParamsSection
        size={size}
        speed={speed}
        variant={variant}
        onSizeChange={setSize}
        onSpeedChange={setSpeed}
        onVariantChange={setVariant}
      />
    </PlaygroundPage>
  );
}

// apps/vue/src/features/playground/loaders/LoadersPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { useI18n } from "vue-i18n";

import DemoControl from "../DemoControl.vue";
import DemoSection from "../DemoSection.vue";
import DemoSlider from "../DemoSlider.vue";
import DemoStage from "../DemoStage.vue";
import PlaygroundPage from "../PlaygroundPage.vue";

import Loader from "./Loader.vue";
import { LOADER_VARIANTS, type LoaderVariant } from "./loader-variants";
import { loadersMeta } from "./meta";

/**
 * 演示场 › 加载动画：beUI `loader`（单组件 17 种加载动效变体）。
 *
 * 与 React 基准的差异只在动画引擎：React 用 motion 关键帧，本端按端内约定
 * （不引入 motion-v）以 CSS `@keyframes` 等效，几何与时长口径不变；React 侧
 * 因 motion 不重应用循环中的 transition 而需要 `key={speed}` 重挂载，本端改
 * CSS 变量即时生效，故页面不传 key。变体名属技术专名，保留英文不译。
 */
const SIZE_RANGE = { min: 16, max: 96, step: 4 };
const SPEED_RANGE = { min: 0.25, max: 3, step: 0.25 };

const { t } = useI18n();

const size = ref(36);
const speed = ref(1);
const variant = ref<LoaderVariant>("spinner");
</script>

<template>
  <PlaygroundPage :meta="loadersMeta">
    <!-- 区块一：17 种变体全员展示墙，滑块统一调节尺寸与周期时长 -->
    <DemoSection
      :description="t('features.playground.loaders.variantsDescription')"
      :title="t('features.playground.loaders.variantsTitle')"
    >
      <template #controls>
        <DemoControl :label="t('features.playground.common.size')">
          <DemoSlider
            v-model="size"
            :label="t('features.playground.common.size')"
            :max="SIZE_RANGE.max"
            :min="SIZE_RANGE.min"
            :step="SIZE_RANGE.step"
          />
        </DemoControl>
        <DemoControl :label="t('features.playground.common.duration')">
          <DemoSlider
            v-model="speed"
            :format-options="{ style: 'unit', unit: 'second' }"
            :label="t('features.playground.common.duration')"
            :max="SPEED_RANGE.max"
            :min="SPEED_RANGE.min"
            :step="SPEED_RANGE.step"
          />
        </DemoControl>
      </template>

      <!-- 5 列给 percent（宽度 size*1.4）留足余量，6 列在 size=96 时会横向溢出 -->
      <div class="grid gap-3 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
        <!-- 卡片高度不写死：随 size 撑开，grid 行内各卡等高、矮内容垂直居中 -->
        <div
          v-for="item in LOADER_VARIANTS"
          :key="item"
          class="border-default bg-elevated/60 flex min-h-24 flex-col items-center justify-center gap-3 rounded-2xl border p-6"
        >
          <Loader :size="size" :speed="speed" :variant="item" />
          <span class="font-mono text-xs">{{ item }}</span>
        </div>
      </div>
    </DemoSection>

    <!-- 区块二：选中一种变体并调节尺寸 / 周期时长，中央大号实时预览 -->
    <DemoSection
      :description="t('features.playground.loaders.paramsDescription')"
      :title="t('features.playground.loaders.paramsTitle')"
    >
      <template #controls>
        <DemoControl :label="t('features.playground.common.size')">
          <DemoSlider
            v-model="size"
            :label="t('features.playground.common.size')"
            :max="SIZE_RANGE.max"
            :min="SIZE_RANGE.min"
            :step="SIZE_RANGE.step"
          />
        </DemoControl>
        <DemoControl :label="t('features.playground.common.duration')">
          <DemoSlider
            v-model="speed"
            :format-options="{ style: 'unit', unit: 'second' }"
            :label="t('features.playground.common.duration')"
            :max="SPEED_RANGE.max"
            :min="SPEED_RANGE.min"
            :step="SPEED_RANGE.step"
          />
        </DemoControl>
      </template>

      <div class="flex flex-col gap-4">
        <div class="flex flex-col gap-1.5">
          <span class="text-muted text-xs">
            {{ t("features.playground.loaders.variant") }}
          </span>
          <div class="flex flex-wrap gap-2">
            <UButton
              v-for="item in LOADER_VARIANTS"
              :key="item"
              :aria-label="item"
              :label="item"
              :variant="item === variant ? 'solid' : 'outline'"
              class="font-mono text-xs"
              size="sm"
              @click="variant = item"
            />
          </div>
        </div>
        <DemoStage class="min-h-52">
          <Loader :size="size" :speed="speed" :variant="variant" />
        </DemoStage>
      </div>
    </DemoSection>
  </PlaygroundPage>
</template>
