// apps/vue/src/pages/(authenticated)/playground/github-activity.vue
<script setup lang="ts">
import { useI18n } from "vue-i18n";

import PlaceholderPage from "@/components/PlaceholderPage.vue";

// 演示场 › GitHub Activity（Phase A 占位；Phase B 按 plan-dashboard-playground.md §6 实现）
const { t } = useI18n();
</script>

<template>
  <PlaceholderPage
    icon="i-lucide-calendar-days"
    title-key="menu.playground.githubActivity"
    :description="t('features.playground.placeholder')"
  />
</template>

// apps/react/src/routes/_authenticated/playground/github-activity.tsx
import { createFileRoute } from "@tanstack/react-router";

import { PlaceholderPage } from "@/components/common/placeholder-page";

/** 演示场 › GitHub Activity（Phase A 占位；Phase B 按 plan-dashboard-playground.md §6 实现）。 */
export const Route = createFileRoute(
  "/_authenticated/playground/github-activity",
)({
  staticData: { titleKey: "menu.playground.githubActivity" },
  component: () => (
    <PlaceholderPage
      descriptionKey="features.playground.placeholder"
      icon="calendar-days"
      titleKey="menu.playground.githubActivity"
    />
  ),
});
