// apps/react/src/routes/_authenticated/playground/ai-kit/fluid-orb.tsx
import { createFileRoute } from "@tanstack/react-router";

import { PlaceholderPage } from "@/components/common/placeholder-page";

/** 演示场 › Ai Kit › Fluid Orb（Phase A 占位；Phase B 按 plan-dashboard-playground.md §6 实现）。 */
export const Route = createFileRoute(
  "/_authenticated/playground/ai-kit/fluid-orb",
)({
  staticData: { titleKey: "menu.playground.fluidOrb" },
  component: () => (
    <PlaceholderPage
      descriptionKey="features.playground.placeholder"
      icon="orbit"
      titleKey="menu.playground.fluidOrb"
    />
  ),
});

// apps/nuxt/app/pages/(authenticated)/playground/ai-kit/fluid-orb.vue
<script setup lang="ts">
// 演示场 › Ai Kit › Fluid Orb（Phase A 占位；Phase B 按 plan-dashboard-playground.md §6 实现）。
// script setup 块不可省略：纯模板 SFC 无 __name，Nuxt keepalive 分支会按组件名
// 混用 RouteProvider（mechanisms.md §26）。
const { t } = useI18n()
</script>

<template>
  <PlaceholderPage
    icon="i-lucide-orbit"
    title-key="menu.playground.fluidOrb"
    :description="t('features.playground.placeholder')"
  />
</template>
