// next/src/features/dicts/dict-item-form-dialog.tsx
"use client";

import type { DictItem } from "@/lib/api-types";
import type { DictItemSaveInput } from "./dict-api";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import {
  Button,
  Description,
  FieldError,
  Form,
  InputGroup,
  Label,
  Modal,
  Spinner,
  Switch,
  TextField,
  toast,
} from "@heroui/react";
import { Check, X } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import {
  createDictItem,
  getDictErrorMessage,
  updateDictItem,
} from "./dict-api";

import {
  SortField,
  sortFieldSchema,
} from "@/components/common/sort-field/sort-field";
import { useTranslation } from "@/i18n";
import { I18N_KEY_PATTERN } from "@/lib/constants";

/**
 * 字典项新增/编辑弹窗（react-hook-form + zod + HeroUI Form）。
 *
 * - value 在同一类型下唯一（后端 409 DICT_ITEM_VALUE_EXISTS 拦截）；
 * - i18nKey 可选（点分键格式，label 作中文兜底）；清空传 ""（后端 ?? 兜底）；
 * - sort 升序排列、enabled 控制业务侧可见性（下拉选项只取启用项）。
 */

export type DictItemFormMode = "create" | "edit";

export interface DictItemFormDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: DictItemFormMode;
  /** 所属字典类型 code（create 时写入目标类型） */
  typeCode: string;
  /** edit：被编辑的字典项；create：null */
  item: DictItem | null;
  /** 保存成功回调（页面统一做缓存失效与业务字典联动刷新） */
  onSaved: () => void;
}

const FORM_ID = "dict-item-form";

const VALUE_MAX_LENGTH = 50;
const LABEL_MAX_LENGTH = 20;
const I18N_KEY_MAX_LENGTH = 100;

const itemFormSchema = z.object({
  value: z.string().trim().min(1).max(VALUE_MAX_LENGTH),
  label: z.string().trim().min(1).max(LABEL_MAX_LENGTH),
  i18nKey: z
    .string()
    .trim()
    .max(I18N_KEY_MAX_LENGTH)
    .refine((value) => value === "" || I18N_KEY_PATTERN.test(value)),
  sort: sortFieldSchema,
  enabled: z.boolean(),
});

type ItemFormValues = z.infer<typeof itemFormSchema>;

export function DictItemFormDialog({
  isOpen,
  onOpenChange,
  mode,
  typeCode,
  item,
  onSaved,
}: DictItemFormDialogProps) {
  // Modal 结构渲染在有 mutation 的内层组件（ItemFormModal），
  // 保证 Modal.Footer 是 Modal.Dialog 的直接子元素（Body 滚动、Footer 固定）
  return isOpen ? (
    <ItemFormModal
      key={`${mode}:${item?.id ?? typeCode}`}
      isOpen
      item={item}
      mode={mode}
      typeCode={typeCode}
      onOpenChange={onOpenChange}
      onSaved={onSaved}
    />
  ) : null;
}

interface ItemFormProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: DictItemFormMode;
  typeCode: string;
  item: DictItem | null;
  onSaved: () => void;
}

function ItemFormModal({
  isOpen,
  onOpenChange,
  mode,
  typeCode,
  item,
  onSaved,
}: ItemFormProps) {
  const { t } = useTranslation();
  const isEdit = mode === "edit";

  const { control, handleSubmit, watch, setValue } = useForm<ItemFormValues>({
    resolver: zodResolver(itemFormSchema),
    defaultValues: {
      value: item?.value ?? "",
      label: item?.label ?? "",
      i18nKey: item?.i18nKey ?? "",
      sort: item?.sort ?? 0,
      enabled: item?.enabled ?? true,
    },
  });

  const mutation = useMutation({
    mutationFn: (values: ItemFormValues) => {
      const input: DictItemSaveInput = {
        value: values.value,
        label: values.label,
        i18nKey: values.i18nKey,
        sort: values.sort,
        enabled: values.enabled,
      };

      return isEdit
        ? updateDictItem(item!.id, input)
        : createDictItem(typeCode, input);
    },
    // 提示反馈统一由 onSubmit 的 toast.promise 呈现（loading → success/error）；
    // 成功副作用（缓存失效联动、关弹窗）保留在此
    onSuccess: () => {
      onSaved();
      onOpenChange(false);
    },
  });

  const onSubmit = handleSubmit((values) => {
    toast.promise(mutation.mutateAsync(values), {
      loading: t("features.dicts.form.saving"),
      success: t(
        isEdit
          ? "features.dicts.message.itemUpdated"
          : "features.dicts.message.itemCreated",
      ),
      error: (error) => getDictErrorMessage(error),
    });
  });

  return (
    <Modal.Backdrop
      isKeyboardDismissDisabled
      isDismissable={false}
      isOpen={isOpen}
      onOpenChange={onOpenChange}
    >
      <Modal.Container>
        <Modal.Dialog className="sm:max-w-md">
          <Modal.CloseTrigger />
          <Modal.Header>
            <Modal.Heading>
              {t(
                mode === "edit"
                  ? "features.dicts.form.title.editItem"
                  : "features.dicts.form.title.createItem",
              )}
            </Modal.Heading>
          </Modal.Header>
          <Modal.Body>
            <Form
              className="flex flex-col gap-4"
              id={FORM_ID}
              validationBehavior="aria"
              onSubmit={(event) => void onSubmit(event)}
            >
              <Controller
                control={control}
                name="value"
                render={({ field, fieldState }) => (
                  <TextField
                    isRequired
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.dicts.form.value")}</Label>
                    {/* Suffix 实时字数（上限与后端 @Length(1,50) 对齐） */}
                    <InputGroup variant="secondary">
                      <InputGroup.Input
                        maxLength={VALUE_MAX_LENGTH}
                        placeholder="1"
                      />
                      <InputGroup.Suffix className="text-xs text-muted">
                        {field.value?.length ?? 0}/{VALUE_MAX_LENGTH}
                      </InputGroup.Suffix>
                    </InputGroup>
                    {fieldState.error && (
                      <FieldError>
                        {t("features.dicts.form.valueInvalid")}
                      </FieldError>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="label"
                render={({ field, fieldState }) => (
                  <TextField
                    isRequired
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.dicts.form.label")}</Label>
                    <InputGroup variant="secondary">
                      <InputGroup.Input
                        maxLength={LABEL_MAX_LENGTH}
                        placeholder={t("features.dicts.form.labelPlaceholder")}
                      />
                      <InputGroup.Suffix className="text-xs text-muted">
                        {field.value?.length ?? 0}/{LABEL_MAX_LENGTH}
                      </InputGroup.Suffix>
                    </InputGroup>
                    {fieldState.error && (
                      <FieldError>
                        {t("features.dicts.form.labelInvalid")}
                      </FieldError>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="i18nKey"
                render={({ field, fieldState }) => (
                  <TextField
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.dicts.form.i18nKey")}</Label>
                    <InputGroup variant="secondary">
                      <InputGroup.Input
                        maxLength={I18N_KEY_MAX_LENGTH}
                        placeholder={`dict.${typeCode}.xxx`}
                      />
                      <InputGroup.Suffix className="text-xs text-muted">
                        {field.value?.length ?? 0}/{I18N_KEY_MAX_LENGTH}
                      </InputGroup.Suffix>
                    </InputGroup>
                    {fieldState.error ? (
                      <FieldError>
                        {t("features.dicts.form.i18nKeyFormat")}
                      </FieldError>
                    ) : (
                      <Description>
                        {t("features.dicts.form.i18nKeyHint")}
                      </Description>
                    )}
                  </TextField>
                )}
              />

              <SortField
                value={watch("sort")}
                onChange={(value) =>
                  setValue("sort", value, { shouldValidate: true })
                }
              />

              <Controller
                control={control}
                name="enabled"
                render={({ field }) => (
                  <div className="flex items-center justify-between gap-3 rounded-3xl border border-border px-3 py-2">
                    <Label>{t("features.dicts.form.enabled")}</Label>
                    <Switch
                      aria-label={t("features.dicts.form.enabled")}
                      isSelected={field.value}
                      onChange={field.onChange}
                    >
                      {({ isSelected }) => (
                        <Switch.Content>
                          <Switch.Control>
                            <Switch.Thumb>
                              <Switch.Icon>
                                {isSelected ? (
                                  <Check className="size-3 text-inherit opacity-100" />
                                ) : (
                                  <X className="size-3 text-inherit opacity-70" />
                                )}
                              </Switch.Icon>
                            </Switch.Thumb>
                          </Switch.Control>
                        </Switch.Content>
                      )}
                    </Switch>
                  </div>
                )}
              />
            </Form>
          </Modal.Body>

          <Modal.Footer className="w-full">
            <Button slot="close" variant="secondary">
              {t("common.cancel")}
            </Button>
            <Button form={FORM_ID} isPending={mutation.isPending} type="submit">
              {({ isPending }) =>
                isPending ? (
                  <>
                    <Spinner color="current" size="sm" />
                    {t("features.dicts.form.saving")}
                  </>
                ) : (
                  t("common.confirm")
                )
              }
            </Button>
          </Modal.Footer>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  );
}

// apps/vue/src/features/dicts/DictItemFormDialog.vue
<script setup lang="ts">
import type { DictItem } from "@/lib/api-types";
import type { FormSubmitEvent } from "@nuxt/ui";

import * as z from "zod";
import { computed, h, reactive, ref, useTemplateRef, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import Spinner from "@/components/ui/spinner/index.vue";

import {
  createDictItem,
  getDictErrorMessage,
  updateDictItem,
} from "./dict-api";
import { I18N_KEY_PATTERN } from "@/lib/constants";

/**
 * 字典项新增/编辑弹窗：UForm + zod schema 校验（官方范式，@submit 仅在
 * 校验通过后触发，event.data 为校验转换后的值）。
 * - value/label 必填（同类型下 value/label 唯一由后端 409 拦截）；
 * - i18nKey 可选：点分格式（menu.xxx.yyy），传 "" 表示清空；
 * - sort 0-999 整数；enabled 开关。
 */
const props = defineProps<{
  open: boolean;
  mode: "create" | "edit";
  item: DictItem | null;
  /** 所属字典类型 code（create 挂载目标） */
  typeCode: string;
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
  /** 保存成功（页面统一刷新右栏列表并回填业务缓存） */
  saved: [];
}>();

const FORM_ID = "dict-item-form";
const VALUE_MAX_LENGTH = 50;
const LABEL_MAX_LENGTH = 20;
const I18N_KEY_MAX_LENGTH = 100;

const { t } = useI18n();
const toast = useToast();

// 校验消息用函数延迟求值：语言切换后错误文案跟随当前 locale
const schema = z.object({
  value: z
    .string()
    .trim()
    .min(1, { error: () => t("features.dicts.form.valueInvalid") })
    .max(VALUE_MAX_LENGTH, {
      error: () => t("features.dicts.form.valueInvalid"),
    }),
  label: z
    .string()
    .trim()
    .min(1, { error: () => t("features.dicts.form.labelInvalid") })
    .max(LABEL_MAX_LENGTH, {
      error: () => t("features.dicts.form.labelInvalid"),
    }),
  i18nKey: z
    .string()
    .trim()
    .max(I18N_KEY_MAX_LENGTH)
    .refine((value) => value === "" || I18N_KEY_PATTERN.test(value), {
      error: () => t("features.dicts.form.i18nKeyFormat"),
    }),
  sort: z.number(),
  enabled: z.boolean(),
});

type Schema = z.output<typeof schema>;

const state = reactive<Schema>({
  value: "",
  label: "",
  i18nKey: "",
  sort: 0,
  enabled: true,
});
const formRef = useTemplateRef("formRef");
const submitting = ref(false);

watch(
  () => props.open,
  (open) => {
    if (!open) return;

    const item = props.mode === "edit" ? props.item : null;

    state.value = item?.value ?? "";
    state.label = item?.label ?? "";
    state.i18nKey = item?.i18nKey ?? "";
    state.sort = item?.sort ?? 0;
    state.enabled = item?.enabled ?? true;
    formRef.value?.clear();
  },
  { immediate: true },
);

const isEdit = computed(() => props.mode === "edit");

function close() {
  emit("update:open", false);
}

async function onSubmit(event: FormSubmitEvent<Schema>) {
  submitting.value = true;

  // toast.promise 形态（对齐 React 端）：保存全程 loading toast，
  // 完成后原位替换为成功/失败；duration 0 保证请求返回前不消失
  //（update 会重置计时回落全局时长）；icon 用 Spinner 组件（toast
  // 内容支持 VNode），自带旋转动画
  const savingToast = toast.add({
    title: t("features.dicts.form.saving"),
    icon: h(Spinner, { size: "sm", class: "mt-0.5" }),
    color: "info",
    duration: 0,
  });

  const input = {
    value: event.data.value,
    label: event.data.label,
    i18nKey: event.data.i18nKey,
    sort: event.data.sort,
    enabled: event.data.enabled,
  };

  try {
    if (isEdit.value && props.item) {
      await updateDictItem(props.item.id, input);
    } else {
      await createDictItem(props.typeCode, input);
    }

    toast.update(savingToast.id, {
      title: t(
        isEdit.value
          ? "features.dicts.message.itemUpdated"
          : "features.dicts.message.itemCreated",
      ),
      icon: "i-lucide-check",
      color: "success",
    });
    emit("saved");
    close();
  } catch (error) {
    toast.update(savingToast.id, {
      title: getDictErrorMessage(error),
      icon: "i-lucide-x",
      color: "error",
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <UModal
    :open="open"
    :dismissible="false"
    :title="
      t(
        isEdit
          ? 'features.dicts.form.title.editItem'
          : 'features.dicts.form.title.createItem',
      )
    "
    :ui="{ content: 'sm:max-w-md', footer: 'justify-end' }"
    @update:open="(value: boolean) => !value && close()"
  >
    <template #body>
      <UForm
        :id="FORM_ID"
        ref="formRef"
        :schema="schema"
        :state="state"
        class="flex flex-col gap-4"
        @submit="onSubmit"
      >
        <UFormField
          :label="t('features.dicts.form.value')"
          name="value"
          required
        >
          <UInput
            v-model="state.value"
            :maxlength="VALUE_MAX_LENGTH"
            placeholder="1"
            :ui="{ base: 'pe-13' }"
            class="w-full"
          >
            <template #trailing>
              <span class="text-dimmed text-xs tabular-nums">
                {{ state.value.length }}/{{ VALUE_MAX_LENGTH }}
              </span>
            </template>
          </UInput>
        </UFormField>

        <UFormField
          :label="t('features.dicts.form.label')"
          name="label"
          required
        >
          <UInput
            v-model="state.label"
            :maxlength="LABEL_MAX_LENGTH"
            :placeholder="t('features.dicts.form.labelPlaceholder')"
            :ui="{ base: 'pe-13' }"
            class="w-full"
          >
            <template #trailing>
              <span class="text-dimmed text-xs tabular-nums">
                {{ state.label.length }}/{{ LABEL_MAX_LENGTH }}
              </span>
            </template>
          </UInput>
        </UFormField>

        <UFormField
          :label="t('features.dicts.form.i18nKey')"
          name="i18nKey"
          :help="t('features.dicts.form.i18nKeyHint')"
          :ui="{ help: 'text-dimmed text-xs' }"
        >
          <UInput
            v-model="state.i18nKey"
            class="w-full"
            :maxlength="I18N_KEY_MAX_LENGTH"
            :placeholder="`dict.${typeCode}.xxx`"
            :ui="{ base: 'pe-16' }"
          >
            <template #trailing>
              <span class="text-dimmed text-xs tabular-nums">
                {{ state.i18nKey.length }}/{{ I18N_KEY_MAX_LENGTH }}
              </span>
            </template>
          </UInput>
        </UFormField>

        <UFormField :label="t('common.column.sort')">
          <UInputNumber v-model="state.sort" :min="0" class="w-full" />
        </UFormField>

        <div
          class="border-default flex items-center justify-between gap-3 rounded-xl border px-3 py-2"
        >
          <span class="text-sm">
            {{ t("features.dicts.form.enabled") }}
          </span>
          <USwitch
            v-model="state.enabled"
            :aria-label="t('features.dicts.form.enabled')"
            unchecked-icon="i-lucide-x"
            checked-icon="i-lucide-check"
          />
        </div>
      </UForm>
    </template>

    <template #footer="{ close: onClose }">
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="onClose"
      />
      <UButton
        :form="FORM_ID"
        :label="
          submitting ? t('features.dicts.form.saving') : t('common.confirm')
        "
        :loading="submitting"
        type="submit"
      />
    </template>
  </UModal>
</template>
