// react/src/layouts/components/notice-bell.tsx
import type { AppNotification } from "@/lib/api-types";
import type { LucideIcon } from "lucide-react";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Badge,
  Button,
  cn,
  Drawer,
  ListBox,
  Skeleton,
  Tabs,
  Typography,
  useOverlayState,
  Spinner,
} from "@heroui/react";
import { AlarmClock, Bell, BellRing, Settings } from "lucide-react";
import { useNavigate } from "@tanstack/react-router";
import { useCallback, useMemo, useState } from "react";

import { EmptyContent } from "@/components/common/empty-content/empty-content";
import {
  fetchNotifications,
  fetchUnreadCount,
  readAllNotifications,
  readNotification,
} from "@/features/notice/notification-api";
import { useTranslation } from "@/i18n";
import { formatRelativeTime } from "@/lib/format-date";

type NoticeBellTab = "unread" | "all";

/** 通知类型 → 图标（装饰性，aria-hidden） */
const NOTIFICATION_ICONS: Record<AppNotification["type"], LucideIcon> = {
  notice_publish: BellRing,
  notice_remind: AlarmClock,
  system: Settings,
};

/**
 * 顶栏通知铃铛（契约 v1.7.0，站内信）：
 * - 未读数经 useQuery refetchInterval 60s 轮询（红点 Badge）；
 * - 抽屉面板展示通知列表（最新在前），点击条目标记已读并跳转 link；
 * - 「全部已读」一键清零。
 */
export function NoticeBell() {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const bellState = useOverlayState();
  const [activeTab, setActiveTab] = useState<NoticeBellTab>("unread");
  const [isOpeningMyNotices, setIsOpeningMyNotices] = useState(false);

  const unreadQuery = useQuery({
    queryKey: ["notifications", "unread-count"],
    queryFn: fetchUnreadCount,
    refetchInterval: 60_000,
    staleTime: 30_000,
  });
  const unreadCount = unreadQuery.data?.count ?? 0;

  const listQuery = useQuery({
    queryKey: ["notifications", "list", activeTab],
    queryFn: () =>
      fetchNotifications({
        page: 1,
        pageSize: 20,
        unreadOnly: activeTab === "unread",
      }),
    enabled: bellState.isOpen,
    staleTime: 0,
  });
  const notifications = listQuery.data?.data ?? [];
  const emptyTitle = useMemo(
    () =>
      activeTab === "unread"
        ? t("layout.header.noUnreadNotifications")
        : t("layout.header.noNotifications"),
    [activeTab, t],
  );

  const invalidateNotifications = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: ["notifications"] });
  }, [queryClient]);

  const readAllMutation = useMutation({
    mutationFn: readAllNotifications,
    onSuccess: () => invalidateNotifications(),
  });

  const readOneMutation = useMutation({
    mutationFn: readNotification,
    onSuccess: () => invalidateNotifications(),
  });

  const handleItemClick = useCallback(
    (id: string, link: string | null) => {
      if (!link) {
        readOneMutation.mutate(id);

        return;
      }
      // 标记已读后跳转（跳转即可读，失败静默）
      readOneMutation.mutate(id);
      bellState.close();
      void navigate({ to: link });
    },
    [readOneMutation, bellState, navigate],
  );

  const openBell = useCallback(() => {
    setActiveTab("unread");
    bellState.open();
  }, [bellState]);

  const openMyNotices = useCallback(() => {
    const run = async () => {
      setIsOpeningMyNotices(true);
      bellState.close();
      try {
        await navigate({ to: "/my-notices" });
      } finally {
        setIsOpeningMyNotices(false);
      }
    };

    void run();
  }, [bellState, navigate]);

  return (
    <>
      {/* 铃铛按钮 + 未读红点（0 条不显示） */}
      <Badge.Anchor>
        <Button
          isIconOnly
          aria-label={
            unreadCount > 0
              ? `${t("layout.header.notifications")} (${unreadCount})`
              : t("layout.header.notifications")
          }
          size="sm"
          variant="ghost"
          onPress={openBell}
        >
          <Bell className="size-4" />
        </Button>
        {unreadCount > 0 && (
          <Badge color="danger" size="sm">
            {unreadCount > 99 ? "99+" : unreadCount}
          </Badge>
        )}
      </Badge.Anchor>

      <Drawer state={bellState}>
        <Drawer.Backdrop>
          <Drawer.Content placement="right">
            <Drawer.Dialog className="w-100 max-w-full">
              <Drawer.CloseTrigger />
              {/* Tabs 仅作「未读 / 全部」筛选器放 Header 固定（列表为单一视图，
                  切换只重发查询），无需 Tabs.Panel */}
              <Drawer.Header className="flex flex-col gap-3 pb-3">
                <Drawer.Heading className="min-w-0 truncate font-bold">
                  {t("layout.header.notifications")}
                </Drawer.Heading>
                <Tabs
                  aria-label={t("layout.header.notifications")}
                  selectedKey={activeTab}
                  onSelectionChange={(key) =>
                    setActiveTab(String(key) as NoticeBellTab)
                  }
                >
                  <Tabs.ListContainer>
                    <Tabs.List aria-label={t("layout.header.notifications")}>
                      <Tabs.Tab id="unread">
                        {t("layout.header.unreadTab")}
                        <Tabs.Indicator />
                      </Tabs.Tab>
                      <Tabs.Tab id="all">
                        <Tabs.Separator />
                        {t("layout.header.allTab")}
                        <Tabs.Indicator />
                      </Tabs.Tab>
                    </Tabs.List>
                  </Tabs.ListContainer>
                </Tabs>
              </Drawer.Header>
              <Drawer.Body>
                {/* isPending（而非 isLoading）：抽屉未开时 query 处于 disabled 的
                    pending 态（isLoading 为 false），用 isLoading 会在打开抽屉的
                    首帧闪现「暂无通知」空态，isPending 才稳定呈现骨架屏 */}
                {listQuery.isPending ? (
                  /* 逼真骨架屏：与通知条目同形（图标 + 标题/时间行 + 通栏摘要两行） */
                  <div aria-hidden className="divide-y divide-separator">
                    {Array.from({ length: 5 }, (_, index) => (
                      <div key={index} className="px-4 py-3">
                        <div className="flex w-full items-center gap-3">
                          <Skeleton className="size-9 shrink-0 rounded-full" />
                          <div className="flex min-w-0 flex-1 items-center justify-between gap-2">
                            <Skeleton
                              className="h-3.5 rounded-md"
                              style={{ width: `${60 - (index % 3) * 8}%` }}
                            />
                            <Skeleton className="h-2.5 w-12 shrink-0 rounded-md" />
                          </div>
                        </div>
                        <div className="mt-2 flex flex-col gap-1.5">
                          <Skeleton
                            className="h-2.5 rounded-md"
                            style={{ width: "92%" }}
                          />
                          <Skeleton
                            className="h-2.5 rounded-md"
                            style={{ width: `${64 - (index % 3) * 10}%` }}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                ) : notifications.length === 0 ? (
                  <div className="px-4 py-10">
                    <EmptyContent title={emptyTitle} />
                  </div>
                ) : (
                  <ListBox
                    aria-label={t("layout.header.notifications")}
                    className="w-full gap-0 divide-y divide-separator p-0"
                    selectionMode="none"
                    onAction={(key) => {
                      const notification = notifications.find(
                        (n) => n.id === key,
                      );

                      if (notification) {
                        handleItemClick(notification.id, notification.link);
                      }
                    }}
                  >
                    {notifications.map((notification) => {
                      const isUnread = notification.readAt === null;
                      const Icon =
                        NOTIFICATION_ICONS[notification.type] ?? Bell;

                      return (
                        <ListBox.Item
                          key={notification.id}
                          className={cn(
                            "w-full rounded-none px-4 py-3 text-start transition-all duration-200 mt-0",
                            "focus-visible:bg-default/60 focus-visible:outline-hidden focus-visible:ring-0",
                            "hover:bg-default/60",
                          )}
                          id={notification.id}
                          textValue={notification.title}
                        >
                          <div className="flex w-full min-w-0 flex-col gap-1.5">
                            <div className="flex w-full items-center gap-3">
                              <Badge.Anchor>
                                <div
                                  aria-hidden
                                  className="flex size-9 shrink-0 items-center justify-center rounded-full bg-accent/10 text-accent"
                                >
                                  <Icon className="size-4" />
                                </div>
                                {/* 未读状态不能只靠视觉红点传达，SR 补播报 */}
                                {isUnread && (
                                  <Badge color="danger" size="sm">
                                    <span className="sr-only">
                                      {t("features.myNotices.filter.unread")}
                                    </span>
                                  </Badge>
                                )}
                              </Badge.Anchor>

                              <div className="flex min-w-0 flex-1 items-center justify-between gap-2">
                                <Typography
                                  className={cn(
                                    "min-w-0 truncate",
                                    isUnread && "font-medium",
                                  )}
                                  type="body-sm"
                                >
                                  {notification.title}
                                </Typography>
                                <Typography
                                  className="shrink-0"
                                  color="muted"
                                  type="body-xs"
                                >
                                  {formatRelativeTime(
                                    notification.createdAt,
                                    i18n.language,
                                  )}
                                </Typography>
                              </div>
                            </div>
                            {notification.content ? (
                              <Typography
                                className="line-clamp-2"
                                color="muted"
                                type="body-xs"
                              >
                                {notification.content}
                              </Typography>
                            ) : null}
                          </div>
                        </ListBox.Item>
                      );
                    })}
                  </ListBox>
                )}
                {listQuery.data &&
                  listQuery.data.pagination.total > notifications.length && (
                    <Typography
                      className="pb-1 pt-2 text-center"
                      color="muted"
                      type="body-xs"
                    >
                      {t("layout.header.moreNotifications")}
                    </Typography>
                  )}
              </Drawer.Body>
              <Drawer.Footer className="grid w-full grid-cols-2 gap-2">
                <Button
                  fullWidth
                  isDisabled={unreadCount === 0 || isOpeningMyNotices}
                  isPending={readAllMutation.isPending}
                  variant="outline"
                  onPress={() => readAllMutation.mutate()}
                >
                  {({ isPending }) => (
                    <>
                      {isPending ? <Spinner color="current" size="sm" /> : null}
                      {t("layout.header.readAll")}
                    </>
                  )}
                </Button>
                <Button
                  fullWidth
                  isDisabled={readAllMutation.isPending}
                  isPending={isOpeningMyNotices}
                  onPress={openMyNotices}
                >
                  {t("layout.header.viewMyNotices")}
                </Button>
              </Drawer.Footer>
            </Drawer.Dialog>
          </Drawer.Content>
        </Drawer.Backdrop>
      </Drawer>
    </>
  );
}

// vue/src/components/layout/NoticeBell.vue
<script setup lang="ts">
import type { AppNotification } from "@/lib/api-types";

import { computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useRouter } from "vue-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { useToast } from "@nuxt/ui/composables";

import {
  fetchNotifications,
  fetchUnreadCount,
  readAllNotifications,
  readNotification,
} from "@/features/notice/notification-api";

import { formatRelativeTime } from "@/lib/format-date";

/**
 * 顶栏通知铃铛（契约 v1.7.0 站内信，对应 React 端 notice-bell.tsx）：
 * - 未读数经 useQuery refetchInterval 60s 轮询（红点角标，0 条不显示）；
 * - 抽屉面板展示通知列表（最新在前），固定「未读 / 全部」筛选 Tabs，
 *   点击条目标记已读并跳转 link（无 link 仅记已读）；
 * - 「全部已读」一键清零；「我的公告」入口。
 */
const { t, locale } = useI18n();
const router = useRouter();
const queryClient = useQueryClient();
const toast = useToast();

const isOpen = ref(false);
const activeTab = ref<"unread" | "all">("unread");
const openingMyNotices = ref(false);

const unreadQuery = useQuery({
  queryKey: ["notifications", "unread-count"],
  queryFn: fetchUnreadCount,
  refetchInterval: 60_000,
  staleTime: 30_000,
});
const unreadCount = computed(() => unreadQuery.data.value?.count ?? 0);

const listQuery = useQuery({
  queryKey: computed(() => ["notifications", "list", activeTab.value]),
  queryFn: () =>
    fetchNotifications({
      page: 1,
      pageSize: 20,
      unreadOnly: activeTab.value === "unread",
    }),
  enabled: computed(() => isOpen.value),
  staleTime: 0,
});
const notifications = computed<AppNotification[]>(
  () => listQuery.data.value?.data ?? [],
);
const listTotal = computed(() => listQuery.data.value?.pagination.total ?? 0);
// isPending（而非 isLoading）：抽屉未开时 query 处于 disabled 的 pending 态，
// 用 isLoading 会在打开抽屉首帧闪现空态，isPending 才稳定呈现骨架屏
const listPending = computed(() => listQuery.status.value === "pending");

const emptyTitle = computed(() =>
  activeTab.value === "unread"
    ? t("layout.header.noUnreadNotifications")
    : t("layout.header.noNotifications"),
);

function invalidateNotifications() {
  void queryClient.invalidateQueries({ queryKey: ["notifications"] });
}

const readAllMutation = useMutation({
  mutationFn: readAllNotifications,
  onSuccess: () => invalidateNotifications(),
  onError: () => {
    toast.add({ color: "error", title: t("common.loadError") });
  },
});

const readOneMutation = useMutation({
  mutationFn: readNotification,
  onSuccess: () => invalidateNotifications(),
});

function handleItemClick(notification: AppNotification) {
  // 标记已读后跳转（跳转即可读，失败静默）
  readOneMutation.mutate(notification.id);

  if (notification.link) {
    isOpen.value = false;
    void router.push(notification.link);
  }
}

function openBell() {
  activeTab.value = "unread";
  isOpen.value = true;
}

async function openMyNotices() {
  openingMyNotices.value = true;
  isOpen.value = false;

  try {
    await router.push("/my-notices");
  } finally {
    openingMyNotices.value = false;
  }
}

const tabItems = computed(() => [
  { label: t("layout.header.unreadTab"), value: "unread" },
  { label: t("layout.header.allTab"), value: "all" },
]);

/** 通知类型 → 图标（装饰性，aria-hidden） */
const NOTIFICATION_ICONS: Record<AppNotification["type"], string> = {
  notice_publish: "i-lucide-bell-ring",
  notice_remind: "i-lucide-alarm-clock",
  system: "i-lucide-settings",
};

const bellAriaLabel = computed(() =>
  unreadCount.value > 0
    ? `${t("layout.header.notifications")} (${unreadCount.value})`
    : t("layout.header.notifications"),
);
</script>

<script lang="ts">
export default { name: "NoticeBell" };
</script>

<template>
  <div>
    <!-- 铃铛按钮 + 未读红点角标（0 条不显示） -->
    <UChip
      :color="unreadCount > 0 ? 'error' : 'neutral'"
      :show="unreadCount > 0"
      :label="unreadCount > 99 ? '99+' : String(unreadCount)"
      size="sm"
    >
      <UButton
        :aria-label="bellAriaLabel"
        color="neutral"
        icon="i-lucide-bell"
        size="sm"
        variant="ghost"
        @click="openBell"
      />
    </UChip>

    <USlideover
      :open="isOpen"
      :ui="{ content: 'w-100 max-w-[85vw]' }"
      :title="t('layout.header.notifications')"
      @update:open="(value: boolean) => (isOpen = value)"
    >
      <template #body>
        <!-- Tabs 仅作「未读 / 全部」筛选器（列表为单一视图，切换只重发查询） -->
        <UTabs
          v-model:model-value="activeTab"
          :content="false"
          :items="tabItems"
          size="sm"
        />

        <div class="mt-3 flex min-h-40 flex-col">
          <!-- 逼真骨架屏：与通知条目同形（图标 + 标题/时间行 + 通栏摘要两行） -->
          <div
            v-if="listPending"
            aria-hidden
            class="divide-default flex flex-col divide-y"
          >
            <div v-for="index in 5" :key="index" class="px-1 py-3">
              <div class="flex w-full items-center gap-3">
                <USkeleton class="size-9 shrink-0 rounded-full" />
                <div
                  class="flex min-w-0 flex-1 items-center justify-between gap-2"
                >
                  <USkeleton
                    class="h-3.5 rounded-md"
                    :style="{ width: `${60 - (index % 3) * 8}%` }"
                  />
                  <USkeleton class="h-2.5 w-12 shrink-0 rounded-md" />
                </div>
              </div>
              <div class="mt-2 flex flex-col gap-1.5">
                <USkeleton class="h-2.5 w-[92%] rounded-md" />
                <USkeleton
                  class="h-2.5 rounded-md"
                  :style="{ width: `${64 - (index % 3) * 10}%` }"
                />
              </div>
            </div>
          </div>

          <p
            v-else-if="notifications.length === 0"
            class="text-muted py-10 text-center text-sm"
          >
            {{ emptyTitle }}
          </p>

          <ul v-else class="divide-default divide-y">
            <li v-for="notification in notifications" :key="notification.id">
              <button
                class="w-full rounded-lg px-1 py-3 text-start transition-colors hover:bg-elevated/60"
                type="button"
                @click="handleItemClick(notification)"
              >
                <div class="flex w-full min-w-0 flex-col gap-1.5">
                  <div class="flex w-full items-center gap-3">
                    <span
                      class="bg-primary/10 text-primary flex size-9 shrink-0 items-center justify-center rounded-full"
                    >
                      <UIcon
                        :name="
                          NOTIFICATION_ICONS[notification.type] ??
                          'i-lucide-bell'
                        "
                        aria-hidden
                        class="size-4"
                      />
                    </span>
                    <!-- 未读状态不能只靠视觉红点传达，SR 补播报 -->
                    <span
                      class="min-w-0 flex-1 truncate text-sm"
                      :class="{ 'font-medium': notification.readAt === null }"
                    >
                      {{ notification.title }}
                    </span>
                    <span v-if="notification.readAt === null" class="sr-only">
                      {{ t("features.myNotices.filter.unread") }}
                    </span>
                    <span
                      v-if="notification.readAt === null"
                      aria-hidden
                      class="bg-error size-2 shrink-0 rounded-full"
                    />
                    <span class="text-muted shrink-0 text-xs">
                      {{ formatRelativeTime(notification.createdAt, locale) }}
                    </span>
                  </div>
                  <span
                    v-if="notification.content"
                    class="text-muted line-clamp-2 text-xs"
                  >
                    {{ notification.content }}
                  </span>
                </div>
              </button>
            </li>
          </ul>

          <p
            v-if="listTotal > notifications.length"
            class="text-muted pb-1 pt-2 text-center text-xs"
          >
            {{ t("layout.header.moreNotifications") }}
          </p>
        </div>
      </template>

      <template #footer>
        <div class="grid w-full grid-cols-2 gap-2">
          <UButton
            :disabled="unreadCount === 0 || openingMyNotices"
            :label="t('layout.header.readAll')"
            :loading="readAllMutation.isPending.value"
            block
            variant="outline"
            @click="readAllMutation.mutate()"
          />
          <UButton
            :disabled="readAllMutation.isPending.value"
            :label="t('layout.header.viewMyNotices')"
            :loading="openingMyNotices"
            block
            @click="openMyNotices"
          />
        </div>
      </template>
    </USlideover>
  </div>
</template>
