// next/src/features/account/cards/profile-form-card.tsx
"use client";

import type { AccountProfile } from "@/lib/api-types";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import {
  Button,
  Card,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  Spinner,
  TextField,
  toast,
} from "@heroui/react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import {
  getAccountErrorMessage,
  updateAccountProfile,
  type OnAccountProfileSaved,
} from "../account-api";
import { TagInput } from "../tag-input";

import { useTranslation } from "@/i18n";

export interface ProfileFormCardProps {
  profile: AccountProfile;
  onSaved: OnAccountProfileSaved;
}

const FORM_ID = "account-profile-form";

interface ProfileFormValues {
  displayName: string;
  phone: string;
  tags: string[];
}

const profileFormSchema = z.object({
  displayName: z.string().trim().min(1).max(50),
  phone: z
    .string()
    .trim()
    .regex(/^\+?[0-9][0-9\- ]{3,19}$/)
    .or(z.literal("")),
  tags: z.array(z.string()),
});

/** 基本信息卡：username 只读，displayName / phone / tags 可编辑 */
export function ProfileFormCard({ profile, onSaved }: ProfileFormCardProps) {
  const { t } = useTranslation();

  const { control, handleSubmit } = useForm<ProfileFormValues>({
    resolver: zodResolver(profileFormSchema),
    defaultValues: {
      displayName: profile.displayName,
      phone: profile.phone ?? "",
      tags: profile.tags,
    },
  });

  const mutation = useMutation({
    mutationFn: (values: ProfileFormValues) =>
      updateAccountProfile({
        displayName: values.displayName.trim(),
        phone: values.phone.trim() ? values.phone.trim() : null,
        tags: values.tags,
      }),
    onSuccess: (updated) => {
      toast.success(t("features.account.profile.saveSuccess"));
      onSaved(updated);
    },
    onError: (mutationError) => {
      toast.danger(getAccountErrorMessage(mutationError));
    },
  });

  const onSubmit = handleSubmit((values) => {
    mutation.mutate(values);
  });

  return (
    <Card>
      <Card.Header>
        <Card.Title className="font-bold">
          {t("features.account.profile.title")}
        </Card.Title>
        <Card.Description className="text-xs">
          {t("features.account.profile.description")}
        </Card.Description>
      </Card.Header>
      <Card.Content>
        <Form
          className="flex flex-col gap-4"
          id={FORM_ID}
          validationBehavior="aria"
          onSubmit={(event) => void onSubmit(event)}
        >
          <TextField
            isDisabled
            className="flex flex-col gap-1"
            value={profile.username}
          >
            <Label>{t("features.account.profile.username")}</Label>
            <Input variant="secondary" />
            <Description>
              {t("features.account.profile.usernameHint")}
            </Description>
          </TextField>

          <Controller
            control={control}
            name="displayName"
            render={({ field, fieldState }) => (
              <TextField
                className="flex flex-col gap-1"
                isInvalid={Boolean(fieldState.error)}
                value={field.value ?? ""}
                onBlur={field.onBlur}
                onChange={field.onChange}
              >
                <Label>{t("features.account.profile.displayName")}</Label>
                <Input
                  maxLength={50}
                  placeholder={t(
                    "features.account.profile.displayNamePlaceholder",
                  )}
                  variant="secondary"
                />
                {fieldState.error ? (
                  <FieldError>
                    {t("features.account.profile.displayNameInvalid")}
                  </FieldError>
                ) : null}
              </TextField>
            )}
          />

          <Controller
            control={control}
            name="phone"
            render={({ field, fieldState }) => (
              <TextField
                className="flex flex-col gap-1"
                isInvalid={Boolean(fieldState.error)}
                value={field.value ?? ""}
                onBlur={field.onBlur}
                onChange={field.onChange}
              >
                <Label>{t("features.account.profile.phone")}</Label>
                <Input
                  inputMode="tel"
                  maxLength={20}
                  placeholder={t("features.account.profile.phonePlaceholder")}
                  type="tel"
                  variant="secondary"
                />
                {fieldState.error ? (
                  <FieldError>
                    {t("features.account.profile.phoneInvalid")}
                  </FieldError>
                ) : null}
              </TextField>
            )}
          />

          <Controller
            control={control}
            name="tags"
            render={({ field }) => (
              <TagInput
                isDisabled={mutation.isPending}
                label={t("features.account.tags.label")}
                placeholder={t("features.account.tags.placeholder")}
                value={field.value ?? []}
                onChange={field.onChange}
              />
            )}
          />
        </Form>
      </Card.Content>
      <Card.Footer className="justify-end border-t border-separator pt-4">
        <Button
          form={FORM_ID}
          isPending={mutation.isPending}
          size="sm"
          type="submit"
        >
          {({ isPending }) =>
            isPending ? (
              <>
                <Spinner color="current" size="sm" />
                {t("features.account.profile.saving")}
              </>
            ) : (
              t("features.account.profile.save")
            )
          }
        </Button>
      </Card.Footer>
    </Card>
  );
}

// vue/src/features/account/cards/ProfileFormCard.vue
<script setup lang="ts">
import type { AccountProfile } from "@/lib/api-types";
import type { FormSubmitEvent } from "@nuxt/ui";

import * as z from "zod";
import { reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import { getAccountErrorMessage, updateAccountProfile } from "../account-api";
import TagInput from "../TagInput.vue";

/** 基本信息卡（对齐 React 端 profile-form-card）：username 只读，displayName / phone / tags 可编辑 */
const props = defineProps<{ profile: AccountProfile }>();

const emit = defineEmits<{ saved: [updated: AccountProfile] }>();

const FORM_ID = "account-profile-form";

const { t } = useI18n();
const toast = useToast();

const PHONE_PATTERN = /^\+?[0-9][0-9\- ]{3,19}$/;

// 错误文案在校验时经 t() 取词（随语言切换）；规则与 React 端 zod schema 一致
const schema = z
  .object({
    displayName: z.string(),
    phone: z.string(),
    tags: z.array(z.string()),
  })
  .superRefine((data, ctx) => {
    const displayName = data.displayName.trim();

    if (displayName.length < 1 || displayName.length > 50) {
      ctx.addIssue({
        code: "custom",
        path: ["displayName"],
        message: t("features.account.profile.displayNameInvalid"),
      });
    }

    const phone = data.phone.trim();

    if (phone !== "" && !PHONE_PATTERN.test(phone)) {
      ctx.addIssue({
        code: "custom",
        path: ["phone"],
        message: t("features.account.profile.phoneInvalid"),
      });
    }
  });

type Schema = z.output<typeof schema>;

// 卡片由页面按 profile.updatedAt 作 key 重建，state 只需在 setup 初始化一次
const state = reactive<Schema>({
  displayName: props.profile.displayName,
  phone: props.profile.phone ?? "",
  tags: [...props.profile.tags],
});
const submitting = ref(false);

async function onSubmit(event: FormSubmitEvent<Schema>) {
  submitting.value = true;

  try {
    const updated = await updateAccountProfile({
      displayName: event.data.displayName.trim(),
      phone: event.data.phone.trim() ? event.data.phone.trim() : null,
      tags: event.data.tags,
    });

    toast.add({
      color: "success",
      title: t("features.account.profile.saveSuccess"),
    });
    emit("saved", updated);
  } catch (error) {
    toast.add({ color: "error", title: getAccountErrorMessage(error) });
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <UCard>
    <template #header>
      <h3 class="font-bold">{{ t("features.account.profile.title") }}</h3>
      <p class="text-muted text-xs">
        {{ t("features.account.profile.description") }}
      </p>
    </template>

    <UForm
      :id="FORM_ID"
      :schema="schema"
      :state="state"
      class="flex flex-col gap-4"
      @submit="onSubmit"
    >
      <UFormField
        :help="t('features.account.profile.usernameHint')"
        :label="t('features.account.profile.username')"
      >
        <UInput :model-value="profile.username" class="w-full" disabled />
      </UFormField>

      <UFormField
        :label="t('features.account.profile.displayName')"
        name="displayName"
      >
        <UInput
          v-model="state.displayName"
          :maxlength="50"
          :placeholder="t('features.account.profile.displayNamePlaceholder')"
          class="w-full"
        />
      </UFormField>

      <UFormField :label="t('features.account.profile.phone')" name="phone">
        <UInput
          v-model="state.phone"
          :maxlength="20"
          :placeholder="t('features.account.profile.phonePlaceholder')"
          class="w-full"
          inputmode="tel"
          type="tel"
        />
      </UFormField>

      <TagInput
        v-model="state.tags"
        :disabled="submitting"
        :label="t('features.account.tags.label')"
        :placeholder="t('features.account.tags.placeholder')"
      />
    </UForm>

    <template #footer>
      <div class="flex justify-end">
        <UButton
          :form="FORM_ID"
          :label="
            submitting
              ? t('features.account.profile.saving')
              : t('features.account.profile.save')
          "
          :loading="submitting"
          size="sm"
          type="submit"
        />
      </div>
    </template>
  </UCard>
</template>
