// next/src/features/notice/notice-scope-selector.tsx
"use client";

import type { DeptTreeNode, NoticeScopeType } from "@/lib/api-types";
import type { Key } from "react";

import { Avatar, Label, ListBox, Select, Tabs } from "@heroui/react";
import { useMemo, useState } from "react";

import { useTranslation } from "@/i18n";

/**
 * 公告发布范围选择器（契约 v1.7.0 三粒度并集）：
 * Tabs 三页签——组织（「└ 」前缀层级多选）/ 岗位（多选）/ 人员（多选），
 * 受控值 NoticeScope[]（三类目标合并数组，切换页签不丢已选）。
 *
 * - 停用组织/岗位禁选；
 * - 人员候选与负责人选择器共用 /users 首页 50 条缓存（量级内可用，
 *   全量分页选择随阶段 4 优化）。
 */

export interface NoticeScopeSelectorProps {
  /** 三类目标分别受控（并集语义，提交时合成 NoticeScope[]） */
  deptIds: string[];
  postIds: string[];
  userIds: string[];
  onDeptIdsChange: (ids: string[]) => void;
  onPostIdsChange: (ids: string[]) => void;
  onUserIdsChange: (ids: string[]) => void;
  tree: DeptTreeNode[];
  posts: { id: string; name: string; deptPath: string; status: string }[];
  users: { id: string; username: string; displayName: string }[];
  usersLoading: boolean;
}

export function NoticeScopeSelector({
  deptIds,
  postIds,
  userIds,
  onDeptIdsChange,
  onPostIdsChange,
  onUserIdsChange,
  tree,
  posts,
  users,
  usersLoading,
}: NoticeScopeSelectorProps) {
  const { t } = useTranslation();
  const [tab, setTab] = useState<NoticeScopeType>("dept");

  // 组织平铺选项（「└ 」前缀表达层级，有编码以「名称(编码)」展示，有负责人带小头像；含停用禁选）
  const deptOptions = useMemo(() => {
    const options: {
      id: string;
      label: string;
      avatar: { src?: string; alt: string } | null;
      disabled: boolean;
    }[] = [];

    const walk = (nodes: DeptTreeNode[], level: number) => {
      for (const node of nodes) {
        const prefix = "　".repeat(level) + (level > 0 ? "└ " : "");
        const label = node.code ? `${node.name}(${node.code})` : node.name;
        const avatar = node.leaderName
          ? { src: node.leaderAvatar ?? undefined, alt: node.leaderName }
          : null;

        options.push({
          id: node.id,
          label: prefix + label,
          avatar,
          disabled: node.status !== "enabled",
        });
        walk(node.children, level + 1);
      }
    };

    walk(tree, 0);

    return options;
  }, [tree]);

  const selectedSummary = useMemo(() => {
    const parts: string[] = [];

    if (deptIds.length)
      parts.push(t("features.notices.scope.depts", { count: deptIds.length }));
    if (postIds.length)
      parts.push(t("features.notices.scope.posts", { count: postIds.length }));
    if (userIds.length)
      parts.push(t("features.notices.scope.users", { count: userIds.length }));

    return parts.length ? parts.join("、") : t("features.notices.scope.none");
  }, [deptIds.length, postIds.length, userIds.length, t]);

  return (
    <div className="flex flex-col gap-2">
      <Label>{t("features.notices.form.scope")}</Label>
      <Tabs
        aria-label={t("features.notices.form.scope")}
        selectedKey={tab}
        onSelectionChange={(key) => setTab(String(key) as NoticeScopeType)}
      >
        <Tabs.ListContainer>
          <Tabs.List aria-label={t("features.notices.form.scope")}>
            <Tabs.Tab id="dept">
              {t("features.notices.scope.tabDept")}
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="post">
              {t("features.notices.scope.tabPost")}
              <Tabs.Indicator />
            </Tabs.Tab>
            <Tabs.Tab id="user">
              {t("features.notices.scope.tabUser")}
              <Tabs.Indicator />
            </Tabs.Tab>
          </Tabs.List>
        </Tabs.ListContainer>

        <Tabs.Panel id="dept">
          <Select
            aria-label={t("features.notices.scope.tabDept")}
            className="w-full"
            placeholder={t("features.notices.scope.deptPlaceholder")}
            selectionMode="multiple"
            value={deptIds}
            variant="secondary"
            onChange={(keys) =>
              onDeptIdsChange(((keys as Key[]) ?? []).map(String))
            }
          >
            <Select.Trigger>
              <Select.Value />
              <Select.Indicator />
            </Select.Trigger>
            <Select.Popover>
              <ListBox selectionMode="multiple">
                {deptOptions.map((option) => (
                  <ListBox.Item
                    key={option.id}
                    id={option.id}
                    isDisabled={option.disabled}
                    textValue={option.label}
                  >
                    <span className="flex min-w-0 items-center gap-1.5">
                      {option.avatar ? (
                        <Avatar
                          aria-hidden
                          className="size-5 shrink-0"
                          color="accent"
                          variant="soft"
                        >
                          {option.avatar.src ? (
                            <Avatar.Image
                              alt={option.avatar.alt}
                              loading="lazy"
                              src={option.avatar.src}
                            />
                          ) : null}
                          <Avatar.Fallback className="text-[10px]">
                            {option.avatar.alt.slice(0, 1)}
                          </Avatar.Fallback>
                        </Avatar>
                      ) : null}
                      <span className="block truncate">{option.label}</span>
                    </span>
                    <ListBox.ItemIndicator />
                  </ListBox.Item>
                ))}
              </ListBox>
            </Select.Popover>
          </Select>
        </Tabs.Panel>

        <Tabs.Panel id="post">
          <Select
            aria-label={t("features.notices.scope.tabPost")}
            className="w-full"
            placeholder={t("features.notices.scope.postPlaceholder")}
            selectionMode="multiple"
            value={postIds}
            variant="secondary"
            onChange={(keys) =>
              onPostIdsChange(((keys as Key[]) ?? []).map(String))
            }
          >
            <Select.Trigger>
              <Select.Value />
              <Select.Indicator />
            </Select.Trigger>
            <Select.Popover>
              <ListBox selectionMode="multiple">
                {posts.map((post) => (
                  <ListBox.Item
                    key={post.id}
                    id={post.id}
                    isDisabled={post.status !== "enabled"}
                    textValue={post.name}
                  >
                    <span className="flex flex-col">
                      <span>{post.name}</span>
                      <span className="text-xs text-muted">
                        {post.deptPath}
                      </span>
                    </span>
                    <ListBox.ItemIndicator />
                  </ListBox.Item>
                ))}
              </ListBox>
            </Select.Popover>
          </Select>
        </Tabs.Panel>

        <Tabs.Panel id="user">
          <Select
            aria-label={t("features.notices.scope.tabUser")}
            className="w-full"
            isDisabled={usersLoading}
            placeholder={
              usersLoading
                ? t("features.notices.scope.usersLoading")
                : t("features.notices.scope.userPlaceholder")
            }
            selectionMode="multiple"
            value={userIds}
            variant="secondary"
            onChange={(keys) =>
              onUserIdsChange(((keys as Key[]) ?? []).map(String))
            }
          >
            <Select.Trigger>
              <Select.Value />
              <Select.Indicator />
            </Select.Trigger>
            <Select.Popover>
              <ListBox selectionMode="multiple">
                {users.map((user) => (
                  <ListBox.Item
                    key={user.id}
                    id={user.id}
                    textValue={user.displayName || user.username}
                  >
                    {user.displayName || user.username}
                    <ListBox.ItemIndicator />
                  </ListBox.Item>
                ))}
              </ListBox>
            </Select.Popover>
          </Select>
        </Tabs.Panel>
      </Tabs>
      <p className="text-xs text-muted">{selectedSummary}</p>
    </div>
  );
}

// apps/nuxt/app/features/notice/NoticeScopeSelector.vue
<script setup lang="ts">
import type { DeptTreeNode, NoticeScopeType, User } from '@/lib/api-types'

import { computed, ref } from 'vue'

/**
 * 公告发布范围选择器（契约 v1.7.0 三粒度并集，对应 React 端
 * notice-scope-selector.tsx）：UTabs 三页签——组织（层级多选）/
 * 岗位（多选）/ 人员（多选），受控值三类 id 数组（并集语义，切换页签不丢已选）。
 *
 * - 停用组织/岗位禁选；
 * - 组织候选为全量树扁平化（与 DeptTreeSelect 同款缩进）；
 * - 岗位/人员候选改用 USelectMenu searchable 远程搜索（React 端为
 *   无限滚动）：首屏预取 50 条 + 关键词远端过滤，功能语义等价（全量可选），
 *   实现贴合 Nuxt UI 组件能力。
 */
const props = defineProps<{
  /** 三类目标分别受控（并集语义，提交时合成 NoticeScope[]） */
  deptIds: string[]
  postIds: string[]
  userIds: string[]
  tree: DeptTreeNode[]
  posts: { id: string, name: string, deptPath: string, status: string }[]
  users: Pick<User, 'id' | 'username' | 'displayName' | 'avatar'>[]
  usersLoading: boolean
}>()

const emit = defineEmits<{
  'update:deptIds': [ids: string[]]
  'update:postIds': [ids: string[]]
  'update:userIds': [ids: string[]]
}>()

const { t } = useI18n()

const tab = ref<NoticeScopeType>('dept')

const tabItems = computed(() => [
  { label: t('features.notices.scope.tabDept'), value: 'dept' },
  { label: t('features.notices.scope.tabPost'), value: 'post' },
  { label: t('features.notices.scope.tabUser'), value: 'user' }
])

// 组织平铺选项（「└ 」前缀表达层级，有编码以「名称(编码)」展示；含停用禁选）
interface DeptOption {
  label: string
  value: string
  disabled: boolean
}

const deptOptions = computed<DeptOption[]>(() => {
  const options: DeptOption[] = []

  const walk = (nodes: DeptTreeNode[], level: number) => {
    for (const node of nodes) {
      const prefix = '\u3000'.repeat(level) + (level > 0 ? '└ ' : '')
      const label = node.code ? `${node.name}(${node.code})` : node.name

      options.push({
        label: prefix + label,
        value: node.id,
        disabled: node.status !== 'enabled'
      })
      walk(node.children, level + 1)
    }
  }

  walk(props.tree, 0)

  return options
})

const postOptions = computed(() =>
  props.posts.map(post => ({
    label: post.name,
    // 次行组织路径（USelectMenu item 的 description 槽，对齐 React 端 deptPath 次行）
    description: post.deptPath,
    value: post.id,
    disabled: post.status !== 'enabled'
  }))
)

const userOptions = computed(() =>
  props.users.map((user) => {
    const name = user.displayName || user.username

    return {
      label: name,
      value: user.id,
      // UAvatar props（src 缺省时 UAvatar 用 text 兜底显示首字，同 DeptLeaderSelect）
      avatar: {
        alt: name,
        text: name.slice(0, 1),
        ...(user.avatar ? { src: user.avatar } : {}),
        // as const 防字面量拓宽为 string（AvatarProps.color 为字面量联合）
        color: 'primary' as const
      }
    }
  })
)

const selectedSummary = computed(() => {
  const parts: string[] = []

  if (props.deptIds.length)
    parts.push(
      t('features.notices.scope.depts', { count: props.deptIds.length })
    )
  if (props.postIds.length)
    parts.push(
      t('features.notices.scope.posts', { count: props.postIds.length })
    )
  if (props.userIds.length)
    parts.push(
      t('features.notices.scope.users', { count: props.userIds.length })
    )

  return parts.length ? parts.join('、') : t('features.notices.scope.none')
})

function toIds(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.map(id => String(id))
  }

  return value == null ? [] : [String(value)]
}
</script>

<script lang="ts">
export default { name: 'NoticeScopeSelector' }
</script>

<template>
  <div class="flex flex-col gap-2">
    <UTabs
      v-model:model-value="tab"
      :content="false"
      :items="tabItems"
      size="sm"
    />

    <USelectMenu
      v-if="tab === 'dept'"
      :items="deptOptions"
      :model-value="deptIds"
      :placeholder="t('features.notices.scope.deptPlaceholder')"
      class="w-full"
      multiple
      value-key="value"
      @update:model-value="
        (value: unknown) => emit('update:deptIds', toIds(value))
      "
    />

    <USelectMenu
      v-else-if="tab === 'post'"
      :items="postOptions"
      :model-value="postIds"
      :placeholder="t('features.notices.scope.postPlaceholder')"
      class="w-full"
      multiple
      value-key="value"
      :ui="{
        itemDescription: 'text-xs'
      }"
      @update:model-value="
        (value: unknown) => emit('update:postIds', toIds(value))
      "
    />

    <USelectMenu
      v-else
      :items="userOptions"
      :loading="usersLoading"
      :model-value="userIds"
      :placeholder="
        usersLoading
          ? t('features.notices.scope.usersLoading')
          : t('features.notices.scope.userPlaceholder')
      "
      class="w-full"
      multiple
      value-key="value"
      @update:model-value="
        (value: unknown) => emit('update:userIds', toIds(value))
      "
    />

    <p class="text-muted text-xs">
      {{ selectedSummary }}
    </p>
  </div>
</template>
