// next/src/features/org/dept-form-dialog.tsx
"use client";

import type {
  Dept,
  DeptCreateInput,
  DeptTreeNode,
  DeptUpdateInput,
} from "@/lib/api-types";
import type { User } from "@/lib/api-types";

import { zodResolver } from "@hookform/resolvers/zod";
import {
  keepPreviousData,
  useInfiniteQuery,
  useMutation,
} from "@tanstack/react-query";
import {
  Button,
  Description,
  FieldError,
  Form,
  Input,
  Label,
  ListBox,
  Modal,
  Select,
  Spinner,
  Switch,
  TextField,
  toast,
} from "@heroui/react";
import { ListBoxLoadMoreItem } from "react-aria-components";
import { Check, X } from "lucide-react";
import { useCallback } from "react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { createDept, getDeptErrorMessage, updateDept } from "./dept-api";

import { UserInfo } from "@/components/common/user-info/user-info";
import {
  SortField,
  sortFieldSchema,
} from "@/components/common/sort-field/sort-field";
import { fetchApiList } from "@/lib/api-client";
import { useTranslation } from "@/i18n";

/**
 * 组织新增/编辑弹窗（react-hook-form + zod + HeroUI Form）。
 *
 * - parentId 用平铺缩进的 Select 表达树形层级（HeroUI 无 Tree 组件）；
 *   不选 = 顶级组织（提交映射 null）；编辑时禁用自身与后代（防环），
 *   停用组织不可作父级；「新增子组织」入口进入时上级锁定为所选父级；
 * - leaderId 拉取 /users（page 1, pageSize 50）选择（UserInfo 带头像展示）；
 *   无用户读取权限时降级为禁用并提示（不阻塞其余字段编辑）；
 * - 名称/编码冲突由后端 409 拦截，错误文案经 getDeptErrorMessage i18n 映射。
 */

export type DeptFormMode = "create" | "edit";

export interface DeptFormDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: DeptFormMode;
  /** edit：被编辑的组织；create：null */
  dept: Dept | null;
  /** create：预设的父级组织（在选中节点下新增）；edit：忽略 */
  parentNode: DeptTreeNode | null;
  /** 全量组织树（父级选择器数据源） */
  tree: DeptTreeNode[];
  /** 保存成功回调（页面统一做缓存失效与选中联动） */
  onSaved: (dept: Dept, mode: DeptFormMode) => void;
}

const FORM_ID = "dept-form";

const deptFormSchema = z.object({
  name: z.string().trim().min(1).max(100),
  code: z.string().trim().max(50),
  /** "" = 顶级组织（提交时映射 null） */
  parentId: z.string(),
  /** "" = 不设置负责人（提交时映射 null） */
  leaderId: z.string(),
  sort: sortFieldSchema,
  status: z.enum(["enabled", "disabled"]),
});

type DeptFormValues = z.infer<typeof deptFormSchema>;

interface ParentOption {
  id: string;
  label: string;
  depth: number;
  disabled: boolean;
}

/** 树 → 平铺下拉选项（缩进层级；编辑时自身与后代禁选，停用组织禁选；不选 = 顶级） */
function buildParentOptions(
  tree: DeptTreeNode[],
  selfId: string | null,
): ParentOption[] {
  const options: ParentOption[] = [];

  const walk = (nodes: DeptTreeNode[], depth: number, underSelf: boolean) => {
    for (const node of nodes) {
      const isSelf = node.id === selfId;
      const disabled = node.status !== "enabled" || underSelf || isSelf;

      options.push({ id: node.id, label: node.name, depth, disabled });
      walk(node.children, depth + 1, underSelf || isSelf);
    }
  };

  walk(tree, 0, false);

  return options;
}

export function DeptFormDialog({
  isOpen,
  onOpenChange,
  mode,
  dept,
  parentNode,
  tree,
  onSaved,
}: DeptFormDialogProps) {
  // Modal 结构渲染在有 mutation 的内层组件（DeptFormModal），
  // 保证 Modal.Footer 是 Modal.Dialog 的直接子元素（Body 滚动、Footer 固定）
  return isOpen ? (
    <DeptFormModal
      key={`${mode}:${dept?.id ?? parentNode?.id ?? "root"}`}
      isOpen
      dept={dept}
      mode={mode}
      parentNode={parentNode}
      tree={tree}
      onOpenChange={onOpenChange}
      onSaved={onSaved}
    />
  ) : null;
}

interface DeptFormProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: DeptFormMode;
  dept: Dept | null;
  parentNode: DeptTreeNode | null;
  tree: DeptTreeNode[];
  onSaved: (dept: Dept, mode: DeptFormMode) => void;
}

function DeptFormModal({
  isOpen,
  onOpenChange,
  mode,
  dept,
  parentNode,
  tree,
  onSaved,
}: DeptFormProps) {
  const { t } = useTranslation();
  const isEdit = mode === "edit";
  // 「新增子组织」入口（create 且带预设父级）：上级组织锁定不可修改
  const isCreateChild = mode === "create" && Boolean(parentNode);

  const { control, handleSubmit, setValue, watch } = useForm<DeptFormValues>({
    resolver: zodResolver(deptFormSchema),
    defaultValues: {
      name: dept?.name ?? "",
      code: dept?.code ?? "",
      parentId: dept ? (dept.parentId ?? "") : (parentNode?.id ?? ""),
      leaderId: dept?.leaderId ?? "",
      sort: dept?.sort ?? 0,
      status: dept?.status ?? "enabled",
    },
  });

  // 负责人候选由 <LeaderSelect> 自管理（/users 分页 + 滚动加载），见文件底部

  const mutation = useMutation({
    mutationFn: (values: DeptFormValues) => {
      if (isEdit) {
        const input: DeptUpdateInput = {
          name: values.name,
          code: values.code || null,
          parentId: values.parentId || null,
          leaderId: values.leaderId || null,
          sort: values.sort,
          status: values.status,
        };

        return updateDept(dept!.id, input);
      }

      const input: DeptCreateInput = {
        name: values.name,
        code: values.code || null,
        parentId: values.parentId || null,
        leaderId: values.leaderId || null,
        sort: values.sort,
        status: values.status,
      };

      return createDept(input);
    },
    // 提示反馈统一由 onSubmit 的 toast.promise 呈现（loading → success/error）；
    // 成功副作用（缓存失效联动、关弹窗）保留在此
    onSuccess: (saved) => {
      onSaved(saved, mode);
      onOpenChange(false);
    },
  });

  const onSubmit = handleSubmit((values) => {
    toast.promise(mutation.mutateAsync(values), {
      loading: t("features.depts.form.saving"),
      success: t(
        isEdit
          ? "features.depts.message.updated"
          : "features.depts.message.created",
      ),
      error: (error) => getDeptErrorMessage(error),
    });
  });

  const parentOptions = buildParentOptions(
    tree,
    isEdit ? (dept?.id ?? null) : null,
  );

  return (
    <Modal.Backdrop
      isKeyboardDismissDisabled
      isDismissable={false}
      isOpen={isOpen}
      onOpenChange={onOpenChange}
    >
      <Modal.Container>
        <Modal.Dialog className="sm:max-w-md">
          <Modal.CloseTrigger />
          <Modal.Header>
            <Modal.Heading>
              {t(
                isEdit
                  ? "features.depts.form.title.edit"
                  : "features.depts.form.title.create",
              )}
            </Modal.Heading>
          </Modal.Header>
          <Modal.Body>
            <Form
              className="flex flex-col gap-4"
              id={FORM_ID}
              // 校验统一交给 react-hook-form（aria 行为避免 required 抢聚焦阻断提交）
              validationBehavior="aria"
              onSubmit={(event) => void onSubmit(event)}
            >
              <Controller
                control={control}
                name="parentId"
                render={({ field }) => (
                  <div className="flex flex-col gap-1">
                    <Label>{t("features.depts.form.parent")}</Label>
                    <div className="flex items-center gap-2">
                      <Select
                        aria-label={t("features.depts.form.parent")}
                        className="flex-1"
                        isDisabled={isCreateChild}
                        placeholder={t("features.depts.form.parentPlaceholder")}
                        value={field.value || null}
                        variant="secondary"
                        onChange={(key) =>
                          field.onChange(key === null ? "" : String(key))
                        }
                      >
                        <Select.Trigger>
                          <Select.Value />
                          <Select.Indicator />
                        </Select.Trigger>
                        <Select.Popover>
                          <ListBox>
                            {parentOptions.map((option) => (
                              <ListBox.Item
                                key={option.id}
                                id={option.id}
                                isDisabled={option.disabled}
                                textValue={option.label}
                              >
                                <span
                                  className="block truncate"
                                  style={{
                                    paddingInlineStart: option.depth * 16,
                                  }}
                                >
                                  {option.label}
                                </span>
                                <ListBox.ItemIndicator />
                              </ListBox.Item>
                            ))}
                          </ListBox>
                        </Select.Popover>
                      </Select>
                      {field.value && !isCreateChild && (
                        <Button
                          isIconOnly
                          aria-label={t("features.depts.form.parentClear")}
                          size="sm"
                          variant="ghost"
                          onPress={() => field.onChange("")}
                        >
                          <X className="size-4" />
                        </Button>
                      )}
                    </div>
                    <Description>
                      {t("features.depts.form.parentHint")}
                    </Description>
                  </div>
                )}
              />

              <Controller
                control={control}
                name="name"
                render={({ field, fieldState }) => (
                  <TextField
                    isRequired
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.depts.form.name")}</Label>
                    <Input
                      maxLength={100}
                      placeholder={t("features.depts.form.namePlaceholder")}
                      variant="secondary"
                    />
                    {fieldState.error && (
                      <FieldError>
                        {t("features.depts.form.nameInvalid")}
                      </FieldError>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="code"
                render={({ field, fieldState }) => (
                  <TextField
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.depts.form.code")}</Label>
                    <Input
                      maxLength={50}
                      placeholder="DEPT-001"
                      variant="secondary"
                    />
                    {fieldState.error ? (
                      <FieldError>
                        {t("features.depts.form.codeInvalid")}
                      </FieldError>
                    ) : (
                      <Description>
                        {t("features.depts.form.codeHint")}
                      </Description>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="leaderId"
                render={({ field }) => (
                  <LeaderSelect
                    currentLeader={
                      isEdit && dept?.leaderId
                        ? {
                            id: dept.leaderId,
                            displayName: dept.leaderName ?? dept.leaderId,
                          }
                        : null
                    }
                    value={field.value}
                    onChange={(key) => field.onChange(key)}
                  />
                )}
              />

              <SortField
                value={watch("sort")}
                onChange={(value) =>
                  setValue("sort", value, { shouldValidate: true })
                }
              />

              <SwitchRow
                checked={watch("status") === "enabled"}
                label={t("features.depts.form.status")}
                onChange={(checked) =>
                  setValue("status", checked ? "enabled" : "disabled")
                }
              />
            </Form>
          </Modal.Body>

          <Modal.Footer className="w-full">
            <Button slot="close" variant="secondary">
              {t("common.cancel")}
            </Button>
            <Button form={FORM_ID} isPending={mutation.isPending} type="submit">
              {({ isPending }) =>
                isPending ? (
                  <>
                    <Spinner color="current" size="sm" />
                    {t("features.depts.form.saving")}
                  </>
                ) : (
                  t("common.confirm")
                )
              }
            </Button>
          </Modal.Footer>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  );
}

interface SwitchRowProps {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}

/** 左 Label 右 Switch 的单行开关（对齐菜单管理表单布局） */
function SwitchRow({ label, checked, onChange }: SwitchRowProps) {
  return (
    <div className="flex items-center justify-between gap-3 rounded-3xl border border-border px-3 py-2">
      <Label>{label}</Label>
      <Switch aria-label={label} isSelected={checked} onChange={onChange}>
        {({ isSelected }) => (
          <Switch.Content>
            <Switch.Control>
              <Switch.Thumb>
                <Switch.Icon>
                  {isSelected ? (
                    <Check className="size-3 text-inherit opacity-100" />
                  ) : (
                    <X className="size-3 text-inherit opacity-70" />
                  )}
                </Switch.Icon>
              </Switch.Thumb>
            </Switch.Control>
          </Switch.Content>
        )}
      </Switch>
    </div>
  );
}

const LEADER_PAGE_SIZE = 50;

/** 编辑回显兜底候选：当前负责人不在已加载用户列表中时，渲染为列表首条 */
interface CurrentLeader {
  id: string;
  displayName: string;
}

/**
 * 负责人选择器：/users 分页下拉 + 滚动到底自动加载下一页
 * （react-aria ListBoxLoadMoreItem 模式，对齐 HeroUI Select 异步加载示例）。
 *
 * 数据用 useInfiniteQuery 缓存（跨弹窗共享、staleTime 内开关弹窗不重复请求），
 * 滚动加载走 fetchNextPage；无权限（403）等加载失败：禁用选择器，
 * 不阻塞表单其余字段编辑。
 */
function LeaderSelect({
  value,
  onChange,
  currentLeader,
}: {
  /** 当前选中值（"" = 未选择） */
  value: string;
  onChange: (key: string) => void;
  currentLeader: CurrentLeader | null;
}) {
  const { t } = useTranslation();

  const usersQuery = useInfiniteQuery({
    queryKey: ["users", "leader-options"],
    queryFn: ({ pageParam }) =>
      fetchApiList<User>("/users", {
        page: pageParam,
        pageSize: LEADER_PAGE_SIZE,
      }),
    initialPageParam: 1,
    getNextPageParam: (lastPage, allPages) =>
      allPages.length * LEADER_PAGE_SIZE < lastPage.pagination.total
        ? allPages.length + 1
        : undefined,
    // 弹窗反复开关共享缓存：staleTime 内不发请求，过期后台 refetch 不打断交互
    staleTime: 60_000,
    placeholderData: keepPreviousData,
    retry: false,
  });

  const items = usersQuery.data?.pages.flatMap((page) => page.data) ?? [];
  const failed = usersQuery.isError;
  // ListBoxLoadMoreItem 进入视口可能连续触发，翻页中不重复 fetchNextPage
  const handleLoadMore = useCallback(() => {
    if (!failed && usersQuery.hasNextPage && !usersQuery.isFetchingNextPage) {
      void usersQuery.fetchNextPage();
    }
  }, [failed, usersQuery]);

  const currentLeaderVisible =
    !currentLeader || items.some((user) => user.id === currentLeader.id);

  return (
    <Select
      className="flex w-full flex-col gap-1"
      isDisabled={failed}
      placeholder={
        usersQuery.isLoading
          ? t("features.depts.form.leaderLoading")
          : failed
            ? t("features.depts.form.leaderLoadFailed")
            : items.length === 0 && !currentLeader
              ? t("features.depts.form.leaderEmpty")
              : t("features.depts.form.leaderPlaceholder")
      }
      value={value || null}
      variant="secondary"
      onChange={(key) => onChange(key === null ? "" : String(key))}
    >
      <Label>{t("features.depts.form.leader")}</Label>
      <Select.Trigger>
        <Select.Value />
        <Select.Indicator />
      </Select.Trigger>
      <Select.Popover>
        <ListBox aria-label={t("features.depts.form.leader")}>
          {!currentLeaderVisible && currentLeader && (
            <ListBox.Item
              id={currentLeader.id}
              textValue={currentLeader.displayName}
            >
              {/* 合成候选仅姓名可显示（无 username / avatar 数据） */}
              <span className="text-sm">{currentLeader.displayName}</span>
              <ListBox.ItemIndicator />
            </ListBox.Item>
          )}
          {items.map((user) => (
            <ListBox.Item
              key={user.id}
              id={user.id}
              textValue={user.displayName || user.username}
            >
              <UserInfo subtitle="username" user={user} />
              <ListBox.ItemIndicator />
            </ListBox.Item>
          ))}
          <ListBoxLoadMoreItem
            isLoading={usersQuery.isFetchingNextPage}
            onLoadMore={handleLoadMore}
          >
            {usersQuery.hasNextPage && !failed ? (
              <div className="flex items-center justify-center gap-2 py-2">
                <Spinner size="sm" />
                <span className="text-sm text-muted">
                  {t("features.depts.form.leaderLoadingMore")}
                </span>
              </div>
            ) : null}
          </ListBoxLoadMoreItem>
        </ListBox>
      </Select.Popover>
    </Select>
  );
}

// vue/src/features/org/DeptFormDialog.vue
<script setup lang="ts">
import type { Dept, DeptTreeNode, DeptStatus } from "@/lib/api-types";

import { computed, reactive, ref, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import { createDept, getDeptErrorMessage, updateDept } from "./dept-api";
import DeptLeaderSelect from "./DeptLeaderSelect.vue";
import DeptTreeSelect from "./DeptTreeSelect.vue";

/**
 * 组织新增/编辑弹窗（对应 React 端 dept-form-dialog.tsx，手动校验范式同 M1）。
 *
 * - parentId 用平铺缩进的树选择器（DeptTreeSelect，M1 用户表单共用组件）；
 *   不选 = 顶级组织（提交映射 null）；编辑时禁选自身与后代（防环），
 *   停用组织不可作父级；「新增子组织」入口进入时上级锁定不可修改；
 * - leaderId 拉取 /users（pageSize 50 滚动加载）选择；无用户读取权限时
 *   降级为禁用并提示（不阻塞其余字段编辑）；
 * - 名称/编码冲突由后端 409 拦截，错误文案经 getDeptErrorMessage i18n 映射。
 */
const props = defineProps<{
  open: boolean;
  mode: "create" | "edit";
  /** edit：被编辑的组织（树节点，含全部表单回显字段）；create：null */
  dept: DeptTreeNode | null;
  /** create：预设的父级组织（在选中节点下新增）；edit：忽略 */
  parentNode: DeptTreeNode | null;
  /** 全量组织树（父级选择器数据源） */
  tree: DeptTreeNode[];
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
  /** 保存成功（页面统一做缓存失效与选中联动） */
  saved: [dept: Dept, mode: "create" | "edit"];
}>();

const { t } = useI18n();
const toast = useToast();

const FORM_ID = "dept-form";

const form = reactive({
  name: "",
  code: "",
  parentId: "",
  leaderId: "",
  sort: 0,
  status: "enabled" as DeptStatus,
});
const errors = reactive({ name: "", code: "" });
const submitting = ref(false);

const isEdit = computed(() => props.mode === "edit");
// 「新增子组织」入口（create 且带预设父级）：上级组织锁定不可修改
const isCreateChild = computed(
  () => props.mode === "create" && Boolean(props.parentNode),
);

watch(
  () => props.open,
  (open) => {
    if (!open) return;

    form.name = props.dept?.name ?? "";
    form.code = props.dept?.code ?? "";
    form.parentId = props.dept
      ? (props.dept.parentId ?? "")
      : (props.parentNode?.id ?? "");
    form.leaderId = props.dept?.leaderId ?? "";
    form.sort = props.dept?.sort ?? 0;
    form.status = props.dept?.status ?? "enabled";
    errors.name = "";
    errors.code = "";
  },
  { immediate: true },
);

function close() {
  emit("update:open", false);
}

function validate(): boolean {
  errors.name =
    form.name.trim().length >= 1 && form.name.trim().length <= 100
      ? ""
      : t("features.depts.form.nameInvalid");
  errors.code =
    form.code.trim().length <= 50 ? "" : t("features.depts.form.codeInvalid");

  return !Object.values(errors).some(Boolean);
}

async function onSubmit() {
  if (!validate()) return;

  submitting.value = true;

  try {
    const input = {
      name: form.name.trim(),
      code: form.code.trim() || null,
      parentId: form.parentId || null,
      leaderId: form.leaderId || null,
      sort: form.sort,
      status: form.status,
    };

    const saved = isEdit.value
      ? await updateDept(props.dept!.id, input)
      : await createDept(input);

    emit("saved", saved, props.mode);
    close();

    toast.add({
      color: "success",
      duration: 3000,
      title: t(
        isEdit.value
          ? "features.depts.message.updated"
          : "features.depts.message.created",
      ),
    });
  } catch (error) {
    toast.add({
      color: "error",
      duration: 5000,
      title: getDeptErrorMessage(error),
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<script lang="ts">
export default { name: "DeptFormDialog" };
</script>

<template>
  <UModal
    :open="open"
    :dismissible="false"
    :ui="{ content: 'sm:max-w-md' }"
    @update:open="(value: boolean) => !value && close()"
  >
    <template #content>
      <form
        :id="FORM_ID"
        class="flex flex-col gap-4 p-6"
        @submit.prevent="onSubmit"
      >
        <h2 class="text-lg font-semibold">
          {{
            t(
              isEdit
                ? "features.depts.form.title.edit"
                : "features.depts.form.title.create",
            )
          }}
        </h2>

        <UFormField
          :label="t('features.depts.form.parent')"
          :help="t('features.depts.form.parentHint')"
          :disabled="isCreateChild"
        >
          <div class="flex items-center gap-2">
            <DeptTreeSelect
              v-model="form.parentId"
              :is-disabled="isCreateChild"
              :self-id="isEdit ? (dept?.id ?? null) : null"
              :placeholder="t('features.depts.form.parentPlaceholder')"
              :tree="tree"
              class="flex-1"
            />
            <UButton
              v-if="form.parentId && !isCreateChild"
              :aria-label="t('features.depts.form.parentClear')"
              class="shrink-0"
              color="neutral"
              icon="i-lucide-x"
              size="sm"
              variant="ghost"
              @click="form.parentId = ''"
            />
          </div>
        </UFormField>

        <UFormField
          :error="errors.name || undefined"
          :label="t('features.depts.form.name')"
          required
        >
          <UInput
            v-model="form.name"
            :maxlength="100"
            :placeholder="t('features.depts.form.namePlaceholder')"
            class="w-full"
          />
        </UFormField>

        <UFormField
          :error="errors.code || undefined"
          :help="errors.code ? undefined : t('features.depts.form.codeHint')"
          :label="t('features.depts.form.code')"
        >
          <UInput
            v-model="form.code"
            :maxlength="50"
            placeholder="DEPT-001"
            class="w-full"
          />
        </UFormField>

        <DeptLeaderSelect
          v-model="form.leaderId"
          :current-leader="
            isEdit && dept?.leaderId
              ? {
                  id: dept.leaderId,
                  displayName: dept.leaderName ?? dept.leaderId,
                }
              : null
          "
        />

        <UFormField :label="t('common.column.sort')">
          <UInput
            v-model.number="form.sort"
            class="w-full"
            type="number"
            variant="soft"
          />
        </UFormField>

        <div
          class="border-default flex items-center justify-between gap-3 rounded-xl border px-3 py-2"
        >
          <span class="text-sm">
            {{ t("features.depts.form.status") }}
          </span>
          <USwitch
            :aria-label="t('features.depts.form.status')"
            :model-value="form.status === 'enabled'"
            @update:model-value="
              (value: boolean) => (form.status = value ? 'enabled' : 'disabled')
            "
          />
        </div>

        <div class="flex items-center justify-end gap-2 pt-2">
          <UButton
            color="neutral"
            :label="t('common.cancel')"
            type="button"
            variant="subtle"
            @click="close"
          />
          <UButton
            :form="FORM_ID"
            :label="
              submitting ? t('features.depts.form.saving') : t('common.confirm')
            "
            :loading="submitting"
            type="submit"
          />
        </div>
      </form>
    </template>
  </UModal>
</template>
