// next/src/features/org/depts-page.tsx
"use client";

import type { Dept, DeptSortItem, DeptTreeNode } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/common/data-table/table-types";
import type { DeptFormMode } from "./dept-form-dialog";

import {
  Button,
  Chip,
  Dropdown,
  Label,
  Surface,
  Typography,
  toast,
  useOverlayState,
} from "@heroui/react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTable } from "@tanstack/react-table";
import { MoreHorizontal, Pencil, Plus, Trash2 } from "lucide-react";
import { useCallback, useMemo, useState } from "react";

import { deleteDept, getDeptErrorMessage, sortDepts } from "./dept-api";
import { DeptFormDialog } from "./dept-form-dialog";
import { DeptTreePanel } from "./dept-tree-panel";
import { DEPTS_TREE_QUERY_KEY, fetchDeptTree } from "./dept-api";

import { ConfirmDialog } from "@/components/common/confirm-dialog/confirm-dialog";
import { DataTable } from "@/components/common/data-table";
import {
  DataTableViewOptions,
  buildColumnSettingKey,
} from "@/components/common/data-table";
import { appTableFeatures } from "@/components/common/data-table/table-types";
import { EmptyContent } from "@/components/common/empty-content/empty-content";
import { useMenuPermissions } from "@/hooks/use-permissions";
import { useTranslation } from "@/i18n";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 组织管理页（契约 v1.6.0 阶段 1）：左树右表布局。
 *
 * - 数据源统一为全量树查询（GET /org/depts/tree）：左栏树、右栏选中组织
 *   详情与子组织列表均由树派生，避免树 + 分页双请求的瀑布；
 * - 同级拖拽整组重编号后提交 PATCH /org/depts/sort，成功后失效树缓存；
 * - 删除由后端三级校验 409 拦截（HAS_CHILDREN / HAS_POSTS / HAS_ACTIVE_USERS），
 *   前端二次确认弹窗 + toast 透出。
 */

interface FormContext {
  mode: DeptFormMode;
  dept: Dept | null;
  /** create：预设父级（新增子组织）；create-root 为 null */
  parentNode: DeptTreeNode | null;
}

export function DeptsPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const userId = useAuthStore((state) => state.user?.id);
  const { canAdd, canEdit, canDelete } = useMenuPermissions();

  // 全量树（含停用组织，左栏置灰）；staleTime 0 保证强一致
  const treeQuery = useQuery({
    queryKey: DEPTS_TREE_QUERY_KEY,
    queryFn: fetchDeptTree,
    placeholderData: (prev) => prev,
    staleTime: 0,
  });
  const tree = useMemo(() => treeQuery.data ?? [], [treeQuery.data]);

  // 选中组织：派生态——selectedId 不在树中（被删/未选）时回退顶级首个
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selectedNode = useMemo<DeptTreeNode | null>(() => {
    const find = (nodes: DeptTreeNode[]): DeptTreeNode | null => {
      for (const node of nodes) {
        if (node.id === selectedId) return node;
        const found = find(node.children);

        if (found) return found;
      }

      return null;
    };

    return find(tree) ?? tree[0] ?? null;
  }, [tree, selectedId]);

  const invalidateTree = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: DEPTS_TREE_QUERY_KEY });
  }, [queryClient]);

  const reorderMutation = useMutation({
    mutationFn: sortDepts,
    // 成功失败都失效树：失败时同样回拉服务端真实状态，避免本地残留拖拽后的视觉顺序
    onSettled: () => invalidateTree(),
  });

  /** 同级拖拽提交：toast.promise 全程反馈（排序中 → 成功/失败），失败自动回拉树 */
  const handleReorder = useCallback(
    (items: DeptSortItem[]) => {
      toast.promise(reorderMutation.mutateAsync(items), {
        loading: t("features.depts.message.sorting"),
        success: t("features.depts.message.sorted"),
        error: (error) => getDeptErrorMessage(error),
      });
    },
    [reorderMutation, t],
  );

  // ---------------- 弹窗状态（useOverlayState，§7.2 受控浮层语义） ----------------
  const formDialog = useOverlayState();
  const deleteDialog = useOverlayState();

  const [formContext, setFormContext] = useState<FormContext>({
    mode: "create",
    dept: null,
    parentNode: null,
  });
  const [deleteTarget, setDeleteTarget] = useState<DeptTreeNode | null>(null);

  const openCreateRoot = useCallback(() => {
    setFormContext({ mode: "create", dept: null, parentNode: null });
    formDialog.open();
  }, [formDialog]);

  const openCreateChild = useCallback(
    (parent: DeptTreeNode) => {
      setFormContext({ mode: "create", dept: null, parentNode: parent });
      formDialog.open();
    },
    [formDialog],
  );

  const openEdit = useCallback(
    (dept: Dept | DeptTreeNode) => {
      setFormContext({ mode: "edit", dept: dept as Dept, parentNode: null });
      formDialog.open();
    },
    [formDialog],
  );

  const openDelete = useCallback(
    (node: DeptTreeNode) => {
      setDeleteTarget(node);
      deleteDialog.open();
    },
    [deleteDialog],
  );

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deleteDept(id),
    onSuccess: () => {
      invalidateTree();
      toast.success(t("features.depts.message.deleted"));
    },
    onError: (error) => {
      toast.danger(getDeptErrorMessage(error));
    },
  });

  const handleSaved = useCallback(
    (_saved: Dept, mode: DeptFormMode) => {
      invalidateTree();
      // 新增子组织后展开父节点由「全展开」默认态天然覆盖，无需额外处理
      void mode;
    },
    [invalidateTree],
  );

  // ---------------- 子组织表格列（数据源：选中节点的 children） ----------------
  const childNodes = selectedNode?.children ?? [];

  const columns = useMemo<AppColumnDef<DeptTreeNode>[]>(
    () => [
      {
        id: "name",
        enableSorting: false,
        header: t("features.depts.column.name"),
        cell: ({ row }) => (
          <Typography className="font-medium" type="body-sm">
            {row.original.name}
          </Typography>
        ),
      },
      {
        id: "code",
        enableSorting: false,
        header: t("features.depts.column.code"),
        cell: ({ row }) => (
          <Typography className="font-mono" type="body-sm">
            {row.original.code ?? "—"}
          </Typography>
        ),
      },
      {
        id: "leaderName",
        enableSorting: false,
        header: t("features.depts.column.leader"),
        cell: ({ row }) => (
          <Typography type="body-sm">
            {row.original.leaderName ?? "—"}
          </Typography>
        ),
      },
      {
        id: "childCount",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.depts.column.childCount"),
        cell: ({ row }) => (
          <Chip size="sm">{row.original.children.length}</Chip>
        ),
      },
      {
        id: "status",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.depts.column.status"),
        cell: ({ row }) => (
          <Chip
            color={row.original.status === "enabled" ? "success" : "danger"}
            size="sm"
            variant="soft"
          >
            {t(
              row.original.status === "enabled"
                ? "features.depts.status.enabled"
                : "features.depts.status.disabled",
            )}
          </Chip>
        ),
      },
      {
        id: "actions",
        enableSorting: false,
        enableHiding: false,
        meta: { align: "center" },
        header: t("common.actions"),
        cell: ({ row }) => {
          if (!canEdit && !canDelete && !canAdd) return null;

          return (
            <Dropdown>
              <Button
                isIconOnly
                aria-label={t("common.actions")}
                size="sm"
                variant="ghost"
              >
                <MoreHorizontal className="size-4" />
              </Button>
              <Dropdown.Popover className="min-w-36">
                <Dropdown.Menu
                  onAction={(key) => {
                    if (key === "add") openCreateChild(row.original);
                    if (key === "edit") openEdit(row.original);
                    if (key === "delete") openDelete(row.original);
                  }}
                >
                  {canAdd && (
                    <Dropdown.Item
                      id="add"
                      textValue={t("features.depts.action.add")}
                    >
                      <Plus className="size-4 shrink-0 text-muted" />
                      <Label>{t("features.depts.action.add")}</Label>
                    </Dropdown.Item>
                  )}
                  {canEdit && (
                    <Dropdown.Item id="edit" textValue={t("common.edit")}>
                      <Pencil className="size-4 shrink-0 text-muted" />
                      <Label>{t("common.edit")}</Label>
                    </Dropdown.Item>
                  )}
                  {canDelete && (
                    <Dropdown.Item
                      id="delete"
                      textValue={t("common.delete")}
                      variant="danger"
                    >
                      <Trash2 className="size-4 shrink-0 text-danger" />
                      <Label>{t("common.delete")}</Label>
                    </Dropdown.Item>
                  )}
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown>
          );
        },
      },
    ],
    [t, canAdd, canEdit, canDelete, openCreateChild, openEdit, openDelete],
  );

  const table = useTable({
    columns,
    data: childNodes,
    features: appTableFeatures,
    // 全量展示：子组织列表随树派生，不渲染分页条
    manualPagination: true,
  });

  return (
    <div className="flex w-full flex-col pb-8">
      <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
        {/* 左栏：组织树面板（与人员通讯录共用 DeptTreePanel） */}
        <DeptTreePanel
          canReorder={canEdit && !reorderMutation.isPending}
          emptyAction={
            canAdd ? (
              <Button size="sm" variant="outline" onPress={openCreateRoot}>
                <Plus className="size-4" />
                {t("features.depts.action.addRoot")}
              </Button>
            ) : undefined
          }
          emptyTitle={t("features.depts.tree.empty")}
          headerAction={
            canAdd ? (
              <Button
                isIconOnly
                aria-label={t("features.depts.action.addRoot")}
                size="sm"
                variant="outline"
                onPress={openCreateRoot}
              >
                <Plus className="size-4" />
              </Button>
            ) : undefined
          }
          isFetching={treeQuery.isFetching}
          isLoading={treeQuery.isLoading}
          nodes={tree}
          selectedId={selectedNode?.id ?? null}
          onReorder={handleReorder}
          onSelect={(node) => setSelectedId(node.id)}
        />

        {/* 右栏：选中组织详情 + 子组织列表 */}
        <div className="flex min-w-0 flex-col gap-6">
          <Surface className="flex flex-col gap-3 rounded-3xl p-4">
            {selectedNode ? (
              <>
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div className="flex min-w-0 items-center gap-2">
                    <Typography
                      className="truncate font-semibold"
                      type="body-sm"
                    >
                      {selectedNode.name}
                    </Typography>
                    <Chip
                      color={
                        selectedNode.status === "enabled" ? "success" : "danger"
                      }
                      size="sm"
                      variant="soft"
                    >
                      {t(
                        selectedNode.status === "enabled"
                          ? "features.depts.status.enabled"
                          : "features.depts.status.disabled",
                      )}
                    </Chip>
                  </div>
                  {/* 允许换行：窄屏/长名称时按钮折行右对齐，不挤压左侧标题区 */}
                  <div className="flex flex-wrap items-center justify-end gap-2">
                    {canAdd && (
                      <Button
                        size="sm"
                        onPress={() => openCreateChild(selectedNode)}
                      >
                        <Plus className="size-4" />
                        {t("features.depts.action.add")}
                      </Button>
                    )}
                    {canEdit && (
                      <Button
                        size="sm"
                        variant="tertiary"
                        onPress={() => openEdit(selectedNode)}
                      >
                        <Pencil className="size-4" />
                        {t("common.edit")}
                      </Button>
                    )}
                    {canDelete && (
                      <Button
                        size="sm"
                        variant="danger"
                        onPress={() => openDelete(selectedNode)}
                      >
                        <Trash2 className="size-4" />
                        {t("common.delete")}
                      </Button>
                    )}
                    <DataTableViewOptions
                      checkboxVariant="secondary"
                      storageKey={
                        userId
                          ? buildColumnSettingKey(userId, "/org/depts")
                          : undefined
                      }
                      table={table}
                    />
                  </div>
                </div>
                <div className="flex flex-wrap gap-x-6 gap-y-1">
                  <Typography color="muted" type="body-sm">
                    {t("features.depts.column.code")}：
                    <span className="font-mono">
                      {selectedNode.code ?? "—"}
                    </span>
                  </Typography>
                  <Typography color="muted" type="body-sm">
                    {t("features.depts.column.leader")}：
                    {selectedNode.leaderName ?? "—"}
                  </Typography>
                  <Typography color="muted" type="body-sm">
                    {t("features.depts.detail.childCount", {
                      count: selectedNode.children.length,
                    })}
                  </Typography>
                </div>
              </>
            ) : (
              <EmptyContent
                className="flex flex-col items-center justify-center gap-2 py-10 text-muted"
                title={t("features.depts.detail.unselected")}
              />
            )}
          </Surface>

          {/* 子组织列表（与详情卡留出呼吸间距，页面底部有 pb-8） */}
          <div className="flex min-w-0 flex-col">
            <DataTable
              aria-label={t("menu.pageTitle.depts")}
              className="w-full"
              contentClassName="min-w-[640px]"
              isLoading={treeQuery.isLoading}
              table={table}
            />
          </div>
        </div>
      </div>

      {/* 弹窗集合 */}
      <DeptFormDialog
        dept={formContext.dept}
        isOpen={formDialog.isOpen}
        mode={formContext.mode}
        parentNode={formContext.parentNode}
        tree={tree}
        onOpenChange={formDialog.setOpen}
        onSaved={handleSaved}
      />

      <ConfirmDialog
        destructive
        confirmText={t("common.delete")}
        description={t("features.depts.message.deleteDesc", {
          name: deleteTarget?.name ?? "",
        })}
        isLoading={deleteMutation.isPending}
        state={{
          isOpen: deleteDialog.isOpen,
          setOpen: deleteDialog.setOpen,
          close: deleteDialog.close,
        }}
        title={t("features.depts.message.deleteTitle")}
        onConfirm={async () => {
          await deleteMutation.mutateAsync(deleteTarget!.id);
        }}
      />
    </div>
  );
}

// vue/src/features/org/DeptsPage.vue
<script setup lang="ts">
import type { DeptSortItem, DeptTreeNode } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/data-table/table-types";

import { computed, h, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useMutation, useQuery, useQueryClient } from "@tanstack/vue-query";
import { keepPreviousData } from "@tanstack/vue-query";
import { useToast } from "@nuxt/ui/composables";
import { useTable } from "@tanstack/vue-table";
import UButton from "@nuxt/ui/runtime/components/Button.vue";
import UDropdownMenu from "@nuxt/ui/runtime/components/DropdownMenu.vue";

import {
  DEPTS_TREE_QUERY_KEY,
  deleteDept,
  fetchDeptTree,
  getDeptErrorMessage,
  sortDepts,
} from "./dept-api";
import DeptFormDialog from "./DeptFormDialog.vue";
import DeptTreePanel from "./DeptTreePanel.vue";

import ConfirmDialog from "@/components/common/ConfirmDialog.vue";
import DataTable from "@/components/data-table/DataTable.vue";
import {
  appTableFeatures,
  type AppTable,
} from "@/components/data-table/table-types";
import { useMenuPermissions } from "@/composables/use-permissions";

/**
 * 组织管理页（契约 v1.6.0 阶段 1，对应 React 端 depts-page.tsx）：左树右表布局。
 *
 * - 数据源统一为全量树查询（GET /org/depts/tree）：左栏树、右栏选中组织
 *   详情与子组织列表均由树派生，避免树 + 分页双请求的瀑布；
 * - 同级拖拽整组重编号后提交 PATCH /org/depts/sort，成功失败都失效树缓存
 *   （失败时同样回拉服务端真实状态，避免本地残留拖拽后的视觉顺序）；
 * - 删除由后端三级校验 409 拦截（HAS_CHILDREN / HAS_POSTS / HAS_ACTIVE_USERS），
 *   前端关键词确认弹窗 + toast 透出。
 */

const { t } = useI18n();
const queryClient = useQueryClient();
const toast = useToast();
const { canAdd, canEdit, canDelete } = useMenuPermissions();

// 全量树（含停用组织，左栏置灰）；staleTime 0 保证强一致
const treeQuery = useQuery({
  queryKey: DEPTS_TREE_QUERY_KEY,
  queryFn: fetchDeptTree,
  placeholderData: keepPreviousData,
  staleTime: 0,
});
const tree = computed(() => treeQuery.data.value ?? []);

// 选中组织：派生态——selectedId 不在树中（被删/未选）时回退顶级首个
const selectedId = ref<string | null>(null);
const selectedNode = computed<DeptTreeNode | null>(() => {
  const find = (nodes: DeptTreeNode[]): DeptTreeNode | null => {
    for (const node of nodes) {
      if (node.id === selectedId.value) return node;

      const found = find(node.children);

      if (found) return found;
    }

    return null;
  };

  return find(tree.value) ?? tree.value[0] ?? null;
});

function invalidateTree() {
  void queryClient.invalidateQueries({ queryKey: DEPTS_TREE_QUERY_KEY });
}

// ---------------- 同级拖拽排序 ----------------

const reorderMutation = useMutation({
  mutationFn: sortDepts,
  // 成功失败都失效树：失败时同样回拉服务端真实状态，避免本地残留拖拽后的视觉顺序
  onSettled: () => invalidateTree(),
});

function handleReorder(items: DeptSortItem[]) {
  reorderMutation.mutate(items, {
    onSuccess: () => {
      toast.add({
        color: "success",
        duration: 3000,
        title: t("features.depts.message.sorted"),
      });
    },
    onError: (error) => {
      toast.add({
        color: "error",
        duration: 5000,
        title: getDeptErrorMessage(error),
      });
    },
  });
}

// ---------------- 弹窗状态 ----------------

interface FormContext {
  mode: "create" | "edit";
  dept: DeptTreeNode | null;
  /** create：预设父级（新增子组织）；create-root 为 null */
  parentNode: DeptTreeNode | null;
}

const formOpen = ref(false);
const formMode = ref<FormContext["mode"]>("create");
const formDept = ref<DeptTreeNode | null>(null);
const formParentNode = ref<DeptTreeNode | null>(null);

const deleteOpen = ref(false);
const deleteTarget = ref<DeptTreeNode | null>(null);
const deleteSubmitting = ref(false);

function openCreateRoot() {
  formMode.value = "create";
  formDept.value = null;
  formParentNode.value = null;
  formOpen.value = true;
}

function openCreateChild(parent: DeptTreeNode) {
  formMode.value = "create";
  formDept.value = null;
  formParentNode.value = parent;
  formOpen.value = true;
}

function openEdit(node: DeptTreeNode) {
  formMode.value = "edit";
  // 树节点含全部表单回显字段（标量子集），直接传节点
  formDept.value = node;
  formParentNode.value = null;
  formOpen.value = true;
}

function openDelete(node: DeptTreeNode) {
  deleteTarget.value = node;
  deleteOpen.value = true;
}

const deleteMutation = useMutation({
  mutationFn: (id: string) => deleteDept(id),
});

async function handleDeleteConfirm() {
  if (!deleteTarget.value) return;

  deleteSubmitting.value = true;

  try {
    await deleteMutation.mutateAsync(deleteTarget.value.id);
    invalidateTree();
    deleteOpen.value = false;

    toast.add({
      color: "success",
      duration: 3000,
      title: t("features.depts.message.deleted"),
    });
  } catch (error) {
    toast.add({
      color: "error",
      duration: 5000,
      title: getDeptErrorMessage(error),
    });
  } finally {
    deleteSubmitting.value = false;
  }
}

// ---------------- 子组织表格列（数据源：选中节点的 children） ----------------

const childNodes = computed(() => selectedNode.value?.children ?? []);

const columns = computed<AppColumnDef<DeptTreeNode>[]>(() => [
  {
    id: "name",
    enableSorting: false,
    header: () => t("features.depts.column.name"),
    cell: ({ row }) =>
      h("span", { class: "text-sm font-medium" }, row.original.name),
  },
  {
    id: "code",
    enableSorting: false,
    header: () => t("features.depts.column.code"),
    cell: ({ row }) =>
      h("span", { class: "text-sm font-mono" }, row.original.code ?? "—"),
  },
  {
    id: "leaderName",
    enableSorting: false,
    header: () => t("features.depts.column.leader"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.leaderName ?? "—"),
  },
  {
    id: "childCount",
    enableSorting: false,
    header: () => t("features.depts.column.childCount"),
    cell: ({ row }) =>
      h(
        "span",
        {
          class:
            "bg-elevated/60 text-default inline-flex items-center rounded-md px-1.5 py-0.5 text-xs font-medium",
        },
        String(row.original.children.length),
      ),
  },
  {
    id: "status",
    enableSorting: false,
    header: () => t("features.depts.column.status"),
    cell: ({ row }) =>
      h(
        "span",
        {
          class: `inline-flex items-center rounded-md px-1.5 py-0.5 text-xs font-medium ${
            row.original.status === "enabled"
              ? "bg-success/10 text-success"
              : "bg-error/10 text-error"
          }`,
        },
        t(
          row.original.status === "enabled"
            ? "features.depts.status.enabled"
            : "features.depts.status.disabled",
        ),
      ),
  },
  {
    id: "actions",
    enableSorting: false,
    enableHiding: false,
    header: () => t("common.actions"),
    cell: ({ row }) => {
      if (!canAdd.value && !canEdit.value && !canDelete.value) return null;

      const items: Array<{
        key: string;
        label: string;
        icon: string;
        color?: "error";
        onSelect: () => void;
      }> = [];

      if (canAdd.value) {
        items.push({
          key: "add",
          label: t("features.depts.action.add"),
          icon: "i-lucide-plus",
          onSelect: () => openCreateChild(row.original),
        });
      }
      if (canEdit.value) {
        items.push({
          key: "edit",
          label: t("common.edit"),
          icon: "i-lucide-pencil",
          onSelect: () => openEdit(row.original),
        });
      }
      if (canDelete.value) {
        items.push({
          key: "delete",
          label: t("common.delete"),
          icon: "i-lucide-trash-2",
          color: "error",
          onSelect: () => openDelete(row.original),
        });
      }

      return h(
        UDropdownMenu,
        { items: [items], content: { align: "center" } },
        () =>
          h(UButton, {
            "aria-label": t("common.actions"),
            color: "neutral",
            icon: "i-lucide-ellipsis",
            size: "sm",
            variant: "ghost",
          }),
      );
    },
  },
]);

const table: AppTable<DeptTreeNode> = useTable({
  get data() {
    return childNodes.value;
  },
  get columns() {
    return columns.value;
  },
  features: appTableFeatures,
  getRowId: (row: DeptTreeNode) => row.id,
  // 全量展示：子组织列表随树派生，不渲染分页条
  manualPagination: true,
});

const deleteDescription = computed(() =>
  t("features.depts.message.deleteDesc", {
    name: deleteTarget.value?.name ?? "",
  }),
);
</script>

<template>
  <div class="flex w-full flex-col pb-8">
    <div
      class="grid grid-cols-1 items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)]"
    >
      <!-- 左栏：组织树面板（与人员通讯录共用） -->
      <DeptTreePanel
        :can-reorder="canEdit && !reorderMutation.isPending.value"
        :is-fetching="treeQuery.isFetching.value"
        :is-loading="treeQuery.isLoading.value"
        :nodes="tree"
        :selected-id="selectedNode?.id ?? null"
        :empty-title="t('features.depts.tree.empty')"
        @reorder="handleReorder"
        @select="(node) => (selectedId = node.id)"
      >
        <template v-if="canAdd" #header-action>
          <UButton
            :aria-label="t('features.depts.action.addRoot')"
            class="p-1"
            color="neutral"
            icon="i-lucide-plus"
            size="sm"
            variant="outline"
            @click="openCreateRoot"
          />
        </template>
        <template v-if="canAdd" #empty-action>
          <UButton
            color="neutral"
            icon="i-lucide-plus"
            size="sm"
            variant="outline"
            @click="openCreateRoot"
          >
            {{ t("features.depts.action.addRoot") }}
          </UButton>
        </template>
      </DeptTreePanel>

      <!-- 右栏：选中组织详情 + 子组织列表 -->
      <div class="flex min-w-0 flex-col gap-6">
        <UCard class="flex flex-col gap-3 rounded-3xl p-4" variant="outline">
          <template v-if="selectedNode">
            <div class="flex flex-wrap items-center justify-between gap-2">
              <div class="flex min-w-0 items-center gap-2">
                <span class="truncate text-sm font-semibold">
                  {{ selectedNode.name }}
                </span>
                <span
                  :class="
                    selectedNode.status === 'enabled'
                      ? 'bg-success/10 text-success'
                      : 'bg-error/10 text-error'
                  "
                  class="inline-flex items-center rounded-md px-1.5 py-0.5 text-xs font-medium"
                >
                  {{
                    t(
                      selectedNode.status === "enabled"
                        ? "features.depts.status.enabled"
                        : "features.depts.status.disabled",
                    )
                  }}
                </span>
              </div>
              <!-- 允许换行：窄屏/长名称时按钮折行右对齐，不挤压左侧标题区 -->
              <div class="flex flex-wrap items-center justify-end gap-2">
                <UButton
                  v-if="canAdd"
                  size="sm"
                  @click="openCreateChild(selectedNode)"
                >
                  <UIcon class="size-4" name="i-lucide-plus" />
                  {{ t("features.depts.action.add") }}
                </UButton>
                <UButton
                  v-if="canEdit"
                  color="neutral"
                  size="sm"
                  variant="subtle"
                  @click="openEdit(selectedNode)"
                >
                  <UIcon class="size-4" name="i-lucide-pencil" />
                  {{ t("common.edit") }}
                </UButton>
                <UButton
                  v-if="canDelete"
                  color="error"
                  size="sm"
                  variant="subtle"
                  @click="openDelete(selectedNode)"
                >
                  <UIcon class="size-4" name="i-lucide-trash-2" />
                  {{ t("common.delete") }}
                </UButton>
              </div>
            </div>
            <div class="text-muted flex flex-wrap gap-x-6 gap-y-1 text-sm">
              <span>
                {{ t("features.depts.column.code") }}：
                <span class="font-mono">{{ selectedNode.code ?? "—" }}</span>
              </span>
              <span>
                {{ t("features.depts.column.leader") }}：
                {{ selectedNode.leaderName ?? "—" }}
              </span>
              <span>
                {{
                  t("features.depts.detail.childCount", {
                    count: selectedNode.children.length,
                  })
                }}
              </span>
            </div>
          </template>
          <div
            v-else
            class="text-muted flex flex-col items-center justify-center gap-2 py-10"
          >
            <p class="text-sm">{{ t("features.depts.detail.unselected") }}</p>
          </div>
        </UCard>

        <!-- 子组织列表（与详情卡留出呼吸间距，页面底部有 pb-8） -->
        <div class="flex min-w-0 flex-col">
          <DataTable
            :loading="treeQuery.isLoading.value"
            :min-width="'640px'"
            :table="table"
          />
        </div>
      </div>
    </div>

    <!-- 弹窗集合 -->
    <DeptFormDialog
      v-model:open="formOpen"
      :dept="formDept"
      :mode="formMode"
      :parent-node="formParentNode"
      :tree="tree"
      @saved="invalidateTree"
    />

    <ConfirmDialog
      v-model:open="deleteOpen"
      :confirm-keyword="deleteTarget?.name"
      :confirm-text="t('common.delete')"
      :description="deleteDescription"
      :keyword-label="t('features.depts.message.deleteKeyword')"
      :title="t('features.depts.message.deleteTitle')"
      destructive
      @confirm="handleDeleteConfirm"
    />
  </div>
</template>
