// next/src/features/org/directory-page.tsx
"use client";

import type { DirectoryEntry } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/common/data-table/table-types";
import type { DirectoryListParams } from "./directory-api";

import { useQuery } from "@tanstack/react-query";
import { Button, Chip, SearchField, toast, Typography } from "@heroui/react";
import { useTable } from "@tanstack/react-table";
import { Download, FilterX } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";

import { DEPTS_TREE_QUERY_KEY, fetchDeptTree } from "./dept-api";
import {
  DIRECTORY_EXPORT_MAX_ROWS,
  DirectoryExportLimitError,
  exportDirectoryExcel,
} from "./directory-export";
import { DeptTreePanel } from "./dept-tree-panel";

import { DataTable } from "@/components/common/data-table";
import {
  DataTableFilterSelect,
  DataTablePagination,
  DataTableSearchReset,
  DataTableToolbar,
  buildColumnSettingKey,
} from "@/components/common/data-table";
import { appTableFeatures } from "@/components/common/data-table/table-types";
import { ErrorContent } from "@/components/common/error-content/error-content";
import { UserInfo } from "@/components/common/user-info/user-info";
import { createListStore } from "@/hooks/create-list-store";
import { useListQuery } from "@/hooks/use-list-query";
import { useTranslation } from "@/i18n";
import { useMenuPermissions } from "@/hooks/use-permissions";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 人员通讯录页（契约 v1.6.0 阶段 2）：左树右表布局。
 *
 * - 左栏组织树点击即筛选（该组织及全部下级组织的人员，递归），
 *   再次进入「全部人员」清除组织筛选；
 * - 在职状态缺省 employed（离职人员默认不展示，PRD 3.3.5）；
 *   可显式筛选离职 / 全部；
 * - 数据源为服务端分页联查（users × depts × user_posts × posts），实时无缓存。
 */

/** 列表 store（模块级单例：保活实例复用同一份分页/筛选状态） */
const useDirectoryListStore = createListStore<{
  deptId: string | null;
  employmentStatus: string | null;
}>({
  deptId: null,
  // 默认「在职」（PRD 3.3.5 离职人员默认不展示）；「全部」(null) 映射后端 all
  employmentStatus: "employed",
});

export function DirectoryPage() {
  const { t } = useTranslation();
  // 导出为敏感操作（批量数据外带）：按 EXPORT 位门控（v1.7.1，仅通讯录菜单声明）
  const { canExport } = useMenuPermissions();
  const userId = useAuthStore((state) => state.user?.id);

  // 组织树（左栏筛选；与组织/岗位页共享缓存）
  const treeQuery = useQuery({
    queryKey: DEPTS_TREE_QUERY_KEY,
    queryFn: fetchDeptTree,
    placeholderData: (prev) => prev,
    staleTime: 0,
  });
  const tree = useMemo(() => treeQuery.data ?? [], [treeQuery.data]);

  // ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
  const page = useDirectoryListStore((s) => s.page);
  const pageSize = useDirectoryListStore((s) => s.pageSize);
  const search = useDirectoryListStore((s) => s.search);
  const sorting = useDirectoryListStore((s) => s.sorting);
  const filters = useDirectoryListStore((s) => s.filters);
  const setPage = useDirectoryListStore((s) => s.setPage);
  const setPageSize = useDirectoryListStore((s) => s.setPageSize);
  const setSorting = useDirectoryListStore((s) => s.setSorting);
  const setFilters = useDirectoryListStore((s) => s.setFilters);
  const resetStore = useDirectoryListStore((s) => s.reset);

  const {
    data,
    pagination,
    isLoading,
    isFetching,
    isError,
    refetch,
    submitSearch,
  } = useListQuery<
    DirectoryEntry,
    { deptId: string | null; employmentStatus: string | null }
  >({
    store: useDirectoryListStore,
    queryKeyPrefix: ["org", "directory", "list"],
    path: "/org/directory",
    // 后端搜索参数名为 keyword（/org/* 统一命名）
    searchParam: "keyword",
    buildFilters: (f) => ({
      ...(f.deptId ? { deptId: f.deptId } : {}),
      // FilterSelect 首项「全部」(null) 映射后端 all；store 默认 employed
      employmentStatus: f.employmentStatus ?? "all",
    }),
  });

  // 搜索（提交式后端过滤：姓名 / 工号 / 登录名）；
  // 条件未变化时 submitSearch 走 refetch，搜索按钮即「刷新列表」入口
  const [searchInput, setSearchInput] = useState(search);
  const applySearch = useCallback(
    () => submitSearch(searchInput.trim()),
    [submitSearch, searchInput],
  );
  const searchDirty = searchInput.trim() !== search;

  const resetFilters = useCallback(() => {
    setSearchInput("");
    resetStore();
  }, [resetStore]);

  // ---------------- 组织筛选与 URL Query 双向同步 ----------------
  // 架构图谱节点点击跳转 /org/directory?deptId=xxx 的落点（阶段 4 交互规范）：
  // 刷新 / 分享 / 前进后退均恢复筛选。
  const urlDeptId = useSearchParams().get("deptId");
  const pathname = usePathname();
  // 用原生 router.replace 同步地址栏（避免 bprogress 进度条在页内筛选时闪烁）
  const nativeRouter = useRouter();

  // URL → 列表 store（getState 比较后 setFilters，防手动回写 URL 触发 effect 空转）
  useEffect(() => {
    const current = useDirectoryListStore.getState().filters.deptId;

    if (current !== urlDeptId) {
      setFilters({ deptId: urlDeptId });
    }
  }, [urlDeptId, setFilters]);

  // store → URL（树点击 / 清除时 replace 地址栏，不塞历史记录）
  const syncDeptIdToUrl = useCallback(
    (deptId: string | null) => {
      nativeRouter.replace(
        deptId ? `${pathname}?deptId=${encodeURIComponent(deptId)}` : pathname,
      );
    },
    [nativeRouter, pathname],
  );

  // ---------------- 导出 Excel（write-excel-file 触发时动态加载） ----------------
  const [isExporting, setIsExporting] = useState(false);
  const handleExport = useCallback(() => {
    if (isExporting) {
      return;
    }
    setIsExporting(true);
    const sortField = sorting[0]?.id;
    const task = exportDirectoryExcel({
      params: {
        keyword: search || undefined,
        deptId: filters.deptId ?? undefined,
        employmentStatus: (filters.employmentStatus ??
          "all") as DirectoryListParams["employmentStatus"],
        ...(sortField
          ? {
              sort: sortField,
              order: sorting[0].desc ? ("desc" as const) : ("asc" as const),
            }
          : {}),
      },
      t,
    });

    toast.promise(task, {
      error: (error: unknown) =>
        error instanceof DirectoryExportLimitError
          ? t("features.directory.export.limitExceeded", {
              max: DIRECTORY_EXPORT_MAX_ROWS,
            })
          : error instanceof Error
            ? error.message
            : String(error),
      loading: t("features.directory.export.loading"),
      success: (count: number) =>
        t("features.directory.export.success", { count }),
    });
    void task.finally(() => setIsExporting(false));
  }, [isExporting, sorting, search, filters, t]);

  const employmentOptions = useMemo(
    () => [
      // FilterSelect 自带头项「全部」（null → 后端 all），选项只给两个具体状态
      { value: "employed", label: t("features.directory.filter.employed") },
      { value: "resigned", label: t("features.directory.filter.resigned") },
    ],
    [t],
  );

  const columns = useMemo<AppColumnDef<DirectoryEntry>[]>(
    () => [
      {
        id: "displayName",
        enableSorting: true,
        header: t("features.directory.column.name"),
        cell: ({ row }) => <UserInfo subtitle="username" user={row.original} />,
      },
      {
        id: "employeeNo",
        enableSorting: true,
        header: t("features.directory.column.employeeNo"),
        cell: ({ row }) => (
          <Typography className="font-mono" type="body-sm">
            {row.original.employeeNo ?? "—"}
          </Typography>
        ),
      },
      {
        id: "deptPath",
        enableSorting: false,
        header: t("features.directory.column.dept"),
        cell: ({ row }) => (
          <Typography type="body-sm">{row.original.deptPath ?? "—"}</Typography>
        ),
      },
      {
        id: "mainPostName",
        enableSorting: false,
        header: t("features.directory.column.mainPost"),
        cell: ({ row }) => (
          <Typography type="body-sm">
            {row.original.mainPostName ?? "—"}
          </Typography>
        ),
      },
      {
        id: "phone",
        enableSorting: false,
        header: t("features.directory.column.phone"),
        cell: ({ row }) => (
          <Typography type="body-sm">{row.original.phone ?? "—"}</Typography>
        ),
      },
      {
        id: "email",
        enableSorting: false,
        header: t("features.directory.column.email"),
        cell: ({ row }) => (
          <Typography type="body-sm">{row.original.email ?? "—"}</Typography>
        ),
      },
      {
        id: "entryDate",
        enableSorting: true,
        header: t("features.directory.column.entryDate"),
        cell: ({ row }) => (
          <Typography type="body-sm">
            {row.original.entryDate ?? "—"}
          </Typography>
        ),
      },
      {
        id: "employmentStatus",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.directory.column.status"),
        cell: ({ row }) => (
          <Chip
            color={
              row.original.employmentStatus === "employed"
                ? "success"
                : "danger"
            }
            size="sm"
            variant="soft"
          >
            {t(
              row.original.employmentStatus === "employed"
                ? "features.directory.filter.employed"
                : "features.directory.filter.resigned",
            )}
          </Chip>
        ),
      },
    ],
    [t],
  );

  const total = pagination?.total ?? 0;

  const table = useTable({
    columns,
    data: data ?? [],
    features: appTableFeatures,
    getRowId: (row) => row.id,
    // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
    manualPagination: true,
    manualSorting: true,
    pageCount: Math.max(1, Math.ceil(total / pageSize)),
    state: {
      pagination: { pageIndex: page - 1, pageSize },
      sorting,
    },
    onPaginationChange: (updater) => {
      const next =
        typeof updater === "function"
          ? updater({ pageIndex: page - 1, pageSize })
          : updater;

      if (next.pageSize !== pageSize) {
        setPageSize(next.pageSize);
      } else {
        setPage(next.pageIndex + 1);
      }
    },
    onSortingChange: (updater) => {
      setSorting(typeof updater === "function" ? updater(sorting) : updater);
    },
  });

  return (
    <div className="flex w-full flex-col pb-8">
      <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)]">
        {/* 左栏：组织树面板（与组织管理共用 DeptTreePanel；树点击即筛选组织及下级） */}
        <DeptTreePanel
          emptyTitle={t("features.depts.tree.empty")}
          headerAction={
            filters.deptId ? (
              <Button
                isIconOnly
                aria-label={t("features.directory.filter.showAll")}
                size="sm"
                variant="ghost"
                onPress={() => setFilters({ deptId: null })}
              >
                <FilterX className="size-4" />
              </Button>
            ) : undefined
          }
          isLoading={treeQuery.isLoading}
          nodes={tree}
          selectedId={filters.deptId}
          onSelect={(node) => {
            setFilters({ deptId: node.id });
            syncDeptIdToUrl(node.id);
          }}
        />

        {/* 右栏：人员列表 */}
        <div className="flex min-w-0 flex-col">
          <DataTableToolbar
            columnSettingKey={
              userId
                ? buildColumnSettingKey(userId, "/org/directory")
                : undefined
            }
            table={table}
          >
            <SearchField
              aria-label={t("features.directory.search.placeholder")}
              className="w-56"
              value={searchInput}
              variant="secondary"
              onChange={setSearchInput}
              onSubmit={applySearch}
            >
              <SearchField.Group>
                <SearchField.SearchIcon />
                <SearchField.Input
                  placeholder={t("features.directory.search.placeholder")}
                />
                <SearchField.ClearButton />
              </SearchField.Group>
            </SearchField>
            <DataTableFilterSelect
              aria-label={t("features.directory.filter.employment")}
              options={employmentOptions}
              value={filters.employmentStatus}
              onChange={(value) =>
                setFilters({ employmentStatus: value ?? null })
              }
            />
            <DataTableSearchReset
              canReset={
                searchDirty ||
                search !== "" ||
                Boolean(filters.deptId) ||
                filters.employmentStatus !== "employed"
              }
              isFetching={isFetching}
              onReset={resetFilters}
              onSearch={applySearch}
            />
            {canExport && (
              <Button
                isPending={isExporting}
                size="sm"
                variant="outline"
                onPress={handleExport}
              >
                <Download aria-hidden className="size-4" />
                {t("features.directory.export.button")}
              </Button>
            )}
          </DataTableToolbar>

          {isError ? (
            <ErrorContent
              action={
                <Button
                  size="sm"
                  variant="secondary"
                  onPress={() => void refetch()}
                >
                  {t("common.retry")}
                </Button>
              }
              title={t("common.loadError")}
            />
          ) : (
            <DataTable
              aria-label={t("menu.pageTitle.directory")}
              className="w-full"
              contentClassName="min-w-[900px]"
              isLoading={isLoading || isFetching}
              table={table}
            />
          )}
          <DataTablePagination table={table} total={total} />
        </div>
      </div>
    </div>
  );
}

// vue/src/features/org/DirectoryPage.vue
<script setup lang="ts">
import type { DirectoryEntry } from "@/lib/api-types";
import type { DirectoryListParams } from "./directory-api";
import type {
  AppColumnDef,
  AppTable,
} from "@/components/data-table/table-types";

import { computed, h, ref, resolveComponent, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useRoute, useRouter } from "vue-router";
import { useQuery } from "@tanstack/vue-query";
import { keepPreviousData } from "@tanstack/vue-query";
import { useVueTable } from "@tanstack/vue-table";
import { getCoreRowModel, getSortedRowModel } from "@tanstack/vue-table";
import { useToast } from "@nuxt/ui/composables";

import { DEPTS_TREE_QUERY_KEY, fetchDeptTree } from "./dept-api";
import {
  DIRECTORY_EXPORT_MAX_ROWS,
  DirectoryExportLimitError,
  exportDirectoryExcel,
} from "./directory-export";
import { DIRECTORY_QUERY_KEY } from "./directory-api";
import DeptTreePanel from "./DeptTreePanel.vue";

import ErrorContent from "@/components/common/ErrorContent.vue";
import UserInfo from "@/components/common/UserInfo.vue";
import Spinner from "@/components/ui/spinner/index.vue";
import DataTable from "@/components/data-table/DataTable.vue";
import DataTablePagination from "@/components/data-table/DataTablePagination.vue";
import DataTableSearchReset from "@/components/data-table/DataTableSearchReset.vue";
import DataTableToolbar from "@/components/data-table/DataTableToolbar.vue";
import { useMenuPermissions } from "@/composables/use-permissions";
import { useListQuery } from "@/composables/use-list-query";
import { createListStore } from "@/lib/list-store";

const UBadge = resolveComponent("UBadge");

/**
 * 人员通讯录页（契约 v1.6.0 阶段 2，对应 React 端 directory-page.tsx）：
 * 左树右表布局。
 *
 * - 左栏组织树点击即筛选（该组织及全部下级组织的人员，递归），
 *   再次点击「全部人员」清除组织筛选；
 * - 组织筛选与 URL Query 双向同步（/org/directory?deptId=xxx）：
 *   架构图谱节点点击跳转的落点，刷新 / 分享 / 前进后退稳定；
 *   防循环口径：URL → store 用「当前值不同才 set」（setFilters 同值幂等兜底），
 *   store → URL 用 router.replace（不塞历史记录）；
 * - 在职状态缺省 employed（离职人员默认不展示，PRD 3.3.5）；
 * - 工具栏支持导出当前筛选结果为 Excel（EXPORT 位门控，见 directory-export.ts）。
 */

/** 列表 store（模块级单例：导航返回复用同一份分页/筛选状态） */
const directoryListStore = createListStore<{
  deptId: string | null;
  employmentStatus: string | null;
}>({
  deptId: null,
  // 默认「在职」（离职人员默认不展示）；「全部」(null) 映射后端 all
  employmentStatus: "employed",
});

const { t } = useI18n();
const toast = useToast();
const route = useRoute();
const router = useRouter();
const { canExport } = useMenuPermissions();

const store = directoryListStore;

// 组织树（左栏筛选；与组织/岗位页共享缓存）
const treeQuery = useQuery({
  queryKey: DEPTS_TREE_QUERY_KEY,
  queryFn: fetchDeptTree,
  placeholderData: keepPreviousData,
  staleTime: 0,
});
const tree = computed(() => treeQuery.data.value ?? []);

// ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
const {
  data,
  pagination,
  isLoading,
  isFetching,
  isError,
  refetch,
  submitSearch,
} = useListQuery<
  DirectoryEntry,
  {
    deptId: string | null;
    employmentStatus: string | null;
  }
>({
  store,
  queryKeyPrefix: DIRECTORY_QUERY_KEY,
  path: "/org/directory",
  // 后端搜索参数名为 keyword（/org/* 统一命名）
  searchParam: "keyword",
  buildFilters: (f) => ({
    ...(f.deptId ? { deptId: f.deptId } : {}),
    // 「全部」(null) 映射后端 all；store 默认 employed
    employmentStatus: f.employmentStatus ?? "all",
  }),
});

// 搜索（提交式后端过滤：姓名 / 工号 / 登录名）；条件未变化时 submitSearch
// 走 refetch，搜索按钮即「刷新列表」入口
const searchInput = ref(store.search);

function applySearch() {
  submitSearch(searchInput.value.trim());
}

const searchDirty = computed(() => searchInput.value.trim() !== store.search);

// URL Query → 列表 store（图谱跳转 / 刷新 / 前进后退恢复组织筛选）
const urlDeptId = computed<string | null>(() => {
  const value = route.query.deptId;

  return typeof value === "string" && value !== "" ? value : null;
});

watch(
  urlDeptId,
  (value) => {
    if (store.filters.deptId !== value) {
      store.setFilters({ deptId: value });
    }
  },
  { immediate: true },
);

// store → URL（页内树点击 / 清除时同步地址栏，保证分享与刷新一致；
// replace 避免每次点击都塞历史记录）
function syncDeptIdToUrl(deptId: string | null) {
  void router.replace({ query: { deptId: deptId ?? undefined } });
}

function selectDept(node: { id: string }) {
  store.setFilters({ deptId: node.id });
  syncDeptIdToUrl(node.id);
}

function clearDeptFilter() {
  store.setFilters({ deptId: null });
  syncDeptIdToUrl(null);
}

function resetFilters() {
  searchInput.value = "";
  store.reset();
  syncDeptIdToUrl(null);
}

// ---------------- 导出 Excel（write-excel-file 触发时动态加载） ----------------
const isExporting = ref(false);

async function handleExport() {
  if (isExporting.value) return;

  isExporting.value = true;

  // toast.promise 三段式（对齐既有 toast.update 形态）
  const exportingToast = toast.add({
    title: t("features.directory.export.loading"),
    icon: h(Spinner, { size: "sm", class: "mt-0.5" }),
    color: "info",
    duration: 0,
  });

  const sortField = store.sorting[0]?.id;

  try {
    const count = await exportDirectoryExcel({
      params: {
        ...(store.search ? { keyword: store.search } : {}),
        ...(store.filters.deptId ? { deptId: store.filters.deptId } : {}),
        employmentStatus: (store.filters.employmentStatus ??
          "all") as DirectoryListParams["employmentStatus"],
        ...(sortField
          ? {
              sort: sortField,
              order: store.sorting[0].desc ? "desc" : "asc",
            }
          : {}),
      },
      t,
    });

    toast.update(exportingToast.id, {
      title: t("features.directory.export.success", { count }),
      icon: "i-lucide-check",
      color: "success",
    });
  } catch (error) {
    toast.update(exportingToast.id, {
      title:
        error instanceof DirectoryExportLimitError
          ? t("features.directory.export.limitExceeded", {
              max: DIRECTORY_EXPORT_MAX_ROWS,
            })
          : error instanceof Error
            ? error.message
            : String(error),
      icon: "i-lucide-x",
      color: "error",
    });
  } finally {
    isExporting.value = false;
  }
}

const employmentOptions = computed(() => [
  // 「全部」由 placeholder 承担（null → 后端 all），选项只给两个具体状态
  { label: t("features.directory.filter.employed"), value: "employed" },
  { label: t("features.directory.filter.resigned"), value: "resigned" },
]);

const canReset = computed(
  () =>
    searchDirty.value ||
    store.search !== "" ||
    Boolean(store.filters.deptId) ||
    store.filters.employmentStatus !== "employed",
);

// ---------------- 表格（TanStack vue-table，服务端分页/排序受控） ----------------
const columns = computed<AppColumnDef<DirectoryEntry>[]>(() => [
  {
    id: "displayName",
    enableSorting: true,
    header: () => t("features.directory.column.name"),
    cell: ({ row }) => h(UserInfo, { user: row.original }),
  },
  {
    id: "employeeNo",
    enableSorting: true,
    header: () => t("features.directory.column.employeeNo"),
    cell: ({ row }) =>
      h("span", { class: "font-mono text-sm" }, row.original.employeeNo ?? "—"),
  },
  {
    id: "deptPath",
    enableSorting: false,
    header: () => t("features.directory.column.dept"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.deptPath ?? "—"),
  },
  {
    id: "mainPostName",
    enableSorting: false,
    header: () => t("features.directory.column.mainPost"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.mainPostName ?? "—"),
  },
  {
    id: "phone",
    enableSorting: false,
    header: () => t("features.directory.column.phone"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.phone ?? "—"),
  },
  {
    id: "email",
    enableSorting: false,
    header: () => t("features.directory.column.email"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.email ?? "—"),
  },
  {
    id: "entryDate",
    enableSorting: true,
    header: () => t("features.directory.column.entryDate"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.entryDate ?? "—"),
  },
  {
    id: "employmentStatus",
    enableSorting: false,
    header: () => t("features.directory.column.status"),
    cell: ({ row }) =>
      h(UBadge, {
        color:
          row.original.employmentStatus === "employed" ? "success" : "error",
        label: t(
          row.original.employmentStatus === "employed"
            ? "features.directory.filter.employed"
            : "features.directory.filter.resigned",
        ),
        variant: "soft",
      }),
  },
]);

const table: AppTable<DirectoryEntry> = useVueTable({
  get data() {
    return data.value;
  },
  get columns() {
    return columns.value;
  },
  getCoreRowModel: getCoreRowModel(),
  getSortedRowModel: getSortedRowModel(),
  getRowId: (row: DirectoryEntry) => row.id,
  // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
  manualPagination: true,
  manualSorting: true,
  // pageCount 必须用 getter 实时求值（写死会导致翻页被 clamp）
  get pageCount() {
    return Math.max(1, Math.ceil(pagination.value.total / store.pageSize));
  },
  state: {
    get pagination() {
      return { pageIndex: store.page - 1, pageSize: store.pageSize };
    },
    get sorting() {
      return store.sorting;
    },
  },
  onPaginationChange: (updater) => {
    const next =
      typeof updater === "function"
        ? updater({ pageIndex: store.page - 1, pageSize: store.pageSize })
        : updater;

    if (next.pageSize !== store.pageSize) {
      store.setPageSize(next.pageSize);
    } else {
      store.setPage(next.pageIndex + 1);
    }
  },
  onSortingChange: (updater) => {
    const next =
      typeof updater === "function" ? updater(store.sorting) : updater;

    store.setSorting(next);
  },
});
</script>

<script lang="ts">
export default { name: "DirectoryPage" };
</script>

<template>
  <div class="flex w-full flex-col">
    <div
      class="grid grid-cols-1 items-start gap-4 lg:grid-cols-[300px_minmax(0,1fr)]"
    >
      <!-- 左栏：组织树面板（与组织管理共用；树点击即筛选组织及下级） -->
      <DeptTreePanel
        :empty-title="t('features.depts.tree.empty')"
        :is-loading="treeQuery.isLoading.value"
        :is-fetching="treeQuery.isFetching.value"
        :nodes="tree"
        :selected-id="store.filters.deptId"
        @select="selectDept"
      >
        <template v-if="store.filters.deptId" #header-action>
          <UButton
            :aria-label="t('features.directory.filter.showAll')"
            class="p-1"
            color="neutral"
            icon="i-lucide-filter-x"
            size="sm"
            variant="ghost"
            @click="clearDeptFilter"
          />
        </template>
      </DeptTreePanel>

      <!-- 右栏：人员列表 -->
      <div class="flex min-w-0 flex-col gap-4">
        <DataTableToolbar>
          <UInput
            v-model="searchInput"
            :aria-label="t('features.directory.search.placeholder')"
            :placeholder="t('features.directory.search.placeholder')"
            class="w-56"
            icon="i-lucide-search"
            @keyup.enter="applySearch"
          />
          <USelectMenu
            :aria-label="t('features.directory.filter.employment')"
            :items="employmentOptions"
            :model-value="store.filters.employmentStatus ?? undefined"
            :placeholder="t('features.directory.column.status')"
            class="w-36"
            value-key="value"
            clear
            :search-input="false"
            @update:model-value="
              (value: unknown) =>
                store.setFilters({
                  employmentStatus: value ? String(value) : null,
                })
            "
          />
          <DataTableSearchReset
            :can-reset="canReset"
            :fetching="isFetching"
            @reset="resetFilters"
            @search="applySearch"
          />
          <UButton
            v-if="canExport"
            :label="t('features.directory.export.button')"
            :loading="isExporting"
            icon="i-lucide-download"
            variant="outline"
            @click="handleExport"
          />
        </DataTableToolbar>

        <ErrorContent
          v-if="isError"
          :retry-label="t('common.retry')"
          :title="t('common.loadError')"
          @retry="refetch()"
        />
        <DataTable
          v-else
          :loading="isLoading"
          :refreshing="isFetching && !isLoading"
          :table="table"
        />

        <DataTablePagination
          :page-index="store.page - 1"
          :page-size="store.pageSize"
          :table="table"
          :total="pagination.total"
        />
      </div>
    </div>
  </div>
</template>
