// react/src/features/org/posts-page.tsx
import type { Post } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/common/data-table/table-types";
import type { PostFormMode } from "./post-form-dialog";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Button,
  Chip,
  Dropdown,
  Label,
  SearchField,
  Typography,
  toast,
  useOverlayState,
} from "@heroui/react";
import { useTable } from "@tanstack/react-table";
import { MoreHorizontal, Pencil, Plus, Trash2 } from "lucide-react";
import { useCallback, useMemo, useState } from "react";

import { deletePost, getPostErrorMessage } from "./post-api";
import { PostFormDialog } from "./post-form-dialog";
import { PostMembersDrawer } from "./post-members-drawer";
import { DeptTreeSelect } from "./dept-tree-select";
import { DEPTS_TREE_QUERY_KEY, fetchDeptTree } from "./dept-api";

import { ConfirmDialog } from "@/components/common/confirm-dialog/confirm-dialog";
import { DataTable } from "@/components/common/data-table";
import { ErrorContent } from "@/components/common/error-content/error-content";
import {
  DataTableFilterSelect,
  DataTablePagination,
  DataTableSearchReset,
  DataTableToolbar,
  buildColumnSettingKey,
} from "@/components/common/data-table";
import { appTableFeatures } from "@/components/common/data-table/table-types";
import { createListStore } from "@/hooks/create-list-store";
import { useListQuery } from "@/hooks/use-list-query";
import { useMenuPermissions } from "@/hooks/use-permissions";
import { useTranslation } from "@/i18n";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 岗位管理页（契约 v1.6.0 阶段 2）：筛选区 + 服务端分页表格。
 *
 * - 筛选：所属组织（DeptTreeSelect，含下级组织的岗位）+ 关键词 + 类别 + 状态；
 * - 列表状态入 feature store（keepAlive 友好），由 useListQuery 装配；
 * - 组织树复用 GET /org/depts/tree 查询缓存（与组织管理页同 key）；
 * - 「在职人数」列点击打开成员穿透抽屉；删除由后端在职校验 409 拦截。
 */

/** 列表 store（模块级单例：保活实例复用同一份分页/筛选状态） */
const usePostsListStore = createListStore<{
  deptId: string | null;
  category: string | null;
  status: string | null;
}>({
  deptId: null,
  category: null,
  status: null,
});

export function PostsPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const userId = useAuthStore((state) => state.user?.id);
  const { canAdd, canEdit, canDelete } = useMenuPermissions();

  // 组织树（所属组织筛选与表单共用；与组织管理页共享缓存）
  const treeQuery = useQuery({
    queryKey: DEPTS_TREE_QUERY_KEY,
    queryFn: fetchDeptTree,
    placeholderData: (prev) => prev,
    staleTime: 0,
  });
  const tree = useMemo(() => treeQuery.data ?? [], [treeQuery.data]);

  // ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
  const page = usePostsListStore((s) => s.page);
  const pageSize = usePostsListStore((s) => s.pageSize);
  const search = usePostsListStore((s) => s.search);
  const sorting = usePostsListStore((s) => s.sorting);
  const filters = usePostsListStore((s) => s.filters);
  const setSearch = usePostsListStore((s) => s.setSearch);
  const setPage = usePostsListStore((s) => s.setPage);
  const setPageSize = usePostsListStore((s) => s.setPageSize);
  const setSorting = usePostsListStore((s) => s.setSorting);
  const setFilters = usePostsListStore((s) => s.setFilters);
  const resetStore = usePostsListStore((s) => s.reset);

  const { data, pagination, isLoading, isFetching, isError, refetch } =
    useListQuery<
      Post,
      { deptId: string | null; category: string | null; status: string | null }
    >({
      store: usePostsListStore,
      queryKeyPrefix: ["org", "posts", "list"],
      path: "/org/posts",
      // 后端搜索参数名为 keyword（/org/* 统一命名）
      searchParam: "keyword",
      buildFilters: (f) => ({
        ...(f.deptId ? { deptId: f.deptId } : {}),
        ...(f.category ? { category: f.category } : {}),
        ...(f.status ? { status: f.status } : {}),
      }),
    });

  // 搜索（提交式后端过滤：岗位名称）
  const [searchInput, setSearchInput] = useState(search);
  const applySearch = useCallback(
    () => setSearch(searchInput.trim()),
    [setSearch, searchInput],
  );
  const searchDirty = searchInput.trim() !== search;

  const resetFilters = useCallback(() => {
    setSearchInput("");
    resetStore();
  }, [resetStore]);

  const setDeptId = useCallback(
    (deptId: string) => setFilters({ deptId: deptId || null }),
    [setFilters],
  );

  const categoryOptions = useMemo(
    () =>
      (["management", "professional", "production"] as const).map((value) => ({
        value,
        label: t(`features.posts.category.${value}`),
      })),
    [t],
  );
  const statusOptions = useMemo(
    () => [
      { value: "enabled", label: t("features.posts.status.enabled") },
      { value: "disabled", label: t("features.posts.status.disabled") },
    ],
    [t],
  );

  // ---------------- 弹窗状态（useOverlayState，§7.2 受控浮层语义） ----------------
  const formDialog = useOverlayState();
  const membersDrawer = useOverlayState();
  const deleteDialog = useOverlayState();

  const [formContext, setFormContext] = useState<{
    mode: PostFormMode;
    post: Post | null;
  }>({ mode: "create", post: null });
  const [deleteTarget, setDeleteTarget] = useState<Post | null>(null);
  const [membersTarget, setMembersTarget] = useState<Post | null>(null);

  const invalidateList = useCallback(() => {
    void queryClient.invalidateQueries({
      queryKey: ["org", "posts", "list"],
    });
    // 组织/用户侧的岗位计数与通讯录主岗随岗位变化，一并失效
    void queryClient.invalidateQueries({ queryKey: DEPTS_TREE_QUERY_KEY });
  }, [queryClient]);

  const openCreate = useCallback(() => {
    setFormContext({ mode: "create", post: null });
    formDialog.open();
  }, [formDialog]);

  const openEdit = useCallback(
    (post: Post) => {
      setFormContext({ mode: "edit", post });
      formDialog.open();
    },
    [formDialog],
  );

  const openDelete = useCallback(
    (post: Post) => {
      setDeleteTarget(post);
      deleteDialog.open();
    },
    [deleteDialog],
  );

  const openMembers = useCallback(
    (post: Post) => {
      setMembersTarget(post);
      membersDrawer.open();
    },
    [membersDrawer],
  );

  const deleteMutation = useMutation({
    mutationFn: (id: string) => deletePost(id),
    onSuccess: () => {
      invalidateList();
      toast.success(t("features.posts.message.deleted"));
    },
    onError: (error) => {
      toast.danger(getPostErrorMessage(error));
    },
  });

  const columns = useMemo<AppColumnDef<Post>[]>(
    () => [
      {
        id: "name",
        enableSorting: true,
        header: t("features.posts.column.name"),
        cell: ({ row }) => (
          <Typography className="font-medium" type="body-sm">
            {row.original.name}
          </Typography>
        ),
      },
      {
        id: "deptPath",
        enableSorting: false,
        header: t("features.posts.column.dept"),
        cell: ({ row }) => (
          <Typography type="body-sm">{row.original.deptPath || "—"}</Typography>
        ),
      },
      {
        id: "category",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.posts.column.category"),
        cell: ({ row }) => (
          <Chip size="sm" variant="soft">
            {t(`features.posts.category.${row.original.category}`)}
          </Chip>
        ),
      },
      {
        id: "rank",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.posts.column.rank"),
        cell: ({ row }) => (
          <Typography className="font-mono" type="body-sm">
            {row.original.rank || "—"}
          </Typography>
        ),
      },
      {
        id: "userCount",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.posts.column.userCount"),
        cell: ({ row }) => (
          <button
            className="rounded-2xl px-2 py-1 text-sm underline-offset-4 transition-colors hover:bg-default/60 hover:underline"
            type="button"
            onClick={() => openMembers(row.original)}
          >
            {row.original.userCount}
          </button>
        ),
      },
      {
        id: "status",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.posts.column.status"),
        cell: ({ row }) => (
          <Chip
            color={row.original.status === "enabled" ? "success" : "danger"}
            size="sm"
            variant="soft"
          >
            {t(
              row.original.status === "enabled"
                ? "features.posts.status.enabled"
                : "features.posts.status.disabled",
            )}
          </Chip>
        ),
      },
      {
        id: "actions",
        enableSorting: false,
        enableHiding: false,
        meta: { align: "center" },
        header: t("common.actions"),
        cell: ({ row }) => {
          if (!canEdit && !canDelete) return null;

          return (
            <Dropdown>
              <Button
                isIconOnly
                aria-label={t("common.actions")}
                size="sm"
                variant="ghost"
              >
                <MoreHorizontal className="size-4" />
              </Button>
              <Dropdown.Popover className="min-w-36">
                <Dropdown.Menu
                  onAction={(key) => {
                    if (key === "edit") openEdit(row.original);
                    if (key === "delete") openDelete(row.original);
                  }}
                >
                  {canEdit && (
                    <Dropdown.Item id="edit" textValue={t("common.edit")}>
                      <Pencil className="size-4 shrink-0 text-muted" />
                      <Label>{t("common.edit")}</Label>
                    </Dropdown.Item>
                  )}
                  {canDelete && (
                    <Dropdown.Item
                      id="delete"
                      textValue={t("common.delete")}
                      variant="danger"
                    >
                      <Trash2 className="size-4 shrink-0 text-danger" />
                      <Label>{t("common.delete")}</Label>
                    </Dropdown.Item>
                  )}
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown>
          );
        },
      },
    ],
    [t, canEdit, canDelete, openEdit, openDelete, openMembers],
  );

  const total = pagination?.total ?? 0;

  const table = useTable({
    columns,
    data: data ?? [],
    features: appTableFeatures,
    getRowId: (row) => row.id,
    // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
    manualPagination: true,
    manualSorting: true,
    pageCount: Math.max(1, Math.ceil(total / pageSize)),
    state: {
      pagination: { pageIndex: page - 1, pageSize },
      sorting,
    },
    onPaginationChange: (updater) => {
      const next =
        typeof updater === "function"
          ? updater({ pageIndex: page - 1, pageSize })
          : updater;

      if (next.pageSize !== pageSize) {
        setPageSize(next.pageSize);
      } else {
        setPage(next.pageIndex + 1);
      }
    },
    onSortingChange: (updater) => {
      setSorting(typeof updater === "function" ? updater(sorting) : updater);
    },
  });

  return (
    <div className="flex w-full flex-col pb-8">
      <DataTableToolbar
        columnSettingKey={
          userId ? buildColumnSettingKey(userId, "/org/posts") : undefined
        }
        table={table}
      >
        <div className="w-56">
          <DeptTreeSelect
            ariaLabel={t("features.posts.filter.dept")}
            className="w-full"
            tree={tree}
            value={filters.deptId ?? ""}
            onChange={setDeptId}
          />
        </div>
        <DataTableFilterSelect
          aria-label={t("features.posts.filter.category")}
          options={categoryOptions}
          value={filters.category}
          onChange={(value) => setFilters({ category: value ?? null })}
        />
        <DataTableFilterSelect
          aria-label={t("features.posts.filter.status")}
          options={statusOptions}
          value={filters.status}
          onChange={(value) => setFilters({ status: value ?? null })}
        />
        <SearchField
          aria-label={t("features.posts.search.placeholder")}
          className="w-56"
          value={searchInput}
          variant="secondary"
          onChange={setSearchInput}
          onSubmit={applySearch}
        >
          <SearchField.Group>
            <SearchField.SearchIcon />
            <SearchField.Input
              placeholder={t("features.posts.search.placeholder")}
            />
            <SearchField.ClearButton />
          </SearchField.Group>
        </SearchField>
        <DataTableSearchReset
          canReset={
            searchDirty ||
            search !== "" ||
            Boolean(filters.deptId) ||
            Boolean(filters.category) ||
            Boolean(filters.status)
          }
          isFetching={isFetching}
          searchDirty={searchDirty}
          onReset={resetFilters}
          onSearch={applySearch}
        />
        {canAdd && (
          <Button size="sm" variant="outline" onPress={openCreate}>
            <Plus className="size-4" />
            {t("features.posts.action.add")}
          </Button>
        )}
      </DataTableToolbar>

      {isError ? (
        <ErrorContent
          action={
            <Button
              size="sm"
              variant="secondary"
              onPress={() => void refetch()}
            >
              {t("common.retry")}
            </Button>
          }
          title={t("common.loadError")}
        />
      ) : (
        <DataTable
          aria-label={t("menu.pageTitle.posts")}
          className="w-full"
          contentClassName="min-w-[860px]"
          isLoading={isLoading || isFetching}
          table={table}
        />
      )}
      <DataTablePagination table={table} total={total} />

      <PostFormDialog
        isOpen={formDialog.isOpen}
        mode={formContext.mode}
        post={formContext.post}
        tree={tree}
        onOpenChange={formDialog.setOpen}
        onSaved={invalidateList}
      />

      <PostMembersDrawer post={membersTarget} state={membersDrawer} />

      <ConfirmDialog
        destructive
        confirmText={t("common.delete")}
        description={t("features.posts.message.deleteDesc", {
          name: deleteTarget?.name ?? "",
        })}
        isLoading={deleteMutation.isPending}
        state={{
          isOpen: deleteDialog.isOpen,
          setOpen: deleteDialog.setOpen,
          close: deleteDialog.close,
        }}
        title={t("features.posts.message.deleteTitle")}
        onConfirm={async () => {
          await deleteMutation.mutateAsync(deleteTarget!.id);
        }}
      />
    </div>
  );
}

// vue/src/features/org/PostsPage.vue
<script setup lang="ts">
import type { DeptTreeNode, Post } from "@/lib/api-types";
import type {
  AppColumnDef,
  AppTable,
} from "@/components/data-table/table-types";

import { computed, h, ref, resolveComponent } from "vue";
import { useI18n } from "vue-i18n";
import { useQuery, useQueryClient } from "@tanstack/vue-query";
import { keepPreviousData } from "@tanstack/vue-query";
import { useVueTable } from "@tanstack/vue-table";
import { getCoreRowModel, getSortedRowModel } from "@tanstack/vue-table";
import { useToast } from "@nuxt/ui/composables";

import { DEPTS_TREE_QUERY_KEY, fetchDeptTree } from "./dept-api";
import { POSTS_QUERY_KEY, deletePost, getPostErrorMessage } from "./post-api";
import DeptTreeSelect from "./DeptTreeSelect.vue";
import PostFormDialog from "./PostFormDialog.vue";
import PostMembersDrawer from "./PostMembersDrawer.vue";

import ConfirmDialog from "@/components/common/ConfirmDialog.vue";
import ErrorContent from "@/components/common/ErrorContent.vue";
import DataTable from "@/components/data-table/DataTable.vue";
import DataTablePagination from "@/components/data-table/DataTablePagination.vue";
import DataTableSearchReset from "@/components/data-table/DataTableSearchReset.vue";
import DataTableToolbar from "@/components/data-table/DataTableToolbar.vue";
import { useMenuPermissions } from "@/composables/use-permissions";
import { useListQuery } from "@/composables/use-list-query";
import { createListStore } from "@/lib/list-store";

const UBadge = resolveComponent("UBadge");
const UButton = resolveComponent("UButton");
const UDropdownMenu = resolveComponent("UDropdownMenu");

/**
 * 岗位管理页（契约 v1.6.0 阶段 2，对应 React 端 posts-page.tsx）：
 * 筛选区 + 服务端分页表格。
 *
 * - 筛选：所属组织（DeptTreeSelect，含下级组织的岗位）+ 关键词 + 类别 + 状态；
 * - 列表状态入 feature store（keepAlive 友好），由 useListQuery 装配；
 * - 组织树复用 GET /org/depts/tree 查询缓存（与组织管理页同 key）；
 * - 「在职人数」列点击打开成员穿透抽屉；删除由后端在职校验 409 拦截。
 */

/** 列表 store（模块级单例：导航返回复用同一份分页/筛选状态） */
const postsListStore = createListStore<{
  deptId: string | null;
  category: string | null;
  status: string | null;
}>({
  deptId: null,
  category: null,
  status: null,
});

const { t } = useI18n();
const toast = useToast();
const queryClient = useQueryClient();
const { canAdd, canEdit, canDelete } = useMenuPermissions();

const store = postsListStore;

// 组织树（所属组织筛选与表单共用；与组织管理页共享缓存）
const treeQuery = useQuery({
  queryKey: DEPTS_TREE_QUERY_KEY,
  queryFn: fetchDeptTree,
  placeholderData: keepPreviousData,
  staleTime: 0,
});
const tree = computed<DeptTreeNode[]>(() => treeQuery.data.value ?? []);

// ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
const {
  data,
  pagination,
  isLoading,
  isFetching,
  isError,
  refetch,
  submitSearch,
} = useListQuery<
  Post,
  {
    deptId: string | null;
    category: string | null;
    status: string | null;
  }
>({
  store,
  queryKeyPrefix: POSTS_QUERY_KEY,
  path: "/org/posts",
  // 后端搜索参数名为 keyword（/org/* 统一命名）
  searchParam: "keyword",
  buildFilters: (f) => ({
    ...(f.deptId ? { deptId: f.deptId } : {}),
    ...(f.category ? { category: f.category } : {}),
    ...(f.status ? { status: f.status } : {}),
  }),
});

// 搜索（提交式后端过滤：岗位名称）；条件未变化时 submitSearch 走 refetch，
// 搜索按钮即「刷新列表」入口
const searchInput = ref(store.search);

function applySearch() {
  submitSearch(searchInput.value.trim());
}

const searchDirty = computed(() => searchInput.value.trim() !== store.search);

function resetFilters() {
  searchInput.value = "";
  store.reset();
}

const categoryOptions = computed<{ label: string; value: string }[]>(() =>
  (["management", "professional", "production"] as const).map((value) => ({
    label: t(`features.posts.category.${value}`),
    value,
  })),
);
const statusOptions = computed<{ label: string; value: string }[]>(() => [
  { label: t("features.posts.status.enabled"), value: "enabled" },
  { label: t("features.posts.status.disabled"), value: "disabled" },
]);

const canReset = computed(
  () =>
    searchDirty.value ||
    store.search !== "" ||
    Boolean(store.filters.deptId) ||
    Boolean(store.filters.category) ||
    Boolean(store.filters.status),
);

// ---------------- 弹窗状态 ----------------
const formOpen = ref(false);
const formMode = ref<"create" | "edit">("create");
const formPost = ref<Post | null>(null);

const membersOpen = ref(false);
const membersTarget = ref<Post | null>(null);

const deleteOpen = ref(false);
const deleteTarget = ref<Post | null>(null);
const deleteSubmitting = ref(false);

function openForm(mode: "create" | "edit", post: Post | null) {
  formMode.value = mode;
  formPost.value = post;
  formOpen.value = true;
}

function openMembers(post: Post) {
  membersTarget.value = post;
  membersOpen.value = true;
}

/** 列表失效：岗位变化影响组织树在职/岗位计数，一并失效 */
function invalidateList() {
  void queryClient.invalidateQueries({ queryKey: POSTS_QUERY_KEY });
  void queryClient.invalidateQueries({ queryKey: DEPTS_TREE_QUERY_KEY });
}

async function confirmDelete() {
  if (!deleteTarget.value) return;

  deleteSubmitting.value = true;

  try {
    await deletePost(deleteTarget.value.id);
  } catch (error) {
    toast.add({
      color: "error",
      title: getPostErrorMessage(error),
    });

    return; // 失败保持弹窗打开（ConfirmDialog 约定）
  } finally {
    deleteSubmitting.value = false;
  }

  invalidateList();
  deleteOpen.value = false;
  toast.add({
    color: "success",
    title: t("features.posts.message.deleted"),
  });
}

// ---------------- 表格（TanStack vue-table，服务端分页/排序受控） ----------------
const columns = computed<AppColumnDef<Post>[]>(() => [
  {
    accessorKey: "name",
    enableSorting: true,
    header: () => t("features.posts.column.name"),
    cell: ({ row }) =>
      h("span", { class: "text-sm font-medium" }, row.original.name),
  },
  {
    id: "deptPath",
    enableSorting: false,
    header: () => t("features.posts.column.dept"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.deptPath || "—"),
  },
  {
    id: "category",
    enableSorting: false,
    header: () => t("features.posts.column.category"),
    cell: ({ row }) =>
      h(UBadge, {
        color: "neutral",
        label: t(`features.posts.category.${row.original.category}`),
        variant: "soft",
      }),
  },
  {
    id: "rank",
    enableSorting: false,
    header: () => t("features.posts.column.rank"),
    cell: ({ row }) =>
      h("span", { class: "font-mono text-sm" }, row.original.rank || "—"),
  },
  {
    id: "userCount",
    enableSorting: false,
    header: () => t("features.posts.column.userCount"),
    cell: ({ row }) =>
      h(
        "button",
        {
          class:
            "rounded-md px-2 py-1 text-sm underline-offset-4 transition-colors hover:bg-elevated/60 hover:underline",
          type: "button",
          onClick: () => openMembers(row.original),
        },
        String(row.original.userCount),
      ),
  },
  {
    id: "status",
    enableSorting: false,
    header: () => t("features.posts.column.status"),
    cell: ({ row }) =>
      h(UBadge, {
        color: row.original.status === "enabled" ? "success" : "error",
        label: t(
          row.original.status === "enabled"
            ? "features.posts.status.enabled"
            : "features.posts.status.disabled",
        ),
        variant: "soft",
      }),
  },
  {
    id: "actions",
    enableSorting: false,
    enableHiding: false,
    header: () => t("common.actions"),
    cell: ({ row }) => {
      if (!canEdit.value && !canDelete.value) return null;

      const items: Array<{
        key: string;
        label: string;
        icon: string;
        color?: "error";
        onSelect: () => void;
      }> = [];

      if (canEdit.value) {
        items.push({
          key: "edit",
          label: t("common.edit"),
          icon: "i-lucide-pencil",
          onSelect: () => openForm("edit", row.original),
        });
      }
      if (canDelete.value) {
        items.push({
          key: "delete",
          label: t("common.delete"),
          icon: "i-lucide-trash-2",
          color: "error",
          onSelect: () => {
            deleteTarget.value = row.original;
            deleteOpen.value = true;
          },
        });
      }

      return h(
        UDropdownMenu,
        { items: [items], content: { align: "center" } },
        () =>
          h(UButton, {
            "aria-label": t("common.actions"),
            color: "neutral",
            icon: "i-lucide-ellipsis",
            size: "sm",
            variant: "ghost",
          }),
      );
    },
  },
]);

const table: AppTable<Post> = useVueTable({
  get data() {
    return data.value;
  },
  get columns() {
    return columns.value;
  },
  getCoreRowModel: getCoreRowModel(),
  getSortedRowModel: getSortedRowModel(),
  getRowId: (row: Post) => row.id,
  // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
  manualPagination: true,
  manualSorting: true,
  // pageCount 必须用 getter 实时求值（对齐 UsersPage：写死会导致翻页被 clamp）
  get pageCount() {
    return Math.max(1, Math.ceil(pagination.value.total / store.pageSize));
  },
  state: {
    get pagination() {
      return { pageIndex: store.page - 1, pageSize: store.pageSize };
    },
    get sorting() {
      return store.sorting;
    },
  },
  onPaginationChange: (updater) => {
    const next =
      typeof updater === "function"
        ? updater({ pageIndex: store.page - 1, pageSize: store.pageSize })
        : updater;

    if (next.pageSize !== store.pageSize) {
      store.setPageSize(next.pageSize);
    } else {
      store.setPage(next.pageIndex + 1);
    }
  },
  onSortingChange: (updater) => {
    const next =
      typeof updater === "function" ? updater(store.sorting) : updater;

    store.setSorting(next);
  },
});

const deleteDescription = computed(() =>
  t("features.posts.message.deleteDesc", {
    name: deleteTarget.value?.name ?? "",
  }),
);
</script>

<script lang="ts">
export default { name: "PostsPage" };
</script>

<template>
  <div class="flex w-full flex-col gap-4">
    <DataTableToolbar>
      <div class="w-56">
        <DeptTreeSelect
          :aria-label="t('features.posts.filter.dept')"
          :model-value="store.filters.deptId ?? ''"
          :placeholder="t('features.org.deptTreeSelect.placeholder')"
          :tree="tree"
          @update:model-value="
            (key: unknown) =>
              store.setFilters({ deptId: key ? String(key) : null })
          "
        />
      </div>
      <USelectMenu
        :aria-label="t('features.posts.filter.category')"
        :items="categoryOptions"
        :model-value="store.filters.category ?? undefined"
        :placeholder="t('features.posts.column.category')"
        class="w-36"
        value-key="value"
        clear
        :search-input="false"
        @update:model-value="
          (value: unknown) =>
            store.setFilters({ category: value ? String(value) : null })
        "
      />
      <USelectMenu
        :aria-label="t('features.posts.filter.status')"
        :items="statusOptions"
        :model-value="store.filters.status ?? undefined"
        :placeholder="t('features.posts.column.status')"
        class="w-36"
        value-key="value"
        clear
        :search-input="false"
        @update:model-value="
          (value: unknown) =>
            store.setFilters({ status: value ? String(value) : null })
        "
      />
      <UInput
        v-model="searchInput"
        :aria-label="t('features.posts.search.placeholder')"
        :placeholder="t('features.posts.search.placeholder')"
        class="w-56"
        icon="i-lucide-search"
        @keyup.enter="applySearch"
      />
      <DataTableSearchReset
        :can-reset="canReset"
        :fetching="isFetching"
        @reset="resetFilters"
        @search="applySearch"
      />
      <UButton
        v-if="canAdd"
        :label="t('features.posts.action.add')"
        icon="i-lucide-plus"
        variant="outline"
        @click="openForm('create', null)"
      />
    </DataTableToolbar>

    <ErrorContent
      v-if="isError"
      :retry-label="t('common.retry')"
      :title="t('common.loadError')"
      @retry="refetch()"
    />
    <DataTable
      v-else
      :loading="isLoading"
      :refreshing="isFetching && !isLoading"
      :table="table"
    />

    <DataTablePagination
      :page-index="store.page - 1"
      :page-size="store.pageSize"
      :table="table"
      :total="pagination.total"
    />

    <PostFormDialog
      v-model:open="formOpen"
      :mode="formMode"
      :post="formPost"
      :tree="tree"
      @saved="invalidateList"
    />

    <PostMembersDrawer v-model:open="membersOpen" :post="membersTarget" />

    <ConfirmDialog
      v-model:open="deleteOpen"
      :confirm-keyword="deleteTarget?.name"
      :confirm-text="t('common.delete')"
      :description="deleteDescription"
      :keyword-label="t('features.posts.message.deleteKeyword')"
      :loading="deleteSubmitting"
      :title="t('features.posts.message.deleteTitle')"
      destructive
      @confirm="confirmDelete"
    />
  </div>
</template>
