// react/src/layouts/components/fullscreen-button.tsx
import { Button } from "@heroui/react";
import { Maximize, Minimize } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { useTranslation } from "@/i18n";

/**
 * 全屏切换按钮：点击进入 / 退出浏览器全屏。
 * 显示状态以 document.fullscreenElement 为准并监听 fullscreenchange 同步，
 * 因此 F11、Esc 等外部途径触发的全屏变化也能正确反映到图标上。
 */
export function FullscreenButton() {
  const [isFullscreen, setIsFullscreen] = useState<boolean>(
    () => document.fullscreenElement != null,
  );

  useEffect(() => {
    const sync = () => {
      setIsFullscreen(document.fullscreenElement != null);
    };

    document.addEventListener("fullscreenchange", sync);

    return () => {
      document.removeEventListener("fullscreenchange", sync);
    };
  }, []);

  const { t } = useTranslation();

  const toggleFullscreen = useCallback(() => {
    if (document.fullscreenElement) {
      void document.exitFullscreen();
    } else {
      void document.documentElement.requestFullscreen();
    }
  }, []);

  return (
    <Button
      isIconOnly
      aria-label={
        isFullscreen
          ? t("layout.fullscreen.exit")
          : t("layout.fullscreen.enter")
      }
      size="sm"
      variant="ghost"
      onPress={toggleFullscreen}
    >
      {isFullscreen ? <Minimize /> : <Maximize />}
    </Button>
  );
}

// apps/vue/src/components/layout/FullscreenButton.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { useFullscreen } from "@vueuse/core";

/**
 * 全屏切换按钮（对齐 React 端 FullscreenButton）：
 * useFullscreen 不传 target 默认作用于 document.documentElement，
 * 挂载时状态同步、fullscreenchange 监听与卸载清理均由 VueUse 托管。
 */
const { t } = useI18n();

const { isFullscreen, toggle } = useFullscreen();

const icon = computed(() =>
  isFullscreen.value ? "i-lucide-minimize" : "i-lucide-maximize",
);
const label = computed(() =>
  isFullscreen.value
    ? t("layout.fullscreen.exit")
    : t("layout.fullscreen.enter"),
);
</script>

<template>
  <UButton
    :aria-label="label"
    :icon="icon"
    color="neutral"
    variant="ghost"
    size="sm"
    @click="toggle"
  />
</template>
