// vue/src/components/data-table/DataTableBulkActions.vue
<script setup lang="ts" generic="TData extends RowData">
import type { RowData } from "@tanstack/vue-table";

import type { AppTable } from "./table-types";
import { computed, useSlots } from "vue";
import { useI18n } from "vue-i18n";
import { useEventListener } from "@vueuse/core";

/**
 * 底部浮动批量操作条（布局对齐 React 端 data-table-bulk-actions 胶囊形）：
 * 左侧 Badge 选中计数 + 中间操作插槽（分割线）+ 右侧清空按钮。
 * 进出场用 Vue 内置 Transition：底部淡入上滑 / 退场下滑淡出
 * （尊重 prefers-reduced-motion）；Esc 键清空选择。
 */
const props = defineProps<{
  table: AppTable<TData>;
}>();

const { t } = useI18n();
const slots = useSlots();

const selectedCount = computed(
  () => props.table.getSelectedRowModel().rows.length,
);
const hasActions = computed(() => !!slots.default);

function onKeydown(event: KeyboardEvent) {
  if (event.key === "Escape" && selectedCount.value > 0) {
    props.table.resetRowSelection();
  }
}

useEventListener(window, "keydown", onKeydown);
</script>

<template>
  <Transition name="bulk-actions">
    <div
      v-if="selectedCount > 0"
      class="pointer-events-none fixed inset-x-0 bottom-6 z-50 flex justify-center"
    >
      <div
        aria-live="polite"
        class="bg-default pointer-events-auto flex items-center gap-1 rounded-full py-1.5 ps-3 pe-1.5 ring ring-accented shadow-lg"
      >
        <span class="sr-only">
          {{ t("common.datatable.selected", { count: selectedCount }) }}
        </span>
        <UBadge color="neutral" variant="soft" class="mx-1 shrink-0">
          {{ selectedCount }}
        </UBadge>
        <template v-if="hasActions">
          <USeparator class="h-5 self-center" orientation="vertical" />
          <div class="flex items-center gap-1">
            <slot />
          </div>
        </template>
        <USeparator class="h-5 self-center" orientation="vertical" />
        <UButton
          :aria-label="t('common.datatable.clearSelection')"
          color="neutral"
          icon="i-lucide-x"
          size="sm"
          variant="ghost"
          @click="table.resetRowSelection()"
        />
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.bulk-actions-enter-active,
.bulk-actions-leave-active {
  transition:
    opacity 200ms ease-out,
    transform 200ms ease-out;
}

.bulk-actions-enter-from,
.bulk-actions-leave-to {
  opacity: 0;
  transform: translateY(12px);
}

@media (prefers-reduced-motion: reduce) {
  .bulk-actions-enter-active,
  .bulk-actions-leave-active {
    transition: none;
  }
}
</style>

// apps/next/src/components/common/data-table/data-table-bulk-actions.tsx
"use client";

import type { RowData } from "@tanstack/react-table";
import type { ReactNode } from "react";
import type { AppTable } from "./table-types";

import { Button, Chip, Separator, cn } from "@heroui/react";
import { useCallback, useEffect, useRef, useState } from "react";
import { X } from "lucide-react";

import { useTranslation } from "@/i18n";
import { getWindow, useEventListener } from "@/hooks/use-event-listener";

export interface DataTableBulkActionsProps<TData extends RowData> {
  table: AppTable<TData>;
  /** 选中后展示的操作按钮（如「批量删除」，由消费方做权限门控） */
  children?: ReactNode;
  className?: string;
}

/** 进/退场动画时长（ms）：与 transition-all duration-200 对齐 */
const EXIT_ANIMATION_MS = 200;

/**
 * 批量操作悬浮条（胶囊形 ActionBar）：行选中数 > 0 时固定显示在底部居中。
 * 布局对齐 HeroUI Action Bar 模式：计数徽章 | 操作插槽 | 清空按钮；
 * 进场自底部淡入上滑，退场向下淡出滑出（尊重 prefers-reduced-motion）。
 * Esc 键清空选择。
 */
export function DataTableBulkActions<TData extends RowData>({
  table,
  children,
  className,
}: DataTableBulkActionsProps<TData>) {
  const { t } = useTranslation();
  const selectedCount = table.getSelectedRowModel().rows.length;
  /** mounted：延长退场动画期的渲染；visible：驱动过渡类切换 */
  const [mounted, setMounted] = useState(false);
  const [visible, setVisible] = useState(false);
  const exitTimer = useRef<number | undefined>(undefined);

  useEffect(() => {
    if (selectedCount > 0) {
      window.clearTimeout(exitTimer.current);
      setMounted(true);
      // 先以隐藏态插入 DOM，下一帧再切入可见态，保证 CSS 过渡生效
      const raf = requestAnimationFrame(() => setVisible(true));

      return () => cancelAnimationFrame(raf);
    }
    setVisible(false);
    exitTimer.current = window.setTimeout(
      () => setMounted(false),
      EXIT_ANIMATION_MS,
    );

    return () => window.clearTimeout(exitTimer.current);
  }, [selectedCount]);

  const handleKeyDown = useCallback(
    (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        table.resetRowSelection();
      }
    },
    [table],
  );

  // 未选中行时不订阅（Esc 监听条件生效）
  useEventListener(
    getWindow(),
    "keydown",
    selectedCount > 0 ? handleKeyDown : null,
  );

  if (!mounted) return null;

  const hasActions = children != null;

  return (
    <div className="pointer-events-none fixed inset-x-0 bottom-6 z-40 flex justify-center">
      <div
        aria-live="polite"
        className={cn(
          "pointer-events-auto flex items-center gap-1 rounded-full border border-border bg-overlay py-1.5 ps-3 pe-1.5 shadow-lg transition-all duration-200 ease-out motion-reduce:transition-none",
          visible ? "translate-y-0 opacity-100" : "translate-y-3 opacity-0",
          className,
        )}
      >
        <span className="sr-only">
          {t("common.datatable.selected", { count: selectedCount })}
        </span>
        <Chip className="mx-1 shrink-0" size="sm">
          {selectedCount}
        </Chip>
        {hasActions && (
          <Separator className="h-5 self-center" orientation="vertical" />
        )}
        {children}
        {hasActions && (
          <Separator className="h-5 self-center" orientation="vertical" />
        )}
        <Button
          isIconOnly
          aria-label={t("common.datatable.clearSelection")}
          size="sm"
          variant="ghost"
          onPress={() => table.resetRowSelection()}
        >
          <X className="size-4" />
        </Button>
      </div>
    </div>
  );
}
