// vue/src/features/users/UsersPage.vue
<script setup lang="ts">
import type { User, UserStatus } from "@/lib/api-types";
import type {
  AppColumnDef,
  AppTable,
} from "@/components/data-table/table-types";

import { h, computed, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useQueryClient } from "@tanstack/vue-query";
import { useTable } from "@tanstack/vue-table";
import { useToast } from "@nuxt/ui/composables";
import UBadge from "@nuxt/ui/runtime/components/Badge.vue";
import UCheckbox from "@nuxt/ui/runtime/components/Checkbox.vue";

import {
  USERS_QUERY_KEY,
  batchDeleteUsers,
  deleteUser,
  getUserErrorMessage,
  updateUserStatus,
} from "./user-api";
import UserFormDialog from "./UserFormDialog.vue";
import UserResetPasswordDialog from "./UserResetPasswordDialog.vue";
import UsersLinksCell from "./UsersLinksCell.vue";
import UsersRolesCell from "./UsersRolesCell.vue";
import UsersRowActions from "./UsersRowActions.vue";

import ConfirmDialog from "@/components/common/ConfirmDialog.vue";
import ErrorContent from "@/components/common/ErrorContent.vue";
import UserInfo from "@/components/common/UserInfo.vue";
import DataTable from "@/components/data-table/DataTable.vue";
import DataTableBulkActions from "@/components/data-table/DataTableBulkActions.vue";
import DataTablePagination from "@/components/data-table/DataTablePagination.vue";
import DataTableSearchReset from "@/components/data-table/DataTableSearchReset.vue";
import DataTableToolbar from "@/components/data-table/DataTableToolbar.vue";
import { appTableFeatures } from "@/components/data-table/table-types";
import { useMenuPermissions } from "@/composables/use-permissions";
import { useListQuery } from "@/composables/use-list-query";
import { createListStore } from "@/lib/list-store";
import { formatDateTime } from "@/lib/format-date";
import { SUPER_ADMIN_ROLE_CODE } from "@/lib/constants";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 用户管理页（对齐 React 端 users-page）：服务端分页列表
 * （page/pageSize/search/status/sort/order）+ CRUD + 状态切换 + 重置密码 + 批量操作。
 *
 * - 列表状态入模块级 list store（导航返回保留），由 useListQuery 装配请求；
 * - username 创建后锁定；编辑不含密码，改密走重置密码弹窗；
 * - 写操作保护（v1.4.6）：本人/内置 admin/绑定 super_admin 的用户不可被
 *   删除/停用/重置密码（操作者为 super_admin 时豁免第三条），后端为契约级
 *   强制校验，前端隐藏入口止损；受保护用户亦不可勾选；
 * - 批量状态切换无后端批量端点：Promise.allSettled 逐行调用，部分成功语义。
 */

/** 列表 store（模块级单例：导航返回复用同一份分页/筛选状态） */
const usersListStore = createListStore<{ status: string | null }>({
  status: null,
});

const { t, locale } = useI18n();
const toast = useToast();
const queryClient = useQueryClient();
const auth = useAuthStore();

const currentUserId = computed(() => auth.user?.id);
const currentUserIsSuperAdmin = computed(
  () => auth.user?.roles.includes("super_admin") ?? false,
);

/** 目标用户是否受写操作保护（删除/停用/重置密码入口隐藏条件，v1.4.6） */
function isProtectedUser(user: User) {
  return (
    user.id === currentUserId.value ||
    user.username === "admin" ||
    (user.roles.some((r) => r.code === SUPER_ADMIN_ROLE_CODE) &&
      !currentUserIsSuperAdmin.value)
  );
}

const { canAdd, canEdit, canDelete, canBatchDelete, canResetPassword } =
  useMenuPermissions();

// ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
const store = usersListStore;

const { data, pagination, isLoading, isFetching, isError, refetch } =
  useListQuery<User, { status: string | null }>({
    store,
    queryKeyPrefix: USERS_QUERY_KEY,
    path: "/users",
    buildFilters: (f) => (f.status ? { status: f.status } : {}),
  });

// 搜索（提交式后端过滤，后端匹配 username/email/displayName 三字段）
const searchInput = ref(store.search);

function applySearch() {
  store.setSearch(searchInput.value.trim());
}

const searchDirty = computed(() => searchInput.value.trim() !== store.search);

function resetFilters() {
  searchInput.value = "";
  store.reset();
}

const filterOptions = computed(() => [
  { label: t("features.users.filter.active"), value: "active" },
  { label: t("features.users.filter.disabled"), value: "disabled" },
]);

// ---------------- 弹窗状态 ----------------
const formOpen = ref(false);
const formMode = ref<"create" | "edit">("create");
const formUser = ref<User | null>(null);

const resetPwdOpen = ref(false);
const resetTarget = ref<User | null>(null);

const deleteOpen = ref(false);
const deleteTarget = ref<User | null>(null);

const batchDeleteOpen = ref(false);
const batchDeleteIds = ref<string[]>([]);

const statusOpen = ref(false);
const statusTarget = ref<{ users: User[]; next: UserStatus } | null>(null);

function openForm(mode: "create" | "edit", user: User | null) {
  formMode.value = mode;
  formUser.value = user;
  formOpen.value = true;
}

/** 列表失效：USERS_QUERY_KEY 前缀覆盖全部分页/筛选组合 */
function invalidateList() {
  void queryClient.invalidateQueries({ queryKey: USERS_QUERY_KEY });
}

// ---------------- 表格（TanStack vue-table，服务端分页/排序受控） ----------------
const columns = computed<AppColumnDef<User>[]>(() => [
  {
    id: "select",
    enableSorting: false,
    enableHiding: false,
    header: ({ table: headerTable }) =>
      h(UCheckbox, {
        modelValue: headerTable.getIsAllPageRowsSelected(),
        "onUpdate:modelValue": (value: unknown) =>
          headerTable.toggleAllPageRowsSelected(Boolean(value)),
      }),
    cell: ({ row }) =>
      h(UCheckbox, {
        modelValue: row.getIsSelected(),
        disabled: !row.getCanSelect(),
        "onUpdate:modelValue": (value: unknown) =>
          row.toggleSelected(Boolean(value)),
      }),
  },
  {
    id: "user",
    enableSorting: false,
    header: () => t("features.users.column.user"),
    cell: ({ row }) => h(UserInfo, { user: row.original }),
  },
  {
    accessorKey: "username",
    header: () => t("features.users.column.username"),
    cell: ({ row }) =>
      h("span", { class: "text-sm font-medium" }, row.original.username),
  },
  {
    accessorKey: "status",
    enableSorting: true,
    header: () => t("features.users.column.status"),
    cell: ({ row }) =>
      h(
        "span",
        { class: "flex justify-center" },
        h(UBadge, {
          color: row.original.status === "active" ? "success" : "error",
          label: t(
            row.original.status === "active"
              ? "features.users.filter.active"
              : "features.users.filter.disabled",
          ),
          variant: "soft",
        }),
      ),
  },
  {
    id: "gender",
    enableSorting: false,
    header: () => t("features.users.column.gender"),
    cell: ({ row }) =>
      h(
        "span",
        { class: "text-sm" },
        row.original.gender
          ? t(
              row.original.gender === "male"
                ? "features.users.gender.male"
                : "features.users.gender.female",
            )
          : "—",
      ),
  },
  {
    id: "deptName",
    enableSorting: false,
    header: () => t("features.users.column.dept"),
    cell: ({ row }) =>
      h("span", { class: "text-sm" }, row.original.deptName ?? "—"),
  },
  {
    id: "roles",
    enableSorting: false,
    header: () => t("features.users.column.roles"),
    cell: ({ row }) => h(UsersRolesCell, { roles: row.original.roles }),
  },
  {
    id: "links",
    enableSorting: false,
    header: () => t("features.users.column.links"),
    cell: ({ row }) => h(UsersLinksCell, { user: row.original }),
  },
  {
    // 后端排序白名单不含 lastLoginAt，禁用排序避免静默回退 createdAt
    accessorKey: "lastLoginAt",
    enableSorting: false,
    header: () => t("features.users.column.lastLoginAt"),
    cell: ({ row }) =>
      h(
        "span",
        { class: "text-muted text-sm" },
        row.original.lastLoginAt
          ? formatDateTime(row.original.lastLoginAt, locale.value)
          : "—",
      ),
  },
  {
    accessorKey: "createdAt",
    header: () => t("common.column.createdAt"),
    cell: ({ row }) =>
      h(
        "span",
        { class: "text-muted text-sm" },
        formatDateTime(row.original.createdAt, locale.value),
      ),
  },
  {
    id: "actions",
    enableSorting: false,
    enableHiding: false,
    header: () => t("common.actions"),
    cell: ({ row }) => {
      const user = row.original;
      // 写操作保护（v1.4.6）：受保护用户隐藏删除与重置密码；启用不受保护约束
      const isProtected = isProtectedUser(user);
      const canToggle =
        canEdit.value && !(isProtected && user.status === "active");
      const nextStatus: UserStatus =
        user.status === "active" ? "disabled" : "active";

      if (!canEdit.value && !canDelete.value && !canResetPassword.value) {
        return null;
      }

      return h(UsersRowActions, {
        user,
        canEdit: canEdit.value,
        canDelete: canDelete.value,
        canResetPassword: canResetPassword.value,
        isProtected,
        nextStatus,
        canToggle,
        onAction: (key) => {
          if (key === "edit") openForm("edit", user);
          if (key === "reset-password") {
            resetTarget.value = user;
            resetPwdOpen.value = true;
          }
          if (key === "toggle" && canToggle) {
            statusTarget.value = { users: [user], next: nextStatus };
            statusOpen.value = true;
          }
          if (key === "delete" && canDelete.value && !isProtected) {
            deleteTarget.value = user;
            deleteOpen.value = true;
          }
        },
      });
    },
  },
]);

const table: AppTable<User> = useTable({
  get data() {
    return data.value;
  },
  get columns() {
    return columns.value;
  },
  features: appTableFeatures,
  getRowId: (row: User) => row.id,
  // 写操作保护：受保护用户不可被勾选（从源头排除批量删除/停用命中，v1.4.6）
  enableRowSelection: (row: { original: User }) =>
    !isProtectedUser(row.original),
  // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
  manualPagination: true,
  manualSorting: true,
  pageCount: Math.max(1, Math.ceil(pagination.value.total / store.pageSize)),
  state: {
    get pagination() {
      return { pageIndex: store.page - 1, pageSize: store.pageSize };
    },
    get sorting() {
      return store.sorting;
    },
  },
  onPaginationChange: (updater) => {
    const next =
      typeof updater === "function"
        ? updater({ pageIndex: store.page - 1, pageSize: store.pageSize })
        : updater;

    if (next.pageSize !== store.pageSize) {
      store.setPageSize(next.pageSize);
    } else {
      store.setPage(next.pageIndex + 1);
    }
  },
  onSortingChange: (updater) => {
    const next =
      typeof updater === "function" ? updater(store.sorting) : updater;

    store.setSorting(next);
  },
});

/** 状态切换（单个/批量共用）：Promise.allSettled 逐行调用，
 * 部分成功不回滚；结束统一失效列表反映真实状态并清空勾选。 */
async function confirmStatusChange() {
  const target = statusTarget.value;

  if (!target) return;

  const results = await Promise.allSettled(
    target.users.map((user) => updateUserStatus(user.id, target.next)),
  );

  invalidateList();
  table.resetRowSelection();

  const failed = results.filter((result) => result.status === "rejected");

  if (failed.length === 0) {
    toast.add({
      color: "success",
      duration: 5000,
      title:
        target.users.length === 1
          ? t("features.users.message.statusChangeSuccess")
          : t("features.users.message.batchStatusSuccess", {
              count: target.users.length,
            }),
    });

    return;
  }

  toast.add({
    color: "warning",
    duration: 5000,
    title: t("features.users.message.batchStatusPartial", {
      ok: target.users.length - failed.length,
      fail: failed.length,
    }),
  });

  // 首个失败原因透出（多为 USER_NOT_FOUND：该用户已被他人删除）
  const firstError = failed[0];

  if (firstError.status === "rejected") {
    toast.add({
      color: "error",
      duration: 5000,
      title: getUserErrorMessage(firstError.reason),
    });
  }
}

async function confirmDelete() {
  if (!deleteTarget.value) return;

  try {
    await deleteUser(deleteTarget.value.id);
  } catch (error) {
    toast.add({
      color: "error",
      duration: 5000,
      title: getUserErrorMessage(error),
    });

    return; // 失败保持弹窗打开（ConfirmDialog 约定）
  }

  invalidateList();
  // 与 logs 页口径一致：删除后清理勾选残留
  table.resetRowSelection();
  deleteOpen.value = false;
  toast.add({
    color: "success",
    duration: 5000,
    title: t("features.users.message.deleteSuccess"),
  });
}

async function confirmBatchDelete() {
  try {
    await batchDeleteUsers(batchDeleteIds.value);
  } catch (error) {
    toast.add({
      color: "error",
      duration: 5000,
      title: getUserErrorMessage(error),
    });

    return;
  }

  invalidateList();
  table.resetRowSelection();
  batchDeleteOpen.value = false;
  toast.add({
    color: "success",
    duration: 5000,
    title: t("features.users.message.deleteSuccess"),
  });
}

const selectedUsers = computed(() =>
  table.getSelectedRowModel().rows.map((row) => row.original),
);
</script>

<template>
  <div class="flex w-full flex-col pb-8">
    <DataTableToolbar>
      <UInput
        v-model="searchInput"
        :aria-label="t('features.users.searchPlaceholder')"
        :placeholder="t('features.users.searchPlaceholder')"
        class="w-64"
        icon="i-lucide-search"
        size="sm"
        @keyup.enter="applySearch"
      />
      <USelect
        :aria-label="t('features.users.column.status')"
        :items="filterOptions"
        :model-value="store.filters.status ?? undefined"
        :placeholder="t('features.users.filter.all')"
        class="w-36"
        size="sm"
        value-key="value"
        @update:model-value="
          (value: unknown) => store.setFilters({ status: value as string })
        "
      />
      <DataTableSearchReset
        :can-reset="
          searchDirty || store.search !== '' || store.filters.status !== null
        "
        :fetching="isFetching"
        :search-dirty="searchDirty"
        @reset="resetFilters"
        @search="applySearch"
      />
      <template #actions>
        <UButton
          v-if="canAdd"
          :label="t('features.users.action.add')"
          icon="i-lucide-plus"
          size="sm"
          variant="outline"
          @click="openForm('create', null)"
        />
      </template>
    </DataTableToolbar>

    <ErrorContent
      v-if="isError"
      :retry-label="t('common.retry')"
      :title="t('common.loadError')"
      @retry="refetch()"
    />
    <DataTable
      v-else
      :loading="isLoading"
      :min-width="'860px'"
      :refreshing="isFetching && !isLoading"
      :table="table"
    />

    <DataTablePagination
      :page-index="store.page - 1"
      :page-size="store.pageSize"
      :table="table"
      :total="pagination.total"
    />

    <DataTableBulkActions :table="table">
      <template v-if="canEdit">
        <UButton
          :label="t('features.users.bulk.enable')"
          icon="i-lucide-power"
          size="sm"
          variant="ghost"
          @click="
            statusTarget = { users: selectedUsers, next: 'active' };
            statusOpen = true;
          "
        />
        <UButton
          :label="t('features.users.bulk.disable')"
          icon="i-lucide-power-off"
          size="sm"
          variant="ghost"
          @click="
            statusTarget = { users: selectedUsers, next: 'disabled' };
            statusOpen = true;
          "
        />
      </template>
      <UButton
        v-if="canBatchDelete"
        :label="t('features.users.bulk.delete')"
        icon="i-lucide-trash-2"
        color="error"
        size="sm"
        variant="soft"
        @click="
          batchDeleteIds = selectedUsers.map((user) => user.id);
          batchDeleteOpen = true;
        "
      />
    </DataTableBulkActions>

    <UserFormDialog
      v-model:open="formOpen"
      :mode="formMode"
      :user="formUser"
      @saved="invalidateList"
    />

    <UserResetPasswordDialog
      v-model:open="resetPwdOpen"
      :user="resetPwdOpen ? resetTarget : null"
      @saved="invalidateList"
    />

    <ConfirmDialog
      v-model:open="deleteOpen"
      :confirm-keyword="deleteTarget?.username"
      :confirm-text="t('common.delete')"
      :description="
        t('features.users.message.deleteDesc', {
          name: deleteTarget?.username ?? '',
        })
      "
      :keyword-label="t('features.users.message.deleteKeyword')"
      :title="t('features.users.message.deleteTitle')"
      destructive
      @confirm="confirmDelete"
    />

    <ConfirmDialog
      v-model:open="batchDeleteOpen"
      :confirm-keyword="'DELETE'"
      :confirm-text="t('common.delete')"
      :description="
        t('features.users.message.batchDeleteDesc', {
          count: batchDeleteIds.length,
        })
      "
      :keyword-label="t('features.users.message.batchDeleteKeyword')"
      :title="t('features.users.message.batchDeleteTitle')"
      destructive
      @confirm="confirmBatchDelete"
    />

    <ConfirmDialog
      v-model:open="statusOpen"
      :confirm-text="
        statusTarget?.next === 'disabled'
          ? t('features.users.action.disable')
          : t('features.users.action.enable')
      "
      :description="
        statusTarget
          ? statusTarget.users.length === 1
            ? statusTarget.next === 'disabled'
              ? t('features.users.message.disableDesc', {
                  name: statusTarget.users[0]?.username ?? '',
                })
              : t('features.users.message.enableDesc', {
                  name: statusTarget.users[0]?.username ?? '',
                })
            : statusTarget.next === 'disabled'
              ? t('features.users.message.batchDisableDesc', {
                  count: statusTarget.users.length,
                })
              : t('features.users.message.batchEnableDesc', {
                  count: statusTarget.users.length,
                })
          : null
      "
      :destructive="statusTarget?.next === 'disabled'"
      :title="
        t(
          statusTarget?.next === 'disabled'
            ? 'features.users.message.disableTitle'
            : 'features.users.message.enableTitle',
        )
      "
      @confirm="confirmStatusChange"
    />
  </div>
</template>

// next/src/features/users/users-page.tsx
"use client";

import type { User, UserStatus } from "@/lib/api-types";
import type { AppColumnDef } from "@/components/common/data-table/table-types";

import { useQueryClient } from "@tanstack/react-query";
import { useTable } from "@tanstack/react-table";
import {
  Button,
  Chip,
  Dropdown,
  Label,
  SearchField,
  Tooltip,
  Typography,
  toast,
  useOverlayState,
} from "@heroui/react";
import {
  Globe,
  KeyRound,
  MoreHorizontal,
  Pencil,
  Plus,
  Power,
  PowerOff,
  Trash2,
} from "lucide-react";
import { useCallback, useMemo, useState } from "react";

import {
  USERS_QUERY_KEY,
  batchDeleteUsers,
  deleteUser,
  getUserErrorMessage,
  updateUserStatus,
} from "./user-api";
import { UserFormDialog, type UserFormMode } from "./user-form-dialog";
import { UserResetPasswordDialog } from "./user-reset-password-dialog";

import { buildProfileLinks, openExternalLink } from "@/lib/profile-links";
import { GithubIcon, XIcon } from "@/lib/brand-icons";
import { DataTable } from "@/components/common/data-table";
import {
  DataTableBulkActions,
  DataTableFilterSelect,
  DataTablePagination,
  DataTableSearchReset,
  DataTableSelectAll,
  DataTableSelectRow,
  DataTableToolbar,
  buildColumnSettingKey,
} from "@/components/common/data-table";
import { ConfirmDialog } from "@/components/common/confirm-dialog/confirm-dialog";
import { ErrorContent } from "@/components/common/error-content/error-content";
import { appTableFeatures } from "@/components/common/data-table/table-types";
import { UserInfo } from "@/components/common/user-info/user-info";
import { useMenuPermissions } from "@/hooks/use-permissions";
import { createListStore } from "@/hooks/create-list-store";
import { useListQuery } from "@/hooks/use-list-query";
import { useTranslation } from "@/i18n";
import { useAuthStore } from "@/stores/auth-store";

/**
 * 用户管理页：服务端分页列表（page/pageSize/search/status/sort/order）+
 * CRUD + 状态切换 + 重置密码 + 批量操作。
 *
 * - 列表状态（分页/搜索/排序/筛选）入 feature store（keepAlive 友好），
 *   由 useListQuery 装配请求与 queryKey；status 筛选刷新后丢失为既定行为
 *   （与角色管理一致，见方案确认记录）；
 * - username 创建后锁定；编辑不含密码，改密走重置密码弹窗；
 * - 写操作保护（v1.4.6，前后端双层）：本人/内置 admin/绑定 super_admin
 *   的用户不可被删除/停用/重置密码（操作者为 super_admin 时豁免第三条），
 *   后端为契约级强制校验，前端隐藏入口止损；
 * - 批量状态切换无后端批量端点：Promise.allSettled 逐行调用，
 *   部分成功语义（成功 X 失败 Y），不回滚已成功的行。
 */

/** 列表 store（模块级单例：保活实例复用同一份分页/筛选状态） */
const useUsersListStore = createListStore<{ status: string | null }>({
  status: null,
});

export function UsersPage() {
  const { t } = useTranslation();
  const queryClient = useQueryClient();
  const currentUserId = useAuthStore((state) => state.user?.id);
  // 规则 3 豁免：当前登录用户自身为 super_admin 时可操作其他 super_admin 用户
  const currentUserIsSuperAdmin = useAuthStore(
    (state) => state.user?.roles.includes("super_admin") ?? false,
  );

  /**
   * 目标用户是否受写操作保护（删除/停用/重置密码入口隐藏条件，v1.4.6）：
   * 本人、内置 admin 用户、绑定 super_admin 角色的用户
   * （操作者自身为 super_admin 时豁免最后一条，与后端校验对齐）。
   */
  const isProtectedUser = useCallback(
    (user: User) =>
      user.id === currentUserId ||
      user.username === "admin" ||
      (user.roles.some((r) => r.code === "super_admin") &&
        !currentUserIsSuperAdmin),
    [currentUserId, currentUserIsSuperAdmin],
  );

  const { canAdd, canEdit, canDelete, canBatchDelete, canResetPassword } =
    useMenuPermissions();

  // ---------------- 列表（服务端分页 + 筛选 + 排序） ----------------
  const page = useUsersListStore((s) => s.page);
  const pageSize = useUsersListStore((s) => s.pageSize);
  const search = useUsersListStore((s) => s.search);
  const sorting = useUsersListStore((s) => s.sorting);
  const filters = useUsersListStore((s) => s.filters);
  const setSearch = useUsersListStore((s) => s.setSearch);
  const setPage = useUsersListStore((s) => s.setPage);
  const setPageSize = useUsersListStore((s) => s.setPageSize);
  const setSorting = useUsersListStore((s) => s.setSorting);
  const setFilters = useUsersListStore((s) => s.setFilters);
  const resetStore = useUsersListStore((s) => s.reset);

  const { data, pagination, isLoading, isFetching, isError, refetch } =
    useListQuery<User, { status: string | null }>({
      store: useUsersListStore,
      queryKeyPrefix: USERS_QUERY_KEY,
      path: "/users",
      buildFilters: (f) => (f.status ? { status: f.status } : {}),
    });

  // 搜索（提交式后端过滤，后端匹配 username/email/displayName 三字段）
  const [searchInput, setSearchInput] = useState(search);
  const applySearch = useCallback(
    () => setSearch(searchInput.trim()),
    [setSearch, searchInput],
  );
  const searchDirty = searchInput.trim() !== search;

  const resetFilters = useCallback(() => {
    setSearchInput("");
    resetStore();
  }, [resetStore]);

  const filterOptions = useMemo(
    () => [
      { value: "active", label: t("features.users.filter.active") },
      { value: "disabled", label: t("features.users.filter.disabled") },
    ],
    [t],
  );

  // ---------------- 弹窗状态（useOverlayState，§7.2 受控浮层语义） ----------------
  const userDialog = useOverlayState();
  const resetPwdDialog = useOverlayState();
  const deleteDialog = useOverlayState();
  const batchDeleteDialog = useOverlayState();
  const statusDialog = useOverlayState();

  const [formContext, setFormContext] = useState<{
    mode: UserFormMode;
    user: User | null;
  }>({ mode: "create", user: null });
  const [resetTarget, setResetTarget] = useState<User | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<User | null>(null);
  const [batchDeleteIds, setBatchDeleteIds] = useState<string[]>([]);
  const [statusTarget, setStatusTarget] = useState<{
    users: User[];
    next: UserStatus;
  } | null>(null);

  const openForm = useCallback(
    (mode: UserFormMode, user: User | null) => {
      setFormContext({ mode, user });
      userDialog.open();
    },
    [userDialog],
  );

  // ---------------- 变更操作 ----------------
  /** 列表失效：USERS_QUERY_KEY 前缀覆盖全部分页/筛选组合 */
  const invalidateList = useCallback(() => {
    void queryClient.invalidateQueries({ queryKey: USERS_QUERY_KEY });
  }, [queryClient]);

  /**
   * 状态切换（单个/批量共用）：Promise.allSettled 逐行调用，
   * 部分成功不回滚；结束统一失效列表反映真实状态。
   */

  // ---------------- 表格 ----------------
  const columns = useMemo<AppColumnDef<User>[]>(
    () => [
      {
        id: "select",
        enableSorting: false,
        enableHiding: false,
        header: ({ table }) => <DataTableSelectAll table={table} />,
        cell: ({ row }) => <DataTableSelectRow row={row} />,
      },
      {
        // 用户信息合并列：头像 + 姓名 + 邮箱（UserInfo 统一组件）
        id: "user",
        enableSorting: false,
        header: t("features.users.column.user"),
        cell: ({ row }) => <UserInfo className="min-w-0" user={row.original} />,
      },
      {
        accessorKey: "username",
        header: t("features.users.column.username"),
        cell: ({ row }) => (
          <Typography className="font-medium" type="body-sm">
            {row.original.username}
          </Typography>
        ),
      },
      {
        accessorKey: "status",
        enableSorting: true,
        meta: { align: "center" },
        header: t("features.users.column.status"),
        cell: ({ row }) => (
          <Chip
            color={row.original.status === "active" ? "success" : "danger"}
            size="sm"
            variant="soft"
          >
            {t(
              row.original.status === "active"
                ? "features.users.filter.active"
                : "features.users.filter.disabled",
            )}
          </Chip>
        ),
      },
      {
        // 性别（契约 v1.6.0 阶段 2 补充；未设置显示 —）
        id: "gender",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.users.column.gender"),
        cell: ({ row }) => (
          <Typography type="body-sm">
            {row.original.gender
              ? t(
                  row.original.gender === "male"
                    ? "features.users.gender.male"
                    : "features.users.gender.female",
                )
              : "—"}
          </Typography>
        ),
      },
      {
        // 所属组织（契约 v1.6.0 组织中心；组织被删/未关联显示 —）
        id: "deptName",
        enableSorting: false,
        header: t("features.users.column.dept"),
        cell: ({ row }) => (
          <Typography type="body-sm">{row.original.deptName ?? "—"}</Typography>
        ),
      },
      {
        id: "roles",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.users.column.roles"),
        cell: ({ row }) => {
          const roles = row.original.roles;

          if (roles.length === 0) {
            return (
              <Typography color="muted" type="body-sm">
                —
              </Typography>
            );
          }

          // 角色可能较多：单元格内最多展示 2 个，剩余以 +N 聚合（悬停显示全量）
          const visibleRoles = roles.slice(0, 2);
          const extraCount = roles.length - visibleRoles.length;

          return (
            <div className="flex flex-wrap items-center justify-center gap-1">
              {visibleRoles.map((role) => (
                <Chip key={role.id} size="sm">
                  {role.name}
                </Chip>
              ))}
              {extraCount > 0 && (
                <Tooltip delay={0}>
                  <Tooltip.Trigger aria-label={t("features.users.rolesMore")}>
                    <Chip size="sm">+{extraCount}</Chip>
                  </Tooltip.Trigger>
                  <Tooltip.Content>
                    {roles.map((role) => role.name).join("、")}
                    <Tooltip.Arrow />
                  </Tooltip.Content>
                </Tooltip>
              )}
            </div>
          );
        },
      },
      {
        id: "links",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.users.column.links"),
        cell: ({ row }) => {
          const links = buildProfileLinks(row.original);

          if (links.length === 0) {
            return (
              <Typography color="muted" type="body-sm">
                —
              </Typography>
            );
          }

          const name = row.original.displayName || row.original.username;

          return (
            <div className="flex items-center justify-center gap-1">
              {links.map((link) => (
                <Tooltip key={link.key} delay={0}>
                  <Tooltip.Trigger aria-label={`${name} ${t(link.labelKey)}`}>
                    <Button
                      isIconOnly
                      size="sm"
                      variant="ghost"
                      onPress={() => openExternalLink(link.url)}
                    >
                      {link.key === "website" ? (
                        // 主页用 lucide 通用图标；GitHub / X 为品牌图形走 Simple Icons
                        <Globe className="size-4" />
                      ) : link.key === "github" ? (
                        <GithubIcon className="size-4" />
                      ) : (
                        <XIcon className="size-4" />
                      )}
                    </Button>
                  </Tooltip.Trigger>
                  <Tooltip.Content>
                    {t(link.labelKey)} · {link.url}
                    <Tooltip.Arrow />
                  </Tooltip.Content>
                </Tooltip>
              ))}
            </div>
          );
        },
      },
      {
        // 后端排序白名单不含 lastLoginAt，禁用排序避免静默回退 createdAt
        accessorKey: "lastLoginAt",
        enableSorting: false,
        meta: { align: "center" },
        header: t("features.users.column.lastLoginAt"),
        cell: ({ row }) => (
          <Typography color="muted" type="body-sm">
            {row.original.lastLoginAt
              ? new Date(row.original.lastLoginAt).toLocaleString()
              : "—"}
          </Typography>
        ),
      },
      {
        accessorKey: "createdAt",
        meta: { align: "center" },
        header: t("common.column.createdAt"),
        cell: ({ row }) => (
          <Typography color="muted" type="body-sm">
            {new Date(row.original.createdAt).toLocaleString()}
          </Typography>
        ),
      },
      {
        id: "actions",
        enableSorting: false,
        enableHiding: false,
        meta: { align: "center" },
        header: t("common.actions"),
        cell: ({ row }) => {
          // 写操作保护（v1.4.6，后端强制校验 + 前端隐藏入口止损）：
          // 受保护用户隐藏删除与重置密码；停用/启用按目标状态分别判定——
          // 启用不受保护约束（后端仅拦停用），已停用的受保护用户可被启用
          const isProtected = isProtectedUser(row.original);
          const canToggle =
            canEdit && !(isProtected && row.original.status === "active");
          const nextStatus: UserStatus =
            row.original.status === "active" ? "disabled" : "active";

          if (!canEdit && !canDelete && !canResetPassword) return null;

          return (
            <Dropdown>
              <Button
                isIconOnly
                aria-label={t("common.actions")}
                size="sm"
                variant="ghost"
              >
                <MoreHorizontal className="size-4" />
              </Button>
              <Dropdown.Popover className="min-w-36">
                <Dropdown.Menu
                  onAction={(key) => {
                    if (key === "edit") openForm("edit", row.original);
                    if (key === "reset-password") {
                      setResetTarget(row.original);
                      resetPwdDialog.open();
                    }
                    if (key === "toggle" && canToggle) {
                      setStatusTarget({
                        users: [row.original],
                        next: nextStatus,
                      });
                      statusDialog.open();
                    }
                    if (key === "delete" && canDelete && !isProtected) {
                      setDeleteTarget(row.original);
                      deleteDialog.open();
                    }
                  }}
                >
                  {canEdit && (
                    <Dropdown.Item id="edit" textValue={t("common.edit")}>
                      <Pencil className="size-4 shrink-0 text-muted" />
                      <Label>{t("common.edit")}</Label>
                    </Dropdown.Item>
                  )}
                  {canResetPassword && !isProtected && (
                    <Dropdown.Item
                      id="reset-password"
                      textValue={t("features.users.action.resetPassword")}
                    >
                      <KeyRound className="size-4 shrink-0 text-muted" />
                      <Label>{t("features.users.action.resetPassword")}</Label>
                    </Dropdown.Item>
                  )}
                  {canToggle && (
                    <Dropdown.Item
                      id="toggle"
                      textValue={t(
                        row.original.status === "active"
                          ? "features.users.action.disable"
                          : "features.users.action.enable",
                      )}
                    >
                      <Power
                        className={
                          row.original.status === "active"
                            ? "size-4 shrink-0 text-danger"
                            : "size-4 shrink-0 text-muted"
                        }
                      />
                      <Label>
                        {t(
                          row.original.status === "active"
                            ? "features.users.action.disable"
                            : "features.users.action.enable",
                        )}
                      </Label>
                    </Dropdown.Item>
                  )}
                  {canDelete && !isProtected && (
                    <Dropdown.Item
                      id="delete"
                      textValue={t("common.delete")}
                      variant="danger"
                    >
                      <Trash2 className="size-4 shrink-0 text-danger" />
                      <Label>{t("common.delete")}</Label>
                    </Dropdown.Item>
                  )}
                </Dropdown.Menu>
              </Dropdown.Popover>
            </Dropdown>
          );
        },
      },
    ],
    [
      t,
      canEdit,
      canDelete,
      canResetPassword,
      isProtectedUser,
      openForm,
      resetPwdDialog,
      deleteDialog,
      statusDialog,
    ],
  );

  const total = pagination.total;
  const table = useTable({
    columns,
    data,
    features: appTableFeatures,
    getRowId: (row) => row.id,
    // 写操作保护：受保护用户不可被勾选（从源头排除批量删除/停用命中，v1.4.6）
    enableRowSelection: (row) => !isProtectedUser(row.original),
    // 服务端分页 + 服务端排序：状态由列表 store 驱动（受控），仅取数
    manualPagination: true,
    manualSorting: true,
    pageCount: Math.max(1, Math.ceil(total / pageSize)),
    state: {
      pagination: { pageIndex: page - 1, pageSize },
      sorting,
    },
    onPaginationChange: (updater) => {
      const next =
        typeof updater === "function"
          ? updater({ pageIndex: page - 1, pageSize })
          : updater;

      if (next.pageSize !== pageSize) {
        setPageSize(next.pageSize);
      } else {
        setPage(next.pageIndex + 1);
      }
    },
    onSortingChange: (updater) => {
      setSorting(typeof updater === "function" ? updater(sorting) : updater);
    },
  });

  const selectedUsers = table
    .getSelectedRowModel()
    .rows.map((row) => row.original);

  /** 状态切换（单个/批量共用）：Promise.allSettled 逐行调用，
   * 部分成功不回滚；结束统一失效列表反映真实状态并清空勾选。 */
  const confirmStatusChange = useCallback(async () => {
    if (!statusTarget) return;
    const { users, next } = statusTarget;
    const results = await Promise.allSettled(
      users.map((user) => updateUserStatus(user.id, next)),
    );

    invalidateList();
    table.resetRowSelection();

    const failed = results.filter((result) => result.status === "rejected");

    if (failed.length === 0) {
      toast.success(
        users.length === 1
          ? t("features.users.message.statusChangeSuccess")
          : t("features.users.message.batchStatusSuccess", {
              count: users.length,
            }),
      );

      return;
    }
    toast.warning(
      t("features.users.message.batchStatusPartial", {
        ok: users.length - failed.length,
        fail: failed.length,
      }),
    );
    // 首个失败原因透出（多为 USER_NOT_FOUND：该用户已被他人删除）
    const firstError = failed[0];

    if (firstError.status === "rejected") {
      toast.danger(getUserErrorMessage(firstError.reason));
    }
  }, [statusTarget, invalidateList, table, t]);

  const confirmDelete = useCallback(async () => {
    if (!deleteTarget) return;
    try {
      await deleteUser(deleteTarget.id);
    } catch (error) {
      toast.danger(getUserErrorMessage(error));
      throw error; // ConfirmDialog 约定：抛错保持弹窗打开
    }
    invalidateList();
    // 与 logs 页口径一致：删除后清理勾选残留（表头全选框据此判定）
    table.resetRowSelection();
    toast.success(t("features.users.message.deleteSuccess"));
  }, [deleteTarget, invalidateList, table, t]);

  const confirmBatchDelete = useCallback(async () => {
    try {
      await batchDeleteUsers(batchDeleteIds);
    } catch (error) {
      toast.danger(getUserErrorMessage(error));
      throw error;
    }
    invalidateList();
    table.resetRowSelection();
    toast.success(t("features.users.message.deleteSuccess"));
  }, [batchDeleteIds, invalidateList, table, t]);

  return (
    <div className="flex w-full flex-col pb-8">
      <DataTableToolbar
        columnSettingKey={
          currentUserId
            ? buildColumnSettingKey(currentUserId, "/settings/users")
            : undefined
        }
        table={table}
      >
        <SearchField
          aria-label={t("features.users.searchPlaceholder")}
          className="w-64"
          value={searchInput}
          variant="secondary"
          onChange={setSearchInput}
          onSubmit={applySearch}
        >
          <SearchField.Group>
            <SearchField.SearchIcon />
            <SearchField.Input
              placeholder={t("features.users.searchPlaceholder")}
            />
            <SearchField.ClearButton />
          </SearchField.Group>
        </SearchField>
        {/* 状态筛选在搜索按钮前（与输入条件一起提交）；不选默认全部 */}
        <DataTableFilterSelect
          aria-label={t("features.users.column.status")}
          options={filterOptions}
          placeholder={t("features.users.filter.all")}
          value={filters.status}
          onChange={(value) => setFilters({ status: value })}
        />
        <DataTableSearchReset
          canReset={searchDirty || search !== "" || filters.status !== null}
          isFetching={isFetching}
          searchDirty={searchDirty}
          onReset={resetFilters}
          onSearch={applySearch}
        />
        {canAdd && (
          <Button
            size="sm"
            variant="outline"
            onPress={() => openForm("create", null)}
          >
            <Plus className="size-4" />
            {t("features.users.action.add")}
          </Button>
        )}
      </DataTableToolbar>

      {isError ? (
        <ErrorContent
          action={
            <Button
              size="sm"
              variant="secondary"
              onPress={() => void refetch()}
            >
              {t("common.retry")}
            </Button>
          }
          title={t("common.loadError")}
        />
      ) : (
        <DataTable
          aria-label={t("menu.pageTitle.users")}
          className="w-full"
          contentClassName="min-w-[860px]"
          isLoading={isLoading || isFetching}
          table={table}
        />
      )}

      <DataTablePagination table={table} total={total} />

      <DataTableBulkActions table={table}>
        {canEdit && (
          <>
            <Button
              size="sm"
              variant="ghost"
              onPress={() => {
                setStatusTarget({ users: selectedUsers, next: "active" });
                statusDialog.open();
              }}
            >
              <Power className="size-4" />
              {t("features.users.bulk.enable")}
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onPress={() => {
                setStatusTarget({ users: selectedUsers, next: "disabled" });
                statusDialog.open();
              }}
            >
              <PowerOff className="size-4" />
              {t("features.users.bulk.disable")}
            </Button>
          </>
        )}
        {canBatchDelete && (
          <Button
            size="sm"
            variant="danger-soft"
            onPress={() => {
              setBatchDeleteIds(selectedUsers.map((user) => user.id));
              batchDeleteDialog.open();
            }}
          >
            <Trash2 className="size-4" />
            {t("features.users.bulk.delete")}
          </Button>
        )}
      </DataTableBulkActions>

      <UserFormDialog
        isOpen={userDialog.isOpen}
        mode={formContext.mode}
        user={formContext.user}
        onOpenChange={userDialog.setOpen}
        onSaved={invalidateList}
      />

      <UserResetPasswordDialog
        isOpen={resetPwdDialog.isOpen}
        user={resetPwdDialog.isOpen ? resetTarget : null}
        onOpenChange={resetPwdDialog.setOpen}
        onSaved={invalidateList}
      />

      <ConfirmDialog
        destructive
        confirmKeyword={deleteTarget?.username}
        confirmText={t("common.delete")}
        description={t("features.users.message.deleteDesc", {
          name: deleteTarget?.username ?? "",
        })}
        keywordLabel={t("features.users.message.deleteKeyword")}
        state={{
          isOpen: deleteDialog.isOpen,
          setOpen: deleteDialog.setOpen,
          close: deleteDialog.close,
        }}
        title={t("features.users.message.deleteTitle")}
        onConfirm={confirmDelete}
      />

      <ConfirmDialog
        destructive
        confirmKeyword="DELETE"
        confirmText={t("common.delete")}
        description={t("features.users.message.batchDeleteDesc", {
          count: batchDeleteIds.length,
        })}
        keywordLabel={t("features.users.message.batchDeleteKeyword")}
        state={{
          isOpen: batchDeleteDialog.isOpen,
          setOpen: batchDeleteDialog.setOpen,
          close: batchDeleteDialog.close,
        }}
        title={t("features.users.message.batchDeleteTitle")}
        onConfirm={confirmBatchDelete}
      />

      <ConfirmDialog
        confirmText={
          statusTarget?.next === "disabled"
            ? t("features.users.action.disable")
            : t("features.users.action.enable")
        }
        description={
          statusTarget
            ? statusTarget.users.length === 1
              ? statusTarget.next === "disabled"
                ? t("features.users.message.disableDesc", {
                    name: statusTarget.users[0]?.username ?? "",
                  })
                : t("features.users.message.enableDesc", {
                    name: statusTarget.users[0]?.username ?? "",
                  })
              : statusTarget.next === "disabled"
                ? t("features.users.message.batchDisableDesc", {
                    count: statusTarget.users.length,
                  })
                : t("features.users.message.batchEnableDesc", {
                    count: statusTarget.users.length,
                  })
            : null
        }
        destructive={statusTarget?.next === "disabled"}
        // 启用为非破坏性操作：accent 图标（destructive 时恒为 danger，此值被忽略）
        iconStatus="accent"
        state={{
          isOpen: statusDialog.isOpen,
          setOpen: statusDialog.setOpen,
          close: statusDialog.close,
        }}
        title={t(
          statusTarget?.next === "disabled"
            ? "features.users.message.disableTitle"
            : "features.users.message.enableTitle",
        )}
        onConfirm={confirmStatusChange}
      />
    </div>
  );
}
