// vue/src/features/users/UserResetPasswordDialog.vue
<script setup lang="ts">
import type { User } from "@/lib/api-types";
import type { FormSubmitEvent } from "@nuxt/ui";

import * as z from "zod";
import { computed, h, reactive, ref, useTemplateRef, watch } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import { getUserErrorMessage, resetUserPassword } from "./user-api";
import PasswordField from "./PasswordField.vue";

import Spinner from "@/components/ui/spinner/index.vue";

/**
 * 重置密码弹窗：POST /users/:id/reset-password（RESET_PASSWORD 位）。
 *
 * 后端行为：bcrypt 重新散列 + tokenVersion+1 + 物理清空该用户全部
 * refreshTokens——成功后该用户所有已登录设备即刻下线，需重新登录。
 */
const props = defineProps<{
  open: boolean;
  user: User | null;
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
  /** 重置成功（页面统一做列表失效） */
  saved: [];
}>();

const FORM_ID = "user-reset-password-form";

const { t } = useI18n();
const toast = useToast();

// 一致性跨字段校验：不匹配时错误挂 confirmPassword 字段
const schema = z
  .object({
    newPassword: z.string().min(6, {
      error: () => t("features.users.form.passwordInvalid"),
    }),
    confirmPassword: z.string(),
  })
  .superRefine((data, ctx) => {
    if (data.newPassword !== data.confirmPassword) {
      ctx.addIssue({
        code: "custom",
        path: ["confirmPassword"],
        message: t("features.users.form.confirmPasswordMismatch"),
      });
    }
  });

type Schema = z.output<typeof schema>;

const state = reactive<Schema>({ newPassword: "", confirmPassword: "" });
const formRef = useTemplateRef("formRef");
const submitting = ref(false);

watch(
  () => props.open,
  (open) => {
    if (open) {
      state.newPassword = "";
      state.confirmPassword = "";
      formRef.value?.clear();
    }
  },
);

const displayName = computed(
  () => props.user && (props.user.displayName || props.user.username),
);

function close() {
  emit("update:open", false);
}

async function onSubmit(event: FormSubmitEvent<Schema>) {
  if (!props.user) return;

  submitting.value = true;

  // toast.promise 形态（对齐 React 端）：重置全程 loading toast，
  // 完成后原位替换为成功/失败；duration 0 保证请求返回前不消失
  //（update 会重置计时回落全局时长）；icon 用 Spinner 组件（toast
  // 内容支持 VNode），自带旋转动画
  const savingToast = toast.add({
    title: t("features.users.resetPassword.saving"),
    icon: h(Spinner, { size: "sm", class: "mt-0.5" }),
    color: "info",
    duration: 0,
  });

  try {
    await resetUserPassword(props.user.id, event.data.newPassword);

    toast.update(savingToast.id, {
      title: t("features.users.resetPassword.success"),
      icon: "i-lucide-check",
      color: "success",
    });
    emit("saved");
    close();
  } catch (error) {
    toast.update(savingToast.id, {
      title: getUserErrorMessage(error),
      icon: "i-lucide-x",
      color: "error",
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <UModal
    :open="open"
    :dismissible="false"
    :title="t('features.users.resetPassword.title')"
    :ui="{ content: 'sm:max-w-md', footer: 'justify-end' }"
    @update:open="(value: boolean) => !value && close()"
  >
    <template #body>
      <UForm
        :id="FORM_ID"
        ref="formRef"
        :schema="schema"
        :state="state"
        class="flex flex-col gap-4"
        @submit="onSubmit"
      >
        <p class="text-muted text-sm">
          {{
            t("features.users.resetPassword.desc", {
              name: displayName ?? "",
            })
          }}
        </p>

        <PasswordField
          v-model="state.newPassword"
          :label="t('features.users.resetPassword.newPassword')"
          :placeholder="t('features.users.form.passwordPlaceholder')"
          name="newPassword"
        />

        <PasswordField
          v-model="state.confirmPassword"
          :label="t('features.users.resetPassword.confirmPassword')"
          :placeholder="t('features.users.resetPassword.confirmPassword')"
          name="confirmPassword"
        />
      </UForm>
    </template>

    <template #footer="{ close: onClose }">
      <UButton
        :label="t('common.cancel')"
        color="neutral"
        variant="outline"
        @click="onClose"
      />
      <UButton
        :form="FORM_ID"
        :label="
          submitting
            ? t('features.users.resetPassword.saving')
            : t('features.users.resetPassword.submit')
        "
        :loading="submitting"
        type="submit"
      />
    </template>
  </UModal>
</template>

// next/src/features/users/user-reset-password-dialog.tsx
"use client";

import type { User } from "@/lib/api-types";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { Button, Form, Modal, Spinner, toast } from "@heroui/react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { getUserErrorMessage, resetUserPassword } from "./user-api";
import { PasswordField } from "./password-field";

import { useTranslation } from "@/i18n";

/**
 * 重置密码弹窗：POST /users/:id/reset-password（RESET_PASSWORD 位）。
 *
 * 后端行为：bcrypt 重新散列 + tokenVersion+1 + 物理清空该用户全部
 * refreshTokens——成功后该用户所有已登录设备即刻下线，需重新登录。
 */

export interface UserResetPasswordDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  user: User | null;
  /** 重置成功回调（页面统一做列表失效） */
  onSaved: () => void;
}

const FORM_ID = "user-reset-password-form";

const resetPasswordSchema = z
  .object({
    newPassword: z.string().min(6),
    confirmPassword: z.string(),
  })
  .refine((values) => values.newPassword === values.confirmPassword, {
    message: "confirmPasswordMismatch",
    path: ["confirmPassword"],
  });

type ResetPasswordValues = z.infer<typeof resetPasswordSchema>;

export function UserResetPasswordDialog({
  isOpen,
  onOpenChange,
  user,
  onSaved,
}: UserResetPasswordDialogProps) {
  // Modal 结构渲染在有 mutation 的内层组件（ResetPasswordFormModal），
  // 保证 Modal.Footer 是 Modal.Dialog 的直接子元素（Body 滚动、Footer 固定）
  return isOpen && user ? (
    <ResetPasswordFormModal
      key={user.id}
      isOpen
      user={user}
      onOpenChange={onOpenChange}
      onSaved={onSaved}
    />
  ) : null;
}

interface ResetPasswordFormProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  user: User;
  onSaved: () => void;
}

function ResetPasswordFormModal({
  isOpen,
  onOpenChange,
  user,
  onSaved,
}: ResetPasswordFormProps) {
  const { t } = useTranslation();

  const { control, handleSubmit } = useForm<ResetPasswordValues>({
    resolver: zodResolver(resetPasswordSchema),
    defaultValues: { newPassword: "", confirmPassword: "" },
  });

  const mutation = useMutation({
    mutationFn: (values: ResetPasswordValues) =>
      resetUserPassword(user.id, values.newPassword),
    // 提示反馈统一由 onSubmit 的 toast.promise 呈现（loading → success/error）；
    // 成功副作用（缓存失效联动、关弹窗）保留在此
    onSuccess: () => {
      onSaved();
      onOpenChange(false);
    },
  });

  const onSubmit = handleSubmit((values) => {
    toast.promise(mutation.mutateAsync(values), {
      loading: t("features.users.resetPassword.saving"),
      success: t("features.users.resetPassword.success"),
      error: (error) => getUserErrorMessage(error),
    });
  });

  return (
    <Modal.Backdrop
      isKeyboardDismissDisabled
      isDismissable={false}
      isOpen={isOpen}
      onOpenChange={onOpenChange}
    >
      <Modal.Container>
        <Modal.Dialog className="sm:max-w-md">
          <Modal.CloseTrigger />
          <Modal.Header>
            <Modal.Heading>
              {t("features.users.resetPassword.title")}
            </Modal.Heading>
          </Modal.Header>
          <Modal.Body>
            <Form
              className="flex flex-col gap-4"
              id={FORM_ID}
              validationBehavior="aria"
              onSubmit={(event) => void onSubmit(event)}
            >
              <div className="text-sm text-muted">
                {t("features.users.resetPassword.desc", {
                  name: user.displayName || user.username,
                })}
              </div>

              <Controller
                control={control}
                name="newPassword"
                render={({ field, fieldState }) => (
                  <PasswordField
                    autoComplete="new-password"
                    error={
                      fieldState.error
                        ? t("features.users.form.passwordInvalid")
                        : undefined
                    }
                    label={t("features.users.resetPassword.newPassword")}
                    placeholder={t("features.users.form.passwordPlaceholder")}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  />
                )}
              />

              <Controller
                control={control}
                name="confirmPassword"
                render={({ field, fieldState }) => (
                  <PasswordField
                    autoComplete="new-password"
                    error={
                      fieldState.error
                        ? t("features.users.form.confirmPasswordMismatch")
                        : undefined
                    }
                    label={t("features.users.resetPassword.confirmPassword")}
                    placeholder={t(
                      "features.users.resetPassword.confirmPassword",
                    )}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  />
                )}
              />
            </Form>
          </Modal.Body>

          <Modal.Footer className="w-full">
            <Button slot="close" variant="secondary">
              {t("common.cancel")}
            </Button>
            <Button form={FORM_ID} isPending={mutation.isPending} type="submit">
              {({ isPending }) =>
                isPending ? (
                  <>
                    <Spinner color="current" size="sm" />
                    {t("features.users.resetPassword.saving")}
                  </>
                ) : (
                  t("features.users.resetPassword.submit")
                )
              }
            </Button>
          </Modal.Footer>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  );
}
