// next/layouts/components/transition-direction-picker.tsx
import { Description, RadioGroup, Radio, cn } from "@heroui/react";
import {
  ArrowDownUp,
  ArrowLeftRight,
  ArrowRightLeft,
  ArrowUpDown,
} from "lucide-react";

import { PickerLabel } from "./picker-label";

import { useDesignThemeStore } from "@/stores/design-theme-store";
import { useTranslation } from "@/i18n";
import { type TransitionDirection } from "@/themes/transition-direction";

const DIRECTION_OPTIONS: {
  value: TransitionDirection;
  labelKey: string;
  icon: typeof ArrowLeftRight;
}[] = [
  {
    value: "ltr",
    labelKey: "layout.prefs.direction.ltr",
    icon: ArrowLeftRight,
  },
  {
    value: "rtl",
    labelKey: "layout.prefs.direction.rtl",
    icon: ArrowRightLeft,
  },
  { value: "ttb", labelKey: "layout.prefs.direction.ttb", icon: ArrowUpDown },
  { value: "btt", labelKey: "layout.prefs.direction.btt", icon: ArrowDownUp },
];

/**
 * 主题动画方向选择器：ltr / rtl / ttb / btt。
 * 切换主题色或主题模式时，ViewTransition 的 clip-path 揭示方向。
 */
export function TransitionDirectionPicker() {
  const transitionDirection = useDesignThemeStore((s) => s.transitionDirection);
  const setTransitionDirection = useDesignThemeStore(
    (s) => s.setTransitionDirection,
  );
  const { t } = useTranslation();

  return (
    <RadioGroup
      aria-label={t("layout.prefs.direction.label")}
      value={transitionDirection}
      variant="secondary"
      onChange={(value) => setTransitionDirection(value as TransitionDirection)}
    >
      <PickerLabel
        labelKey="layout.prefs.direction.label"
        tooltipKey="layout.prefs.direction.tooltip"
      />
      <div className="grid gap-2 grid-cols-2 lg:grid-cols-4 mt-2">
        {DIRECTION_OPTIONS.map(({ value, labelKey, icon: Icon }) => (
          <Radio key={value} className="mt-0" value={value}>
            <Radio.Content
              className={cn(
                "group w-full rounded-lg border border-default px-1 py-2 transition-all",
                "data-[selected=true]:border-accent data-[selected=true]:bg-accent/10 hover:scale-105",
              )}
            >
              <div className="min-w-0 flex items-center justify-center w-full gap-1">
                <Icon className="shrink-0" size={14} />
                <Description className="truncate">{t(labelKey)}</Description>
              </div>
            </Radio.Content>
          </Radio>
        ))}
      </div>
    </RadioGroup>
  );
}

// apps/vue/src/components/layout/prefs/TransitionDirectionPicker.vue
<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";

import PickerLabel from "./PickerLabel.vue";
import PrefOptionGrid from "./PrefOptionGrid.vue";

import { useDesignThemeStore } from "@/stores/design-theme-store";
import {
  TRANSITION_DIRECTIONS,
  type TransitionDirection,
} from "@/themes/transition-direction";

const DIRECTION_ICONS: Record<TransitionDirection, string> = {
  ltr: "i-lucide-arrow-left-right",
  rtl: "i-lucide-arrow-right-left",
  ttb: "i-lucide-arrow-up-down",
  btt: "i-lucide-arrow-down-up",
};

/** 主题动画方向选择器：切换主题色 / 主题模式 / 色彩模式时 clip-path 揭示的方向。 */
const store = useDesignThemeStore();
const { t } = useI18n();

const options = computed(() =>
  TRANSITION_DIRECTIONS.map(({ id, labelKey }) => ({
    value: id,
    label: t(labelKey),
    icon: DIRECTION_ICONS[id],
  })),
);

const model = computed<TransitionDirection>({
  get: () => store.transitionDirection,
  set: (direction) => store.setTransitionDirection(direction),
});
</script>

<template>
  <div class="flex flex-col gap-2">
    <PickerLabel
      label-key="layout.prefs.direction.label"
      tooltip-key="layout.prefs.direction.tooltip"
    />
    <PrefOptionGrid v-model="model" :options="options" :columns="2" />
  </div>
</template>
