// vue/src/components/layout/TagsBar.vue
<script setup lang="ts">
import {
  computed,
  nextTick,
  onBeforeUnmount,
  onMounted,
  ref,
  useTemplateRef,
  watch,
} from "vue";
import { useI18n } from "vue-i18n";
import { useRoute, useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import type { ContextMenuItem } from "@nuxt/ui";

import type { MenuNode } from "@/lib/api-types";
import { useMenus } from "@/composables/use-menus";
import { collectMenuPaths, flattenLeafMenus } from "@/lib/menu-utils";
import {
  LOGIN_REQUIRED_PATHS,
  LOGIN_REQUIRED_PREFIXES,
  resolveRouteTitleKey,
} from "@/lib/route-access";
import { isPinnedTab } from "@/lib/tabs-model";
import { useTabsStore } from "@/stores/tabs-store";

/**
 * 多标签页栏（TagsView，对齐 React 端 tags-bar）：置于顶栏下方，记录路由访问轨迹。
 * - 控制台为固定标签：恒在首位、不可关闭（ensureHomeTab 保证至少一个标签），
 *   结构为「菜单图标 名称 Pin 图标」；普通标签尾部为关闭热区；
 * - 标签主体为 UButton（激活 primary subtle / 未激活 neutral outline），
 *   关闭热区为 Button 内的 span（阻止冒泡避免误触发切换）；中键关闭；
 * - 标签过多时横向滚动（mask 渐隐 + chevron + 滚轮横滚 + 鼠标按住拖拽平移，
 *   隐藏原生滚动条），激活标签自动滚动进可视区；新标签带进场动画（styles/tags-bar.css）；
 * - 右键菜单：UContextMenu 包裹标签列表，capture 阶段记录目标标签
 *   （非标签区域右键不弹出）；
 * - 标题优先取菜单实时数据，其次取 sessionStorage 快照（刷新后立即可渲染
 *   中文标题），两者皆无时显示骨架占位；
 * - 与 KeepAliveOutlet 联动：打开的标签集合约束 KeepAlive include，「关闭标签 = 销毁对应保活实例」。
 */
type TabMenuAction =
  | "refresh"
  | "close"
  | "close-left"
  | "close-right"
  | "close-others"
  | "close-all";

/** chevron 按钮单次滚动距离（px）。 */
const SCROLL_STEP = 160;
/** 判定为拖拽平移的位移阈值（px），避免误吞普通点击。 */
const DRAG_THRESHOLD = 6;

type ShadowState = "none" | "left" | "right" | "both";

const route = useRoute();
const router = useRouter();
const { t } = useI18n();
const { data: menuTree } = useMenus();
const tabsStore = useTabsStore();
const { paths, meta: cachedMeta } = storeToRefs(tabsStore);

// 路由变化 → 登记打开标签（去重追加；控制台恒在首位由 store 保证）
watch(
  () => route.path,
  (path) => tabsStore.openPath(path, path),
  { immediate: true },
);

// 路径 → 标题 / 图标实时映射（菜单数据源；标题经 i18nKey 取词，语言切换即更新）
const liveMetaByPath = computed(() => {
  const map = new Map<string, { title: string; icon?: string }>();

  for (const node of flattenLeafMenus((menuTree.value ?? []) as MenuNode[])) {
    if (node.to) {
      map.set(node.to, {
        title: node.i18nKey ? t(node.i18nKey) : node.label,
        icon: node.icon ? `i-lucide-${node.icon}` : undefined,
      });
    }
  }

  return map;
});

// 菜单就绪 → 权限治理（清理恢复 / 权限变更后不可达的残留标签；登录可达路径豁免）
// + 写入标题快照（新值覆盖旧值并持久化：刷新后无需等菜单接口）
watch(
  menuTree,
  (tree) => {
    if (!tree) return;

    tabsStore.pruneTabs(
      new Set([
        ...collectMenuPaths(tree as MenuNode[]),
        ...LOGIN_REQUIRED_PATHS,
      ]),
      LOGIN_REQUIRED_PREFIXES,
    );
  },
  { immediate: true },
);

watch(
  liveMetaByPath,
  (map) => {
    if (map.size > 0) tabsStore.syncMeta(Object.fromEntries(map));
  },
  { immediate: true },
);

/** 标签展示数据：标题（实时 → 快照 → 路由标题键 → 控制台 → null 骨架）+ 图标。 */
const tabs = computed(() =>
  paths.value.map((path) => {
    const live = liveMetaByPath.value.get(path);
    const cached = cachedMeta.value[path];
    const routeTitleKey = resolveRouteTitleKey(path);
    const title =
      live?.title ??
      cached?.title ??
      (routeTitleKey !== undefined
        ? t(routeTitleKey)
        : isPinnedTab(path)
          ? t("menu.pageTitle.console")
          : null);

    return {
      path,
      title,
      icon: live?.icon ?? cached?.icon,
      active: path === route.path,
      pinned: isPinnedTab(path),
    };
  }),
);

// ── 横向滚动：溢出检测 / 滚轮横滚 / 按住拖拽平移 ──
const scrollEl = useTemplateRef<HTMLDivElement>("scrollEl");
const listEl = useTemplateRef<HTMLUListElement>("listEl");
const shadow = ref<ShadowState>("none");
// 最近一次指针手势是否发生了拖拽平移（吞掉其后的 click，防误切换标签）
let dragMoved = false;
let drag: { startX: number; startScroll: number } | null = null;
let resizeObserver: ResizeObserver | null = null;

/** 由横向剩余滚动量推导 chevron 禁用态与渐隐阴影状态。 */
function updateShadow() {
  const el = scrollEl.value;

  if (!el) return;

  const max = el.scrollWidth - el.clientWidth;

  if (max <= 1) {
    shadow.value = "none";

    return;
  }

  const start = Math.abs(el.scrollLeft);

  if (start > 1 && start < max - 1) shadow.value = "both";
  else if (start > 1) shadow.value = "left";
  else shadow.value = "right";
}

// 滚轮纵向增量转横向滚动（Vue 默认非 passive 监听，允许 preventDefault）
function onWheel(event: WheelEvent) {
  const el = scrollEl.value;

  if (!el || event.deltaY === 0) return;

  event.preventDefault();
  el.scrollLeft += event.deltaMode === 1 ? event.deltaY * 16 : event.deltaY;
}

// 按住拖拽平移（仅鼠标左键）：位移超过阈值判定为拖动并捕获指针，
// 拖动中阻止选中文本；结束后的 click 一律吞掉防止误触发点击
function onPointerDown(event: PointerEvent) {
  if (event.pointerType !== "mouse" || event.button !== 0) return;

  drag = {
    startX: event.clientX,
    startScroll: scrollEl.value?.scrollLeft ?? 0,
  };
  dragMoved = false;
}

function onPointerMove(event: PointerEvent) {
  const el = scrollEl.value;

  if (!drag || !el) return;

  const dx = event.clientX - drag.startX;

  if (!dragMoved && Math.abs(dx) < DRAG_THRESHOLD) return;

  if (!dragMoved) {
    dragMoved = true;
    el.setPointerCapture(event.pointerId);
  }

  event.preventDefault();
  el.scrollLeft = drag.startScroll - dx;
}

function onPointerEnd() {
  drag = null;
}

function onClickCapture(event: MouseEvent) {
  if (!dragMoved) return;

  event.preventDefault();
  event.stopPropagation();
  dragMoved = false;
}

onMounted(() => {
  const el = scrollEl.value;

  if (!el) return;

  updateShadow();
  // 可见性自管理：隐藏原生滚动条后没有滚动条出现改变布局的信号，且新增
  // 标签只增加内容宽度、不改变容器尺寸，需同时观察容器与内容元素
  resizeObserver = new ResizeObserver(updateShadow);
  resizeObserver.observe(el);
  if (listEl.value) resizeObserver.observe(listEl.value);
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  resizeObserver = null;
});

// 激活标签自动滚动进可视区
watch(
  () => [route.path, paths.value.length] as const,
  async () => {
    await nextTick();
    scrollEl.value
      ?.querySelector<HTMLElement>('[data-tab-active="true"]')
      ?.scrollIntoView({ block: "nearest", inline: "nearest" });
  },
  { immediate: true },
);

const canScrollLeft = computed(
  () => shadow.value === "left" || shadow.value === "both",
);
const canScrollRight = computed(
  () => shadow.value === "right" || shadow.value === "both",
);

/** chevron 定向平滑滚动。 */
function scrollByStep(direction: -1 | 1) {
  scrollEl.value?.scrollBy({
    left: direction * SCROLL_STEP,
    behavior: "smooth",
  });
}

// ── 标签交互 ──

/** 点击标签切换路由（刚发生拖拽平移时忽略，防误触）。 */
function handleSelect(path: string) {
  if (dragMoved || path === route.path) return;

  void router.push(path);
}

/** 关闭单个标签（关闭热区 / 中键共用）；关闭的是当前页则跟随 redirect。 */
function handleClose(path: string) {
  const redirect = tabsStore.closePath(path, route.path);

  if (redirect) void router.push(redirect);
}

/** 中键关闭（auxclick 的 button === 1）。 */
function handleAuxClick(event: MouseEvent, path: string, pinned: boolean) {
  if (event.button === 1 && !pinned) {
    event.preventDefault();
    handleClose(path);
  }
}

// ── 右键菜单：UContextMenu 包裹标签列表，capture 阶段记录目标标签 ──
const ctxTarget = ref<string | null>(null);

function onContextMenuCapture(event: MouseEvent) {
  const target = (event.target as HTMLElement | null)?.closest<HTMLElement>(
    "[data-tab-path]",
  );
  const path = target?.dataset.tabPath ?? null;

  if (!path) {
    // 非标签区域：不弹出自定义菜单（阻止 UContextMenu 的触发监听）
    event.stopPropagation();
    ctxTarget.value = null;

    return;
  }

  ctxTarget.value = path;
}

/** 各动作在当前目标上的可用性（驱动菜单项 disabled）。 */
const ctxAbility = computed(() => {
  const target = ctxTarget.value;

  if (!target || !paths.value.includes(target)) return null;

  if (isPinnedTab(target)) {
    return {
      refresh: true,
      close: false,
      left: false,
      right: false,
      others: false,
      all: false,
    };
  }

  const idx = paths.value.indexOf(target);

  return {
    refresh: true,
    close: true,
    left: paths.value.slice(0, idx).some((p) => !isPinnedTab(p)),
    right: paths.value.slice(idx + 1).some((p) => !isPinnedTab(p)),
    others: paths.value.some((p) => p !== target && !isPinnedTab(p)),
    all: true,
  };
});

/** 执行菜单动作：变更标签并按需导航（redirect 由 store 纯函数计算）。 */
function handleMenuAction(action: TabMenuAction) {
  const target = ctxTarget.value;

  if (!target) return;

  let redirect: string | null = null;

  switch (action) {
    case "refresh":
      tabsStore.refreshPath(target);
      break;
    case "close":
      redirect = tabsStore.closePath(target, route.path);
      break;
    case "close-left":
      redirect = tabsStore.closeLeft(target, route.path);
      break;
    case "close-right":
      redirect = tabsStore.closeRight(target, route.path);
      break;
    case "close-others":
      redirect = tabsStore.closeOthers(target, route.path);
      break;
    case "close-all":
      redirect = tabsStore.closeAll(route.path);
      break;
  }

  if (redirect) void router.push(redirect);
}

const ctxItems = computed<ContextMenuItem[][]>(() => {
  const ability = ctxAbility.value;

  return [
    [
      {
        label: t("layout.tags.refresh"),
        icon: "i-lucide-refresh-cw",
        disabled: !ability?.refresh,
        onSelect: () => handleMenuAction("refresh"),
      },
      {
        label: t("layout.tags.closeLeft"),
        icon: "i-lucide-arrow-left-to-line",
        disabled: !ability?.left,
        onSelect: () => handleMenuAction("close-left"),
      },
      {
        label: t("layout.tags.closeRight"),
        icon: "i-lucide-arrow-right-to-line",
        disabled: !ability?.right,
        onSelect: () => handleMenuAction("close-right"),
      },
      {
        label: t("layout.tags.closeOthers"),
        icon: "i-lucide-square-x",
        disabled: !ability?.others,
        onSelect: () => handleMenuAction("close-others"),
      },
      {
        label: t("layout.tags.closeAll"),
        icon: "i-lucide-circle-x",
        disabled: !ability?.all,
        onSelect: () => handleMenuAction("close-all"),
      },
    ],
    [
      {
        label: t("layout.tags.close"),
        icon: "i-lucide-x",
        color: "error",
        disabled: !ability?.close,
        onSelect: () => handleMenuAction("close"),
      },
    ],
  ];
});
</script>

<template>
  <nav
    class="flex h-10 shrink-0 items-center gap-1 border-b border-default bg-default px-2"
  >
    <!-- 左侧 chevron：仅当左方仍有未展示内容时可用 -->
    <UButton
      :aria-label="t('layout.tags.scrollLeft')"
      class="hidden md:flex"
      color="neutral"
      :disabled="!canScrollLeft"
      icon="i-lucide-chevron-left"
      size="xs"
      variant="ghost"
      @click="scrollByStep(-1)"
    />

    <UContextMenu :items="ctxItems" :ui="{ content: 'min-w-40' }">
      <!-- 手型光标仅在可滚动（溢出）时展示：无可平移内容时提示拖拽会误导 -->
      <div
        ref="scrollEl"
        class="tags-scroll min-w-0 flex-1 overflow-x-auto"
        :class="shadow === 'none' ? '' : 'cursor-grab active:cursor-grabbing'"
        :data-shadow="shadow"
        @scroll.passive="updateShadow"
        @wheel="onWheel"
        @pointerdown="onPointerDown"
        @pointermove="onPointerMove"
        @pointerup="onPointerEnd"
        @pointercancel="onPointerEnd"
        @click.capture="onClickCapture"
        @contextmenu.capture="onContextMenuCapture"
      >
        <ul ref="listEl" class="flex w-max items-center gap-1 px-0.5 py-1.5">
          <li
            v-for="tab in tabs"
            :key="tab.path"
            class="flex shrink-0 items-center"
            data-tab-enter="true"
          >
            <!-- UButton 作为标签主体：图标 名称 尾部标识全部在 Button 内 -->
            <UButton
              :aria-current="tab.active ? 'page' : undefined"
              class="h-7 max-w-44 min-w-0 gap-1.5 px-3"
              :color="tab.active ? 'primary' : 'neutral'"
              :data-tab-active="tab.active"
              :data-tab-path="tab.path"
              size="sm"
              :variant="tab.active ? 'subtle' : 'outline'"
              :ui="{ base: tab.active ? '' : 'ring-default' }"
              @auxclick="handleAuxClick($event, tab.path, tab.pinned)"
              @click="handleSelect(tab.path)"
              @mousedown.middle.prevent
            >
              <UIcon
                v-if="tab.icon"
                :name="tab.icon"
                class="size-3.5 shrink-0"
              />
              <span v-if="tab.title !== null" class="truncate text-xs">
                {{ tab.title }}
              </span>
              <!-- 菜单未就绪且无快照：骨架占位（避免闪现原始路径） -->
              <USkeleton v-else class="h-3 w-14 rounded-full" />
              <UIcon
                v-if="tab.pinned"
                name="i-lucide-pin"
                class="size-3.5 shrink-0 text-muted"
              />
              <!-- 关闭热区：阻止指针 / 点击冒泡，避免触发标签自身的切换 -->
              <span
                v-else-if="tab.title !== null"
                :aria-label="t('layout.tags.closeNamed', { title: tab.title })"
                class="-mr-1 flex size-4 shrink-0 cursor-pointer items-center justify-center rounded-full opacity-50 transition-opacity hover:bg-accented hover:opacity-100"
                role="button"
                tabindex="-1"
                @click.stop.prevent="handleClose(tab.path)"
                @pointerdown.stop
              >
                <UIcon name="i-lucide-x" class="size-3" />
              </span>
            </UButton>
          </li>
        </ul>
      </div>
    </UContextMenu>

    <!-- 右侧 chevron -->
    <UButton
      :aria-label="t('layout.tags.scrollRight')"
      class="hidden md:flex"
      color="neutral"
      :disabled="!canScrollRight"
      icon="i-lucide-chevron-right"
      size="xs"
      variant="ghost"
      @click="scrollByStep(1)"
    />
  </nav>
</template>

// react/src/layouts/components/tags-bar.tsx
import type { Key, MouseEvent as ReactMouseEvent } from "react";

import { useEffect, useMemo, useRef, useState } from "react";
import {
  Button,
  Dropdown,
  ScrollShadow,
  Separator,
  Skeleton,
  useOverlayState,
} from "@heroui/react";
import { useLocation, useNavigate } from "@tanstack/react-router";
import {
  ArrowLeftToLine,
  ArrowRightToLine,
  ChevronLeft,
  ChevronRight,
  CircleX,
  Pin,
  RefreshCw,
  SquareX,
  X,
} from "lucide-react";
import { DynamicIcon, type IconName } from "lucide-react/dynamic";

import { useMenus } from "@/hooks/use-menus";
import { useTranslation } from "@/i18n";
import { getMenuLabel } from "@/lib/menu-i18n";
import { type MenuNode } from "@/lib/api-types";
import { collectMenuPaths, flattenLeafMenus } from "@/lib/menu-utils";
import { isPinnedTab } from "@/lib/tabs-model";
import { useTabsStore } from "@/stores/tabs-store";

/** 右键菜单动作 id。 */
type TabMenuAction =
  | "refresh"
  | "close"
  | "close-left"
  | "close-right"
  | "close-others"
  | "close-all";

/** 鼠标中键按键值。 */
const MIDDLE_BUTTON = 1;

/** 鼠标左键按键值。 */
const MAIN_BUTTON = 0;

/** chevron 按钮单次滚动距离（px）。 */
const SCROLL_STEP = 160;

/** 判定为拖拽平移的位移阈值（px），避免误吞普通点击。 */
const DRAG_THRESHOLD = 6;

/** 滚动阴影可见性（含 horizontal 双侧态 leftRight）。 */
type ScrollState =
  | "auto"
  | "both"
  | "top"
  | "bottom"
  | "left"
  | "right"
  | "leftRight"
  | "none";

/**
 * 在捕获阶段截停指针 / 点击事件并向父级（HeroUI Button）隔离，
 * 使「Button 内部的关闭热区」不会误触 Button 自身的 press 导航；
 * click 由本 hook 直接执行关闭回调（React 合成事件已被一并截停）。
 */
function useIsolatedClick(onClose: () => void) {
  const ref = useRef<HTMLSpanElement>(null);
  const onCloseRef = useRef(onClose);

  onCloseRef.current = onClose;

  useEffect(() => {
    const el = ref.current;

    if (!el) return;

    const handle = (event: Event) => {
      event.stopPropagation();

      if (event.type === "click") {
        event.preventDefault();
        onCloseRef.current();
      }
    };

    el.addEventListener("pointerdown", handle, true);
    el.addEventListener("pointerup", handle, true);
    el.addEventListener("click", handle, true);

    return () => {
      el.removeEventListener("pointerdown", handle, true);
      el.removeEventListener("pointerup", handle, true);
      el.removeEventListener("click", handle, true);
    };
  }, []);

  return ref;
}

/**
 * 多标签页栏（TagsView）：置于顶栏下方，记录路由访问轨迹。
 * - 控制台为固定标签：恒在首位、不可关闭（ensureHomeTab 保证至少一个标签），
 *   结构为「菜单图标 名称 Pin 图标」；普通标签尾部为关闭热区；
 * - 标签主体为 HeroUI Button（未激活 outline / 激活 tertiary 原生样式），
 *   关闭热区位于 Button 内部（useIsolatedClick 隔离 press）；
 * - 标签过多时横向滚动（ScrollShadow 渐隐阴影 + chevron + 滚轮横滚 +
 *   鼠标按住拖拽平移，隐藏原生滚动条避免占用固定栏高挤压标签），
 *   激活标签自动滚动进可视区；新标签带进场动画（styles/tags-bar.css）；
 * - 标题优先取菜单实时数据，其次取 sessionStorage 快照（刷新后立即可渲染
 *   中文标题），两者皆无时显示骨架占位；
 * - 与 KeepAliveOutlet 联动：打开的标签集合约束保活实例池，
 *   「关闭标签 = 销毁对应保活实例」。
 */
export function TagsBar() {
  const navigate = useNavigate();
  const { pathname } = useLocation();
  const { data: menuTree } = useMenus();
  const { t } = useTranslation();

  const paths = useTabsStore((s) => s.paths);
  const cachedMeta = useTabsStore((s) => s.meta);
  const openPath = useTabsStore((s) => s.openPath);
  const closePathAction = useTabsStore((s) => s.closePath);
  const closeOthers = useTabsStore((s) => s.closeOthers);
  const closeLeft = useTabsStore((s) => s.closeLeft);
  const closeRight = useTabsStore((s) => s.closeRight);
  const closeAll = useTabsStore((s) => s.closeAll);
  const refreshPath = useTabsStore((s) => s.refreshPath);
  const syncMeta = useTabsStore((s) => s.syncMeta);
  const pruneTabs = useTabsStore((s) => s.pruneTabs);

  // 路由变化 → 登记打开标签（去重追加；控制台恒在首位由 store 保证）。
  useEffect(() => {
    openPath(pathname, pathname);
  }, [pathname, openPath]);

  // 菜单就绪 → 权限治理：清理恢复 / 权限变更后不可达的残留标签。
  useEffect(() => {
    if (!menuTree) return;

    pruneTabs(collectMenuPaths(menuTree as MenuNode[]));
  }, [menuTree, pruneTabs]);

  // 路径 → 标题 / 图标实时映射（菜单数据源；标题经 i18nKey 取词，语言切换即更新）。
  const liveMetaByPath = useMemo(() => {
    const map = new Map<string, { title: string; icon?: string }>();

    for (const node of flattenLeafMenus(menuTree ?? [])) {
      if (node.to) {
        map.set(node.to, { title: getMenuLabel(node, t), icon: node.icon });
      }
    }

    return map;
  }, [menuTree, t]);

  // 菜单就绪 → 写入快照（新值覆盖旧值并持久化：刷新后无需等菜单接口）。
  useEffect(() => {
    if (liveMetaByPath.size === 0) return;

    syncMeta(Object.fromEntries(liveMetaByPath));
  }, [liveMetaByPath, syncMeta]);

  // ── 横向滚动 ──
  const scrollRef = useRef<HTMLDivElement>(null);
  const [visibility, setVisibility] = useState<ScrollState>("none");
  // 最近一次指针手势是否发生了拖拽平移（吞掉其后的 click，防误切换标签）。
  const dragMovedRef = useRef(false);

  // 溢出检测 / 滚轮横滚 / 按住拖拽平移：统一挂在滚动容器上（一次性挂载）。
  // 可见性必须自管理——隐藏原生滚动条后不再有「滚动条出现改变容器
  // content-box」的信号；且新增标签只增加内容宽度、不改变容器尺寸，
  // 需同时用 ResizeObserver 观察内容元素。
  useEffect(() => {
    const el = scrollRef.current;

    if (!el) return;

    /** 由横向剩余滚动量推导 chevron 禁用态与渐隐阴影状态。 */
    const updateVisibility = () => {
      const max = el.scrollWidth - el.clientWidth;

      if (max <= 1) {
        setVisibility("none");

        return;
      }

      const start = Math.abs(el.scrollLeft);

      if (start > 1 && start < max - 1) {
        setVisibility("leftRight");
      } else if (start > 1) {
        setVisibility("left");
      } else {
        setVisibility("right");
      }
    };

    updateVisibility();

    el.addEventListener("scroll", updateVisibility, { passive: true });

    const resizeObserver = new ResizeObserver(updateVisibility);

    resizeObserver.observe(el);

    if (el.firstElementChild) resizeObserver.observe(el.firstElementChild);

    // 滚轮纵向增量转横向滚动（wheel 需 non-passive 才能 preventDefault）。
    const onWheel = (event: WheelEvent) => {
      if (event.deltaY === 0) return;

      event.preventDefault();
      el.scrollLeft += event.deltaMode === 1 ? event.deltaY * 16 : event.deltaY;
    };

    // 按住拖拽平移（仅鼠标左键）：位移超过阈值判定为拖动并捕获指针，
    // 拖动中阻止选中文本；结束后的 click 一律吞掉防止误触发点击。
    let drag: { startX: number; startScroll: number } | null = null;

    const onPointerDown = (event: PointerEvent) => {
      if (event.pointerType !== "mouse" || event.button !== MAIN_BUTTON) return;

      drag = { startX: event.clientX, startScroll: el.scrollLeft };
      dragMovedRef.current = false;
    };

    const onPointerMove = (event: PointerEvent) => {
      if (!drag) return;

      const dx = event.clientX - drag.startX;

      if (!dragMovedRef.current && Math.abs(dx) < DRAG_THRESHOLD) return;

      if (!dragMovedRef.current) {
        dragMovedRef.current = true;
        el.setPointerCapture(event.pointerId);
      }

      event.preventDefault();
      el.scrollLeft = drag.startScroll - dx;
    };

    const onPointerEnd = () => {
      drag = null;
    };

    const onClickCapture = (event: MouseEvent) => {
      if (!dragMovedRef.current) return;

      event.preventDefault();
      event.stopPropagation();
      dragMovedRef.current = false;
    };

    el.addEventListener("wheel", onWheel, { passive: false });
    el.addEventListener("pointerdown", onPointerDown);
    el.addEventListener("pointermove", onPointerMove);
    el.addEventListener("pointerup", onPointerEnd);
    el.addEventListener("pointercancel", onPointerEnd);
    el.addEventListener("click", onClickCapture, true);

    return () => {
      el.removeEventListener("scroll", updateVisibility);
      el.removeEventListener("wheel", onWheel);
      el.removeEventListener("pointerdown", onPointerDown);
      el.removeEventListener("pointermove", onPointerMove);
      el.removeEventListener("pointerup", onPointerEnd);
      el.removeEventListener("pointercancel", onPointerEnd);
      el.removeEventListener("click", onClickCapture, true);
      resizeObserver.disconnect();
    };
  }, []);

  // 激活标签自动滚动进可视区。
  useEffect(() => {
    const active = scrollRef.current?.querySelector<HTMLElement>(
      '[data-tab-active="true"]',
    );

    active?.scrollIntoView({ block: "nearest", inline: "nearest" });
  }, [pathname, paths.length]);

  const canScrollLeft = visibility === "left" || visibility === "leftRight";
  const canScrollRight = visibility === "right" || visibility === "leftRight";

  /** chevron 定向平滑滚动。 */
  const scrollByStep = (direction: -1 | 1) => {
    scrollRef.current?.scrollBy({
      left: direction * SCROLL_STEP,
      behavior: "smooth",
    });
  };

  // ── 右键菜单：HeroUI Dropdown 受控（useOverlayState 管开合）+ 虚拟锚点定位 ──
  const ctxMenu = useOverlayState();
  const [ctxTarget, setCtxTarget] = useState<string | null>(null);
  const [ctxPos, setCtxPos] = useState({ x: 0, y: 0 });

  /** 各动作在当前目标上的可用性（驱动 disabledKeys）。 */
  const ctxAbility = useMemo(() => {
    if (!ctxTarget || !paths.includes(ctxTarget)) return null;

    if (isPinnedTab(ctxTarget)) {
      return {
        refresh: true,
        close: false,
        left: false,
        right: false,
        others: false,
        all: false,
      };
    }

    const idx = paths.indexOf(ctxTarget);

    return {
      refresh: true,
      close: true,
      left: paths.slice(0, idx).some((p) => !isPinnedTab(p)),
      right: paths.slice(idx + 1).some((p) => !isPinnedTab(p)),
      others: paths.some((p) => p !== ctxTarget && !isPinnedTab(p)),
      all: true,
    };
  }, [ctxTarget, paths]);

  const disabledKeys = useMemo<string[]>(() => {
    if (!ctxAbility) return [];

    return (
      [
        ["refresh", ctxAbility.refresh],
        ["close", ctxAbility.close],
        ["close-left", ctxAbility.left],
        ["close-right", ctxAbility.right],
        ["close-others", ctxAbility.others],
        ["close-all", ctxAbility.all],
      ] as const
    )
      .filter(([, enabled]) => !enabled)
      .map(([key]) => key);
  }, [ctxAbility]);

  /** 打开右键菜单：记录鼠标坐标与目标标签。 */
  const openContextMenu = (event: ReactMouseEvent, path: string) => {
    event.preventDefault();
    setCtxTarget(path);
    setCtxPos({ x: event.clientX, y: event.clientY });
    ctxMenu.open();
  };

  /** 执行菜单动作：变更标签并按需导航（redirect 由 store 纯函数计算）。 */
  const handleMenuAction = (key: Key) => {
    const target = ctxTarget;

    if (!target) return;

    let redirect: string | null = null;

    switch (key as TabMenuAction) {
      case "refresh":
        refreshPath(target);

        break;
      case "close":
        redirect = closePathAction(target, pathname);

        break;
      case "close-left":
        redirect = closeLeft(target, pathname);

        break;
      case "close-right":
        redirect = closeRight(target, pathname);

        break;
      case "close-others":
        redirect = closeOthers(target, pathname);

        break;
      case "close-all":
        redirect = closeAll(pathname);

        break;
    }

    if (redirect) void navigate({ href: redirect });
  };

  /** 点击标签切换路由（刚发生拖拽平移时忽略，防误触）。 */
  const handleSelect = (path: string) => {
    if (dragMovedRef.current || path === pathname) return;

    void navigate({ href: path });
  };

  /** 关闭单个标签（关闭热区 / 中键共用）；关闭的是当前页则跟随 redirect。 */
  const handleClose = (path: string) => {
    const redirect = closePathAction(path, pathname);

    if (redirect) void navigate({ href: redirect });
  };

  return (
    <nav className="flex h-10 shrink-0 items-center gap-1 border-b border-separator bg-surface px-2">
      {/* 左侧 chevron：仅当左方仍有未展示内容时可用 */}
      <Button
        isIconOnly
        aria-label={t("layout.tags.scrollLeft")}
        className="hidden size-6 min-w-6 md:flex"
        isDisabled={!canScrollLeft}
        size="sm"
        variant="ghost"
        onPress={() => scrollByStep(-1)}
      >
        <ChevronLeft size={16} />
      </Button>

      <ScrollShadow
        ref={scrollRef}
        hideScrollBar
        // 手型光标仅在可滚动（溢出）时展示：无可平移内容时提示拖拽会误导。
        className={`min-w-0 flex-1 ${
          visibility === "none" ? "" : "cursor-grab active:cursor-grabbing"
        }`}
        orientation="horizontal"
        size={24}
        visibility={visibility === "leftRight" ? "both" : visibility}
      >
        <ul className="flex w-max items-center gap-1 px-0.5 py-1.5">
          {paths.map((path) => {
            const live = liveMetaByPath.get(path);
            const cached = cachedMeta[path];
            const title =
              live?.title ??
              cached?.title ??
              (isPinnedTab(path) ? t("menu.pageTitle.console") : null);
            const icon = live?.icon ?? cached?.icon;
            const active = path === pathname;
            const pinned = isPinnedTab(path);

            return (
              <li
                key={path}
                className="flex shrink-0 items-center"
                data-tab-enter="true"
              >
                {/* HeroUI Button 作为标签主体：图标 名称 尾部标识全部在 Button 内 */}
                <Button
                  aria-current={active ? "page" : undefined}
                  className="h-7 min-w-0 max-w-44 gap-1.5 px-3"
                  data-tab-active={active}
                  size="sm"
                  variant={active ? "tertiary" : "outline"}
                  onAuxClick={(event: ReactMouseEvent<HTMLButtonElement>) => {
                    if (event.button === MIDDLE_BUTTON && !pinned) {
                      // 阻止中键默认行为（自动滚动 / 链接新开）
                      event.preventDefault();
                      handleClose(path);
                    }
                  }}
                  onContextMenu={(event) => openContextMenu(event, path)}
                  onPress={() => handleSelect(path)}
                >
                  {icon && (
                    <DynamicIcon
                      className="shrink-0 size-3.5"
                      name={icon as IconName}
                    />
                  )}
                  {title !== null ? (
                    <span className="truncate text-xs">{title}</span>
                  ) : (
                    /* 菜单未就绪且无快照：骨架占位（避免闪现原始路径） */
                    <Skeleton className="h-3 w-14 rounded-full" />
                  )}
                  {pinned ? (
                    <Pin className="shrink-0 text-muted" size={14} />
                  ) : (
                    title !== null && (
                      <TabCloseTrigger
                        title={title}
                        onClose={() => handleClose(path)}
                      />
                    )
                  )}
                </Button>
              </li>
            );
          })}
        </ul>
      </ScrollShadow>

      {/* 右侧 chevron */}
      <Button
        isIconOnly
        aria-label={t("layout.tags.scrollRight")}
        className="hidden size-6 min-w-6 md:flex"
        isDisabled={!canScrollRight}
        size="sm"
        variant="ghost"
        onPress={() => scrollByStep(1)}
      >
        <ChevronRight size={16} />
      </Button>

      {/* 全局共享的右键菜单：虚拟锚点（1px fixed 按钮）移到鼠标坐标，
          Popover 以 bottom start 对齐锚点，实现 context menu 体验。
          受控流遵循 HeroUI 官方写法：isOpen/onOpenChange 挂最外层 Overlay。 */}
      <Dropdown.Root isOpen={ctxMenu.isOpen} onOpenChange={ctxMenu.setOpen}>
        <Dropdown.Trigger
          aria-hidden="true"
          className="fixed m-0 border-0 bg-transparent p-0 opacity-0 outline-none"
          style={{ left: ctxPos.x, top: ctxPos.y, width: 1, height: 1 }}
        />
        <Dropdown.Popover className="min-w-40" placement="bottom start">
          <Dropdown.Menu
            disabledKeys={disabledKeys}
            onAction={handleMenuAction}
          >
            <Dropdown.Item id="refresh" textValue={t("layout.tags.refresh")}>
              <RefreshCw className="size-4 shrink-0 text-muted" />
              {t("layout.tags.refresh")}
            </Dropdown.Item>
            <Dropdown.Item
              id="close-left"
              textValue={t("layout.tags.closeLeft")}
            >
              <ArrowLeftToLine className="size-4 shrink-0 text-muted" />
              {t("layout.tags.closeLeft")}
            </Dropdown.Item>
            <Dropdown.Item
              id="close-right"
              textValue={t("layout.tags.closeRight")}
            >
              <ArrowRightToLine className="size-4 shrink-0 text-muted" />
              {t("layout.tags.closeRight")}
            </Dropdown.Item>
            <Dropdown.Item
              id="close-others"
              textValue={t("layout.tags.closeOthers")}
            >
              <SquareX className="size-4 shrink-0 text-muted" />
              {t("layout.tags.closeOthers")}
            </Dropdown.Item>
            <Dropdown.Item id="close-all" textValue={t("layout.tags.closeAll")}>
              <CircleX className="size-4 shrink-0 text-muted" />
              {t("layout.tags.closeAll")}
            </Dropdown.Item>

            <Separator />

            <Dropdown.Item
              id="close"
              textValue={t("layout.tags.close")}
              variant="danger"
            >
              <X className="size-4 shrink-0 text-danger" />
              {t("layout.tags.close")}
            </Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown.Popover>
      </Dropdown.Root>
    </nav>
  );
}

/** 标签尾部关闭热区：X 图标 span（位于 Button 内部），经 useIsolatedClick
 * 在捕获阶段截停指针事件（RAC press 与 React 合成 click 均不再触发），
 * 由 hook 直接执行关闭；键盘可达性暂以鼠标为主（后续可加速捷键）。 */
function TabCloseTrigger({
  onClose,
  title,
}: {
  onClose: () => void;
  title: string;
}) {
  const ref = useIsolatedClick(onClose);
  const { t } = useTranslation();

  return (
    <span
      ref={ref}
      aria-label={t("layout.tags.closeNamed", { title })}
      className="-mr-1 flex size-4 shrink-0 cursor-pointer items-center justify-center rounded-full opacity-50 transition-opacity hover:bg-default hover:opacity-100"
      role="button"
    >
      <X className="size-3" />
    </span>
  );
}
