// apps/vue/src/features/org/PostFormDialog.vue
<script setup lang="ts">
import type { DeptTreeNode, Post } from "@/lib/api-types";
import type { FormSubmitEvent } from "@nuxt/ui";
import Spinner from "@/components/ui/spinner/index.vue";
import * as z from "zod";
import { computed, reactive, ref, useTemplateRef, watch, h } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import { createPost, getPostErrorMessage, updatePost } from "./post-api";
import DeptTreeSelect from "./DeptTreeSelect.vue";

/**
 * 岗位新增/编辑弹窗（对应 React 端 post-form-dialog.tsx）：
 * UForm + zod schema 校验（官方范式，@submit 仅在校验通过后触发）。
 *
 * - deptId 用平铺缩进的树选择器（DeptTreeSelect），必填校验阻断提交；
 * - 岗位类别三选一（管理岗 / 专业岗 / 生产岗）；
 * - 同组织岗位名冲突由后端 409（POST_NAME_EXISTS）拦截，
 *   错误文案经 getPostErrorMessage i18n 映射。
 */
const props = defineProps<{
  open: boolean;
  mode: "create" | "edit";
  /** edit：被编辑的岗位；create：null */
  post: Post | null;
  /** 全量组织树（所属组织选择器数据源） */
  tree: DeptTreeNode[];
}>();

const emit = defineEmits<{
  "update:open": [value: boolean];
  /** 保存成功（页面统一做缓存失效） */
  saved: [post: Post, mode: "create" | "edit"];
}>();

const { t } = useI18n();
const toast = useToast();

const FORM_ID = "post-form";

/** 字数统计上限（与后端 @Length 校验及 React 端对齐：名称 100 / 职级 20） */
const NAME_MAX_LENGTH = 100;
const RANK_MAX_LENGTH = 20;

// 校验消息用函数延迟求值：语言切换后错误文案跟随当前 locale
const schema = z.object({
  deptId: z
    .string()
    .min(1, { error: () => t("features.posts.form.deptRequired") }),
  name: z
    .string()
    .trim()
    .min(1, { error: () => t("features.posts.form.nameInvalid") })
    .max(100, { error: () => t("features.posts.form.nameInvalid") }),
  category: z.enum(["management", "professional", "production"]),
  rank: z
    .string()
    .trim()
    .max(20, { error: () => t("features.posts.form.rankInvalid") }),
  status: z.enum(["enabled", "disabled"]),
});

type Schema = z.output<typeof schema>;

const state = reactive<Schema>({
  deptId: "",
  name: "",
  category: "management",
  rank: "",
  status: "enabled",
});
const formRef = useTemplateRef("formRef");
const submitting = ref(false);

const isEdit = computed(() => props.mode === "edit");

const categoryOptions = computed(() =>
  (["management", "professional", "production"] as const).map((value) => ({
    label: t(`features.posts.category.${value}`),
    value,
  })),
);

watch(
  () => props.open,
  (open) => {
    if (!open) return;

    state.deptId = props.post?.deptId ?? "";
    state.name = props.post?.name ?? "";
    // Post.category 契约为 string，表单只产出三枚举之一，断言收窄
    state.category = (props.post?.category ??
      "management") as Schema["category"];
    state.rank = props.post?.rank ?? "";
    state.status = props.post?.status ?? "enabled";
    formRef.value?.clear();
  },
  { immediate: true },
);

function close() {
  emit("update:open", false);
}

async function onSubmit(event: FormSubmitEvent<Schema>) {
  submitting.value = true;

  // toast.promise 形态（对齐 React 端）：保存全程 loading toast，
  // 完成后原位替换为成功/失败；duration 0 保证请求返回前不消失
  const savingToast = toast.add({
    title: t("features.posts.form.saving"),
    icon: h(Spinner, { size: "sm", class: "mt-0.5" }),
    color: "info",
    duration: 0,
  });

  try {
    // event.data 已过 schema 校验转换（name/rank 已 trim）
    const input = {
      name: event.data.name,
      deptId: event.data.deptId,
      category: event.data.category,
      rank: event.data.rank,
      status: event.data.status,
    };

    const saved = isEdit.value
      ? await updatePost(props.post!.id, input)
      : await createPost(input);

    toast.update(savingToast.id, {
      title: t(
        isEdit.value
          ? "features.posts.message.updated"
          : "features.posts.message.created",
      ),
      icon: "i-lucide-check",
      color: "success",
    });

    emit("saved", saved, props.mode);
    close();
  } catch (error) {
    toast.update(savingToast.id, {
      title: getPostErrorMessage(error),
      icon: "i-lucide-x",
      color: "error",
    });
  } finally {
    submitting.value = false;
  }
}
</script>

<script lang="ts">
export default { name: "PostFormDialog" };
</script>

<template>
  <UModal
    :open="open"
    :dismissible="false"
    :title="
      t(
        isEdit
          ? 'features.posts.form.title.edit'
          : 'features.posts.form.title.create',
      )
    "
    :ui="{ content: 'sm:max-w-md', footer: 'justify-end' }"
    @update:open="(value: boolean) => !value && close()"
  >
    <template #body>
      <UForm
        :id="FORM_ID"
        ref="formRef"
        :schema="schema"
        :state="state"
        class="flex flex-col gap-4"
        @submit="onSubmit"
      >
        <UFormField
          :label="t('features.posts.form.dept')"
          name="deptId"
          required
        >
          <DeptTreeSelect
            v-model="state.deptId"
            :placeholder="t('features.org.deptTreeSelect.placeholder')"
            :tree="tree"
            class="w-full"
          />
        </UFormField>

        <UFormField :label="t('features.posts.form.name')" name="name" required>
          <UInput
            v-model="state.name"
            :maxlength="NAME_MAX_LENGTH"
            :placeholder="t('features.posts.form.namePlaceholder')"
            class="w-full"
            :ui="{ base: 'pe-16' }"
          >
            <!-- trailing 实时字数（对齐 React 端 InputGroup.Suffix） -->
            <template #trailing>
              <span class="text-dimmed text-xs tabular-nums">
                {{ state.name.length }}/{{ NAME_MAX_LENGTH }}
              </span>
            </template>
          </UInput>
        </UFormField>

        <UFormField :label="t('features.posts.form.category')" name="category">
          <USelect
            v-model="state.category"
            :items="categoryOptions"
            :placeholder="t('features.posts.form.categoryPlaceholder')"
            class="w-full"
            value-key="value"
          />
        </UFormField>

        <UFormField :label="t('features.posts.form.rank')" name="rank">
          <UInput
            v-model="state.rank"
            :maxlength="RANK_MAX_LENGTH"
            :placeholder="t('features.posts.form.rankPlaceholder')"
            class="w-full"
          />
        </UFormField>

        <div
          class="border-default flex items-center justify-between gap-3 rounded-xl border px-3 py-2"
        >
          <span class="text-sm">
            {{ t("features.posts.form.status") }}
          </span>
          <USwitch
            :aria-label="t('features.posts.form.status')"
            :model-value="state.status === 'enabled'"
            unchecked-icon="i-lucide-x"
            checked-icon="i-lucide-check"
            @update:model-value="
              (value: boolean) =>
                (state.status = value ? 'enabled' : 'disabled')
            "
          />
        </div>
      </UForm>
    </template>

    <template #footer="{ close: onClose }">
      <UButton
        color="neutral"
        :label="t('common.cancel')"
        variant="outline"
        @click="onClose"
      />
      <UButton
        :form="FORM_ID"
        :label="
          submitting ? t('features.posts.form.saving') : t('common.confirm')
        "
        :loading="submitting"
        type="submit"
      />
    </template>
  </UModal>
</template>

// react/src/features/org/post-form-dialog.tsx
import type {
  DeptTreeNode,
  Post,
  PostCategory,
  PostCreateInput,
  PostUpdateInput,
} from "@/lib/api-types";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import {
  Button,
  FieldError,
  Form,
  Input,
  InputGroup,
  Label,
  ListBox,
  Modal,
  Select,
  Spinner,
  Switch,
  TextField,
  toast,
} from "@heroui/react";
import { Check, X } from "lucide-react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import { createPost, getPostErrorMessage, updatePost } from "./post-api";
import { DeptTreeSelect } from "./dept-tree-select";

import { useTranslation } from "@/i18n";

/**
 * 岗位新增/编辑弹窗（react-hook-form + zod + HeroUI Form）。
 *
 * - deptId 用 DeptTreeSelect（平铺缩进树形下拉；不选时为必填校验阻断提交）；
 * - 岗位类别三选一（管理岗 / 专业岗 / 生产岗）；
 * - 同组织岗位名冲突由后端 409（POST_NAME_EXISTS）拦截，文案经 i18n 映射。
 */

export type PostFormMode = "create" | "edit";

export interface PostFormDialogProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: PostFormMode;
  /** edit：被编辑的岗位；create：null */
  post: Post | null;
  /** 全量组织树（所属组织选择器数据源） */
  tree: DeptTreeNode[];
  /** 保存成功回调（页面统一做缓存失效） */
  onSaved: (post: Post, mode: PostFormMode) => void;
}

const FORM_ID = "post-form";

const NAME_MAX_LENGTH = 100;

const postFormSchema = z.object({
  name: z.string().trim().min(1).max(100),
  /** "" = 未选择（提交时阻断提示必填） */
  deptId: z.string().min(1),
  category: z.enum(["management", "professional", "production"]),
  rank: z.string().trim().max(20),
  status: z.enum(["enabled", "disabled"]),
});

type PostFormValues = z.infer<typeof postFormSchema>;

const CATEGORY_OPTIONS: PostCategory[] = [
  "management",
  "professional",
  "production",
];

export function PostFormDialog({
  isOpen,
  onOpenChange,
  mode,
  post,
  tree,
  onSaved,
}: PostFormDialogProps) {
  // Modal 结构渲染在有 mutation 的内层组件（PostFormModal），
  // 保证 Modal.Footer 是 Modal.Dialog 的直接子元素（Body 滚动、Footer 固定）
  return isOpen ? (
    <PostFormModal
      key={`${mode}:${post?.id ?? "new"}`}
      isOpen
      mode={mode}
      post={post}
      tree={tree}
      onOpenChange={onOpenChange}
      onSaved={onSaved}
    />
  ) : null;
}

interface PostFormProps {
  isOpen: boolean;
  onOpenChange: (isOpen: boolean) => void;
  mode: PostFormMode;
  post: Post | null;
  tree: DeptTreeNode[];
  onSaved: (post: Post, mode: PostFormMode) => void;
}

function PostFormModal({
  isOpen,
  onOpenChange,
  mode,
  post,
  tree,
  onSaved,
}: PostFormProps) {
  const { t } = useTranslation();
  const isEdit = mode === "edit";

  const { control, handleSubmit } = useForm<PostFormValues>({
    resolver: zodResolver(postFormSchema),
    defaultValues: {
      name: post?.name ?? "",
      deptId: post?.deptId ?? "",
      category: post?.category ?? "management",
      rank: post?.rank ?? "",
      status: post?.status ?? "enabled",
    },
  });

  const mutation = useMutation({
    mutationFn: (values: PostFormValues) => {
      if (isEdit) {
        const input: PostUpdateInput = {
          name: values.name,
          deptId: values.deptId,
          category: values.category,
          rank: values.rank,
          status: values.status,
        };

        return updatePost(post!.id, input);
      }

      const input: PostCreateInput = {
        name: values.name,
        deptId: values.deptId,
        category: values.category,
        rank: values.rank,
        status: values.status,
      };

      return createPost(input);
    },
    // 提示反馈由 onSubmit 的 toast.promise 呈现；成功副作用（失效联动、关弹窗）在此
    onSuccess: (saved) => {
      onSaved(saved, mode);
      onOpenChange(false);
    },
  });

  const onSubmit = handleSubmit((values) => {
    toast.promise(mutation.mutateAsync(values), {
      loading: t("features.posts.form.saving"),
      success: t(
        isEdit
          ? "features.posts.message.updated"
          : "features.posts.message.created",
      ),
      error: (error) => getPostErrorMessage(error),
    });
  });

  return (
    <Modal.Backdrop
      isKeyboardDismissDisabled
      isDismissable={false}
      isOpen={isOpen}
      onOpenChange={onOpenChange}
    >
      <Modal.Container>
        <Modal.Dialog className="sm:max-w-md">
          <Modal.CloseTrigger />
          <Modal.Header>
            <Modal.Heading>
              {t(
                isEdit
                  ? "features.posts.form.title.edit"
                  : "features.posts.form.title.create",
              )}
            </Modal.Heading>
          </Modal.Header>
          <Modal.Body>
            <Form
              className="flex flex-col gap-4"
              id={FORM_ID}
              // 校验统一交给 react-hook-form（aria 行为避免 required 抢聚焦阻断提交）
              validationBehavior="aria"
              onSubmit={(event) => void onSubmit(event)}
            >
              <Controller
                control={control}
                name="deptId"
                render={({ field, fieldState }) => (
                  <DeptTreeSelect
                    showLabel
                    ariaLabel={t("features.posts.form.dept")}
                    isInvalid={!!fieldState.error}
                    tree={tree}
                    value={field.value}
                    onChange={(key) => field.onChange(key)}
                  />
                )}
              />

              <Controller
                control={control}
                name="name"
                render={({ field, fieldState }) => (
                  <TextField
                    isRequired
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.posts.form.name")}</Label>
                    {/* Suffix 实时字数（上限与后端 @Length(1,100) 对齐） */}
                    <InputGroup variant="secondary">
                      <InputGroup.Input
                        maxLength={NAME_MAX_LENGTH}
                        placeholder={t("features.posts.form.namePlaceholder")}
                      />
                      <InputGroup.Suffix className="text-xs text-muted">
                        {field.value?.length ?? 0}/{NAME_MAX_LENGTH}
                      </InputGroup.Suffix>
                    </InputGroup>
                    {fieldState.error && (
                      <FieldError>
                        {t("features.posts.form.nameInvalid")}
                      </FieldError>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="category"
                render={({ field }) => (
                  <Select
                    aria-label={t("features.posts.form.category")}
                    className="flex w-full flex-col gap-1"
                    placeholder={t("features.posts.form.categoryPlaceholder")}
                    value={field.value}
                    variant="secondary"
                    onChange={(key) =>
                      field.onChange(
                        key === null
                          ? "management"
                          : String(key as PostCategory),
                      )
                    }
                  >
                    <Label>{t("features.posts.form.category")}</Label>
                    <Select.Trigger>
                      <Select.Value />
                      <Select.Indicator />
                    </Select.Trigger>
                    <Select.Popover>
                      <ListBox>
                        {CATEGORY_OPTIONS.map((option) => (
                          <ListBox.Item
                            key={option}
                            id={option}
                            textValue={t(`features.posts.category.${option}`)}
                          >
                            {t(`features.posts.category.${option}`)}
                            <ListBox.ItemIndicator />
                          </ListBox.Item>
                        ))}
                      </ListBox>
                    </Select.Popover>
                  </Select>
                )}
              />

              <Controller
                control={control}
                name="rank"
                render={({ field, fieldState }) => (
                  <TextField
                    className="flex flex-col gap-1"
                    isInvalid={Boolean(fieldState.error)}
                    value={field.value ?? ""}
                    onBlur={field.onBlur}
                    onChange={field.onChange}
                  >
                    <Label>{t("features.posts.form.rank")}</Label>
                    <Input
                      maxLength={20}
                      placeholder={t("features.posts.form.rankPlaceholder")}
                      variant="secondary"
                    />
                    {fieldState.error && (
                      <FieldError>
                        {t("features.posts.form.rankInvalid")}
                      </FieldError>
                    )}
                  </TextField>
                )}
              />

              <Controller
                control={control}
                name="status"
                render={({ field }) => (
                  <div className="flex items-center justify-between gap-3 rounded-3xl border border-border px-3 py-2">
                    <Label>{t("features.posts.form.status")}</Label>
                    <Switch
                      aria-label={t("features.posts.form.status")}
                      isSelected={field.value === "enabled"}
                      onChange={(selected) =>
                        field.onChange(selected ? "enabled" : "disabled")
                      }
                    >
                      {({ isSelected }) => (
                        <Switch.Content>
                          <Switch.Control>
                            <Switch.Thumb>
                              <Switch.Icon>
                                {isSelected ? (
                                  <Check className="size-3 text-inherit opacity-100" />
                                ) : (
                                  <X className="size-3 text-inherit opacity-70" />
                                )}
                              </Switch.Icon>
                            </Switch.Thumb>
                          </Switch.Control>
                        </Switch.Content>
                      )}
                    </Switch>
                  </div>
                )}
              />
            </Form>
          </Modal.Body>

          <Modal.Footer className="w-full">
            <Button slot="close" variant="secondary">
              {t("common.cancel")}
            </Button>
            <Button
              isPending={mutation.isPending}
              onPress={() => void onSubmit()}
            >
              {({ isPending }) =>
                isPending ? (
                  <>
                    <Spinner color="current" size="sm" />
                    {t("features.posts.form.saving")}
                  </>
                ) : (
                  t("common.confirm")
                )
              }
            </Button>
          </Modal.Footer>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  );
}
