// react/src/features/account/cards/email-form-card.tsx
import type { AccountProfile } from "@/lib/api-types";

import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import {
  Button,
  Card,
  FieldError,
  Form,
  Input,
  Label,
  Spinner,
  TextField,
  toast,
} from "@heroui/react";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

import {
  getAccountErrorMessage,
  updateAccountEmail,
  type OnAccountProfileSaved,
} from "../account-api";

import { PasswordInput } from "@/components/common/password-input/password-input";
import { useTranslation } from "@/i18n";

export interface EmailFormCardProps {
  profile: AccountProfile;
  onSaved: OnAccountProfileSaved;
}

const FORM_ID = "account-email-form";

interface EmailFormValues {
  email: string;
  currentPassword: string;
}

const emailFormSchema = z.object({
  email: z.string().trim().email(),
  currentPassword: z.string().min(1),
});

/** 邮箱卡：新邮箱 + 当前密码确认（唯一性由后端校验，冲突 409） */
export function EmailFormCard({ profile, onSaved }: EmailFormCardProps) {
  const { t } = useTranslation();

  const { control, handleSubmit, resetField } = useForm<EmailFormValues>({
    resolver: zodResolver(emailFormSchema),
    defaultValues: { email: profile.email, currentPassword: "" },
  });

  const mutation = useMutation({
    mutationFn: (values: EmailFormValues) =>
      updateAccountEmail({
        email: values.email.trim(),
        currentPassword: values.currentPassword,
      }),
    onSuccess: (updated) => {
      toast.success(t("features.account.email.updateSuccess"));
      resetField("currentPassword");
      onSaved(updated);
    },
    onError: (mutationError) => {
      toast.danger(getAccountErrorMessage(mutationError));
    },
  });

  const onSubmit = handleSubmit((values) => {
    mutation.mutate(values);
  });

  return (
    <Card>
      <Card.Header>
        <Card.Title className="font-bold">
          {t("features.account.email.title")}
        </Card.Title>
        <Card.Description className="text-xs">
          {t("features.account.email.description")}
        </Card.Description>
      </Card.Header>
      <Card.Content>
        <Form
          className="flex flex-col gap-4"
          id={FORM_ID}
          validationBehavior="aria"
          onSubmit={(event) => void onSubmit(event)}
        >
          <Controller
            control={control}
            name="email"
            render={({ field, fieldState }) => (
              <TextField
                className="flex flex-col gap-1"
                isInvalid={Boolean(fieldState.error)}
                value={field.value ?? ""}
                onBlur={field.onBlur}
                onChange={field.onChange}
              >
                <Label>{t("features.account.email.newEmail")}</Label>
                <Input
                  maxLength={254}
                  placeholder={t("features.account.email.emailPlaceholder")}
                  variant="secondary"
                />
                {fieldState.error ? (
                  <FieldError>
                    {t("features.account.email.emailInvalid")}
                  </FieldError>
                ) : null}
              </TextField>
            )}
          />

          <Controller
            control={control}
            name="currentPassword"
            render={({ field, fieldState }) => (
              <div className="flex flex-col gap-1">
                <PasswordInput
                  autoComplete="current-password"
                  label={t("features.account.currentPassword")}
                  placeholder={t("features.account.currentPasswordPlaceholder")}
                  value={field.value ?? ""}
                  onBlur={field.onBlur}
                  onChange={field.onChange}
                />
                {fieldState.error ? (
                  <p className="text-xs text-danger">
                    {t("features.account.currentPasswordRequired")}
                  </p>
                ) : null}
              </div>
            )}
          />
        </Form>
      </Card.Content>
      <Card.Footer className="justify-end border-t border-separator pt-4">
        <Button
          form={FORM_ID}
          isPending={mutation.isPending}
          size="sm"
          type="submit"
        >
          {({ isPending }) =>
            isPending ? (
              <>
                <Spinner color="current" size="sm" />
                {t("features.account.email.updating")}
              </>
            ) : (
              t("features.account.email.update")
            )
          }
        </Button>
      </Card.Footer>
    </Card>
  );
}

// apps/vue/src/features/account/cards/EmailFormCard.vue
<script setup lang="ts">
import type { AccountProfile } from "@/lib/api-types";
import type { FormSubmitEvent } from "@nuxt/ui";

import * as z from "zod";
import { reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { useToast } from "@nuxt/ui/composables";

import { getAccountErrorMessage, updateAccountEmail } from "../account-api";

import PasswordField from "@/components/common/PasswordField.vue";

/** 邮箱卡（对齐 React 端 email-form-card）：新邮箱 + 当前密码确认（唯一性由后端校验，冲突 409） */
const props = defineProps<{ profile: AccountProfile }>();

const emit = defineEmits<{ saved: [updated: AccountProfile] }>();

const FORM_ID = "account-email-form";

const { t } = useI18n();
const toast = useToast();

const schema = z
  .object({
    email: z.string(),
    currentPassword: z.string(),
  })
  .superRefine((data, ctx) => {
    if (!z.email().safeParse(data.email.trim()).success) {
      ctx.addIssue({
        code: "custom",
        path: ["email"],
        message: t("features.account.email.emailInvalid"),
      });
    }

    if (data.currentPassword.length < 1) {
      ctx.addIssue({
        code: "custom",
        path: ["currentPassword"],
        message: t("features.account.currentPasswordRequired"),
      });
    }
  });

type Schema = z.output<typeof schema>;

const state = reactive<Schema>({
  email: props.profile.email,
  currentPassword: "",
});
const submitting = ref(false);

async function onSubmit(event: FormSubmitEvent<Schema>) {
  submitting.value = true;

  try {
    const updated = await updateAccountEmail({
      email: event.data.email.trim(),
      currentPassword: event.data.currentPassword,
    });

    toast.add({
      color: "success",
      title: t("features.account.email.updateSuccess"),
    });
    state.currentPassword = "";
    emit("saved", updated);
  } catch (error) {
    toast.add({ color: "error", title: getAccountErrorMessage(error) });
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <UCard>
    <template #header>
      <h3 class="font-bold">{{ t("features.account.email.title") }}</h3>
      <p class="text-muted text-xs">
        {{ t("features.account.email.description") }}
      </p>
    </template>

    <UForm
      :id="FORM_ID"
      :schema="schema"
      :state="state"
      class="flex flex-col gap-4"
      @submit="onSubmit"
    >
      <UFormField :label="t('features.account.email.newEmail')" name="email">
        <UInput
          v-model="state.email"
          :maxlength="254"
          :placeholder="t('features.account.email.emailPlaceholder')"
          autocomplete="email"
          class="w-full"
          type="email"
        />
      </UFormField>

      <PasswordField
        v-model="state.currentPassword"
        :label="t('features.account.currentPassword')"
        :placeholder="t('features.account.currentPasswordPlaceholder')"
        auto-complete="current-password"
        name="currentPassword"
      />
    </UForm>

    <template #footer>
      <div class="flex justify-end">
        <UButton
          :form="FORM_ID"
          :label="
            submitting
              ? t('features.account.email.updating')
              : t('features.account.email.update')
          "
          :loading="submitting"
          size="sm"
          type="submit"
        />
      </div>
    </template>
  </UCard>
</template>
